/**
 * B-Atlas Decision Report Generator Layer
 * 
 * =========================================================================
 * ARCHITECTURAL DESIGN & COMMENTS
 * =========================================================================
 * 1. Purpose of Decision Reports:
 *    - Decision Reports act as a summary of the evidence generated by the various
 *      evaluations performed during suitability matching.
 *    - They organize and synthesize these outcomes into a structured, buyer-facing
 *      explanation.
 * 
 * 2. Relationships to other Layers:
 *    - They DO NOT replace evaluator logic (such as evaluateFuel or evaluateHullType).
 *      Instead, they consume and categorize the output (evidence) of those evaluators.
 *    - They DO NOT replace scoring. Existing rankings, fitness indices, and BScout legacy
 *      scores are untouched and continue to function as they did before.
 *    - This layer purely constructs the reporting structure; future UI components will
 *      bind to and display this structured decision report information.
 */

/**
 * Generates a structured Decision Report based on the provided Evaluation Context.
 * 
 * @param {Object} evaluationContext - The current boat evaluation context
 * @param {Object} evaluationContext.boat - Raw boat model object
 * @param {Object} evaluationContext.userProfile - Active search/user profile
 * @param {Array} evaluationContext.evaluations - Array of B-Atlas Evaluation Results
 * @returns {Object} Structured Decision Report Object
 */
function generateDecisionReport(evaluationContext) {
    // 1. Initialize Default Structure
    const report = {
        recommendation: "Strong Candidate",
        summary: "This boat matches your current requirements.",
        matches: [],
        conflicts: [],
        unknowns: [],
        actions: [],
        confidence: 100,
        evaluationCount: 0
    };

    // If no context or evaluations array, return the valid empty report safely
    if (!evaluationContext || !Array.isArray(evaluationContext.evaluations)) {
        return report;
    }

    const evaluations = evaluationContext.evaluations;
    report.evaluationCount = evaluations.length;

    // Helper to determine if a requirement is canonical "Required"
    function isReq(ev) {
        if (!ev) return false;
        if (typeof isRequired === "function") {
            return isRequired(ev.requirement);
        }
        return ev.requirement === "Required";
    }

    // 2. Categorize Evaluation Results
    evaluations.forEach(ev => {
        const item = {
            feature: ev.feature || "Unknown",
            explanation: ev.reason || ""
        };

        if (ev.status === "Match") {
            report.matches.push(item);
        } else if (ev.status === "Conflict") {
            report.conflicts.push({
                ...item,
                // keep requirement information for scoring and recommendation rules
                _isRequired: isReq(ev)
            });
        } else if (ev.status === "Unknown") {
            report.unknowns.push({
                ...item,
                _isRequired: isReq(ev)
            });
        }
    });

    // 3. Confidence Calculation
    // Start at 100
    let confidenceScore = 100;
    evaluations.forEach(ev => {
        if (ev.status === "Unknown") {
            confidenceScore -= 10;
        } else if (ev.status === "Conflict") {
            if (isReq(ev)) {
                confidenceScore -= 25;
            } else {
                confidenceScore -= 5;
            }
        }
    });
    // Constrain to [0, 100]
    report.confidence = Math.max(0, Math.min(100, confidenceScore));

    // 4. Generate Summary Text (Deterministic, rule-based)
    if (report.conflicts.length > 0) {
        report.summary = "This boat has one or more requirement conflicts.";
    } else if (report.unknowns.length > 0 && report.matches.length === 0) {
        report.summary = "This boat may be suitable, but additional information is needed.";
    } else {
        report.summary = "This boat matches your current requirements.";
    }

    // 5. Recommendation Field Classification Rules
    const hasRequiredConflict = report.conflicts.some(c => c._isRequired);
    const hasPreferredConflict = report.conflicts.some(c => !c._isRequired);
    const hasImportantUnknown = report.unknowns.some(u => u._isRequired);

    if (hasRequiredConflict) {
        report.recommendation = "Poor Match";
    } else if (hasImportantUnknown) {
        report.recommendation = "Needs Review";
    } else if (hasPreferredConflict) {
        report.recommendation = "Candidate";
    } else if (report.unknowns.length > 0 && report.matches.length === 0) {
        // Only unknowns (no conflicts, no matches, but has unknowns)
        report.recommendation = "Needs Review";
    } else if (report.unknowns.length > 1) {
        // No conflicts, but has multiple (more than 1) unknowns -> Candidate
        report.recommendation = "Candidate";
    } else {
        // No conflicts, and few/no unknowns (0 or 1 unknown) -> Strong Candidate
        report.recommendation = "Strong Candidate";
    }

    // 6. Convert evidence into deterministic buyer next-actions.
    const actionGenerator = typeof generateBuyerActions === "function"
        ? generateBuyerActions
        : (typeof window !== "undefined" && typeof window.generateBuyerActions === "function"
            ? window.generateBuyerActions
            : null);
    report.actions = actionGenerator ? actionGenerator(evaluationContext) : [];

    // Clean up internal properties before returning
    report.conflicts.forEach(c => delete c._isRequired);
    report.unknowns.forEach(u => delete u._isRequired);

    return report;
}

// Expose globally
if (typeof window !== "undefined") {
    window.generateDecisionReport = generateDecisionReport;
}
if (typeof module !== "undefined" && module.exports) {
    module.exports = { generateDecisionReport };
}
