(() => {
const CORE=['FirstYear','LastYear','LOA_ft','Beam_ft','Draft_ft','AirDraft_ft','Displacement_lb','FuelCapacity','WaterCapacity','HoldingCapacity','HullType','Construction','Fuel','Propulsion','TypicalEngineID','Berths','Heads','Shower','Strengths','Weaknesses','CommonProblems','TypicalMission','AvoidIf'];
const state={boats:[],priority:new Set(),selected:null,staged:JSON.parse(localStorage.getItem('bscout-enrichment-staged')||'{}')};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const blank=v=>v===null||v===undefined||v===''||(typeof v==='number'&&Number.isNaN(v));
function merged(b){return {...b,...(state.staged[b.BoatModelID]?.fields||{})}}
function coverage(b){const m=merged(b);return Math.round(100*CORE.filter(k=>!blank(m[k])).length/CORE.length)}
async function init(){const [boats,p]=await Promise.all([fetch('boatmodels.json').then(r=>r.json()),fetch('data/priority-fleet.json').then(r=>r.json())]);state.boats=boats;state.priority=new Set(p.boatModelIds);renderQueue();}
function filtered(){let a=[...state.boats],q=document.querySelector('#search').value.toLowerCase(),f=document.querySelector('#queueFilter').value;if(q)a=a.filter(b=>(b.Manufacturer+' '+b.Model+' '+b.Nickname+' '+b.BoatModelID).toLowerCase().includes(q));if(f==='priority')a=a.filter(b=>state.priority.has(b.BoatModelID));if(f==='staged')a=a.filter(b=>state.staged[b.BoatModelID]);a.sort((x,y)=>f==='incomplete'?coverage(x)-coverage(y):(x.Manufacturer+x.Model).localeCompare(y.Manufacturer+y.Model));return a}
function renderQueue(){const a=filtered();document.querySelector('#queueCount').textContent=`${a.length} models`;document.querySelector('#queue').innerHTML=a.map(b=>`<div class="queue-item ${state.selected===b.BoatModelID?'active':''}" data-id="${b.BoatModelID}"><strong>${esc(b.Nickname||`${b.Manufacturer} ${b.Model}`)}</strong><div class="meta">${b.BoatModelID}${state.staged[b.BoatModelID]?' • staged':''} • ${coverage(b)}%</div><div class="bar"><span style="width:${coverage(b)}%"></span></div></div>`).join('');document.querySelectorAll('.queue-item').forEach(n=>n.onclick=()=>openEditor(n.dataset.id));}
function field(b,k,label,type='text',span=''){const v=merged(b)[k];const control=type==='textarea'?`<textarea data-field="${k}">${esc(v)}</textarea>`:`<input data-field="${k}" type="${type}" value="${esc(v)}">`;return `<div class="field ${blank(v)?'missing':''} ${span}"><label>${label}</label>${control}</div>`}
function openEditor(id){state.selected=id;renderQueue();const b=state.boats.find(x=>x.BoatModelID===id),s=state.staged[id]||{},ev=s.evidence||[],imgs=s.images||[];document.querySelector('#editor').innerHTML=`<div class="editor-head"><div><p class="eyebrow">${b.BoatModelID}</p><h2>${esc(b.Nickname||b.Manufacturer+' '+b.Model)}</h2><p class="meta">Core coverage ${coverage(b)}% • ${CORE.filter(k=>blank(merged(b)[k])).length} missing fields</p></div><span class="status">${state.priority.has(id)?'Priority fleet':'General fleet'}</span></div><div class="editor-body"><div class="grid">
${field(b,'Manufacturer','Manufacturer')}${field(b,'Model','Model')}${field(b,'Variant','Variant')}${field(b,'FirstYear','First year','number')}${field(b,'LastYear','Last year','number')}${field(b,'Designer','Designer')}${field(b,'LOA_ft','LOA (ft)','number')}${field(b,'Beam_ft','Beam (ft)','number')}${field(b,'Draft_ft','Draft (ft)','number')}${field(b,'AirDraft_ft','Air draft (ft)','number')}${field(b,'Displacement_lb','Displacement (lb)','number')}${field(b,'TypicalEngineID','Typical engine')}${field(b,'FuelCapacity','Fuel capacity','number')}${field(b,'WaterCapacity','Water capacity','number')}${field(b,'HoldingCapacity','Holding capacity','number')}${field(b,'HullType','Hull type')}${field(b,'Construction','Construction')}${field(b,'Propulsion','Propulsion')}${field(b,'Strengths','Strengths','textarea','span-3')}${field(b,'Weaknesses','Weaknesses','textarea','span-3')}${field(b,'CommonProblems','Common problems','textarea','span-3')}${field(b,'TypicalMission','Typical mission','textarea','span-3')}${field(b,'AvoidIf','Avoid if','textarea','span-3')}</div>
<div class="section"><h3>Evidence</h3><p class="meta">Record source URLs and the fields they support. Verification remains pending until reviewed.</p><div id="evidenceRows">${ev.map(e=>evidenceRow(e)).join('')}</div><button id="addEvidence">Add evidence</button></div>
<div class="section"><h3>Images</h3><p class="meta">Track candidate image files or source URLs; no image is treated as approved automatically.</p><div id="imageRows">${imgs.map(e=>imageRow(e)).join('')}</div><button id="addImage">Add image</button></div>
<div class="actions"><button class="primary" id="stageBtn">Stage Changes</button><button id="discardBtn">Discard Staged Changes</button><span id="editorStatus"></span></div></div>`;
document.querySelector('#addEvidence').onclick=()=>{document.querySelector('#evidenceRows').insertAdjacentHTML('beforeend',evidenceRow({}));bindRemove()};document.querySelector('#addImage').onclick=()=>{document.querySelector('#imageRows').insertAdjacentHTML('beforeend',imageRow({}));bindRemove()};document.querySelector('#stageBtn').onclick=()=>stage(b);document.querySelector('#discardBtn').onclick=()=>{delete state.staged[id];save();openEditor(id)};bindRemove();}
function evidenceRow(e){return `<div class="evidence-row"><input class="ev-source" placeholder="Source URL or citation" value="${esc(e.source)}"><input class="ev-fields" placeholder="Supported fields, comma separated" value="${esc(e.fields)}"><select class="ev-type"><option>Manufacturer</option><option>Manual</option><option>Review</option><option>Owner Association</option><option>Listing</option></select><button class="remove">×</button></div>`}
function imageRow(e){return `<div class="evidence-row"><input class="img-source" placeholder="File path or source URL" value="${esc(e.source)}"><input class="img-caption" placeholder="View or caption" value="${esc(e.caption)}"><select class="img-status"><option>Candidate</option><option>Reviewed</option><option>Approved</option></select><button class="remove">×</button></div>`}
function bindRemove(){document.querySelectorAll('.remove').forEach(b=>b.onclick=()=>b.parentElement.remove())}
function stage(b){const fields={};document.querySelectorAll('[data-field]').forEach(i=>{let v=i.value.trim();if(i.type==='number')v=v===''?'':Number(v);if(v!==b[i.dataset.field])fields[i.dataset.field]=v});const evidence=[...document.querySelectorAll('#evidenceRows .evidence-row')].map(r=>({source:r.querySelector('.ev-source').value.trim(),fields:r.querySelector('.ev-fields').value.trim(),sourceType:r.querySelector('.ev-type').value,verificationStatus:'PendingReview'})).filter(x=>x.source);const images=[...document.querySelectorAll('#imageRows .evidence-row')].map(r=>({source:r.querySelector('.img-source').value.trim(),caption:r.querySelector('.img-caption').value.trim(),status:r.querySelector('.img-status').value})).filter(x=>x.source);state.staged[b.BoatModelID]={BoatModelID:b.BoatModelID,fields,evidence,images,stagedAt:new Date().toISOString()};save();document.querySelector('#editorStatus').innerHTML='<span class="ok">Changes staged.</span>';renderQueue()}
function save(){localStorage.setItem('bscout-enrichment-staged',JSON.stringify(state.staged))}
function validate(){const errors=[];Object.values(state.staged).forEach(s=>{if(!s.BoatModelID)errors.push('Missing BoatModelID');if(s.fields.BoatModelID&&s.fields.BoatModelID!==s.BoatModelID)errors.push(`${s.BoatModelID}: identity changes are not allowed`);['LOA_ft','Beam_ft','Draft_ft','AirDraft_ft','Displacement_lb'].forEach(k=>{if(k in s.fields&&s.fields[k]!==''&&(!(Number.isFinite(s.fields[k]))||s.fields[k]<=0))errors.push(`${s.BoatModelID}: invalid ${k}`)});s.evidence.forEach((e,i)=>{if(!e.source)errors.push(`${s.BoatModelID}: evidence ${i+1} missing source`)})});return errors}
function exportBundle(){const errors=validate();if(errors.length){alert('Export blocked:\n'+errors.join('\n'));return}const bundle={schemaVersion:'1.0',release:'6.15',exportedAt:new Date().toISOString(),recordCount:Object.keys(state.staged).length,updates:Object.values(state.staged)};const blob=new Blob([JSON.stringify(bundle,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`bscout-enrichment-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
document.querySelector('#search').oninput=renderQueue;document.querySelector('#queueFilter').onchange=renderQueue;document.querySelector('#exportBtn').onclick=exportBundle;init().catch(e=>document.querySelector('#editor').innerHTML=`<div class="empty error">${esc(e.message)}</div>`);
})();
