"use strict";
const http=require("http"),fs=require("fs"),path=require("path"),crypto=require("crypto");
const ROOT=__dirname,DATA_DIR=path.resolve(process.env.BSCOUT_DATA_DIR||path.join(ROOT,".bscout-data")),UPLOAD_DIR=path.join(DATA_DIR,"uploads"),STATE_FILE=path.join(DATA_DIR,"community-state.json"),BACKUP_DIR=path.join(DATA_DIR,"backups"),PUBLISHED_DIR=path.join(DATA_DIR,"published");
const PORT=Number(process.env.PORT||8080),ADMIN_TOKEN=String(process.env.BSCOUT_ADMIN_TOKEN||"");
fs.mkdirSync(UPLOAD_DIR,{recursive:true});fs.mkdirSync(BACKUP_DIR,{recursive:true});fs.mkdirSync(PUBLISHED_DIR,{recursive:true});
const initial=()=>({schema:"bscout-shared-community-v1",pending:[],reviewed:[],knowledgeItems:readJson(path.join(ROOT,"data/community-knowledge-items.json"),[]),knowledgeEvidence:readJson(path.join(ROOT,"data/community-knowledge-evidence.json"),[]),updatedAt:new Date().toISOString()});
function readJson(file,fallback){try{return JSON.parse(fs.readFileSync(file,"utf8"))}catch{return fallback}}
function writeJsonAtomic(file,data){fs.mkdirSync(path.dirname(file),{recursive:true});const tmp=file+".tmp";fs.writeFileSync(tmp,JSON.stringify(data,null,2)+"\n");fs.renameSync(tmp,file)}
function mirrorJson(relative,data){writeJsonAtomic(path.join(ROOT,relative),data);writeJsonAtomic(path.join(PUBLISHED_DIR,relative),data)}
function mirrorFile(relative,source){const rootTarget=path.join(ROOT,relative),persistentTarget=path.join(PUBLISHED_DIR,relative);fs.mkdirSync(path.dirname(rootTarget),{recursive:true});fs.mkdirSync(path.dirname(persistentTarget),{recursive:true});fs.copyFileSync(source,rootTarget);fs.copyFileSync(source,persistentTarget)}
function state(){const s=readJson(STATE_FILE,null);if(s)return s;const n=initial();writeJsonAtomic(STATE_FILE,n);return n}
function saveState(s){s.updatedAt=new Date().toISOString();writeJsonAtomic(STATE_FILE,s)}
function json(res,status,obj){res.writeHead(status,{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"});res.end(JSON.stringify(obj))}
function body(req,limit=50*1024*1024){return new Promise((resolve,reject)=>{let size=0,chunks=[];req.on("data",c=>{size+=c.length;if(size>limit){reject(new Error("Request too large"));req.destroy();return}chunks.push(c)});req.on("end",()=>{try{resolve(chunks.length?JSON.parse(Buffer.concat(chunks).toString("utf8")):{} )}catch{reject(new Error("Invalid JSON"))}});req.on("error",reject)})}
function auth(req,url){if(!ADMIN_TOKEN)return false;const bearer=(req.headers.authorization||"").replace(/^Bearer\s+/i,"");return crypto.timingSafeEqual(Buffer.from((bearer||url.searchParams.get("token")||"").padEnd(ADMIN_TOKEN.length,"\0").slice(0,ADMIN_TOKEN.length)),Buffer.from(ADMIN_TOKEN))}
function backup(file){if(!fs.existsSync(file))return;const stamp=new Date().toISOString().replace(/[:.]/g,"-");fs.copyFileSync(file,path.join(BACKUP_DIR,`${path.basename(file)}.${stamp}.bak`))}
function cleanFilename(s){return String(s||"file").replace(/[^a-zA-Z0-9._-]+/g,"_").slice(0,120)}
const rate=new Map();function rateAllowed(ip){const now=Date.now(),windowMs=10*60*1000;let rows=(rate.get(ip)||[]).filter(t=>now-t<windowMs);if(rows.length>=12)return false;rows.push(now);rate.set(ip,rows);return true}
function findUpload(attachmentId){if(!fs.existsSync(UPLOAD_DIR))return null;for(const d of fs.readdirSync(UPLOAD_DIR)){const dir=path.join(UPLOAD_DIR,d);if(!fs.statSync(dir).isDirectory())continue;for(const f of fs.readdirSync(dir))if(f.startsWith(cleanFilename(attachmentId)+"__"))return path.join(dir,f)}return null}
function publishReviewedContributions(s){const outDir=path.join(ROOT,"community-assets");fs.mkdirSync(outDir,{recursive:true});const allowedRights=new Set(["creator_or_owner","permission_granted","public_distribution"]);const rows=(s.reviewed||[]).filter(r=>r.ModerationStatus==="approved").map(r=>{const pub={...r,ContactEmail:null,ModeratorNotes:null};const urls=[];for(const ref of r.AttachmentRefs||[]){if(!allowedRights.has(r.RightsStatus))continue;const src=findUpload(ref);if(!src)continue;const original=path.basename(src).split("__").slice(1).join("__")||ref;const filename=`${cleanFilename(ref)}__${cleanFilename(original)}`;mirrorFile(`community-assets/${filename}`,src);urls.push(`community-assets/${filename}`)}pub.PublishedAttachmentURLs=urls;return pub});const file=path.join(ROOT,"data/community-reviewed-contributions.json");backup(file);mirrorJson("data/community-reviewed-contributions.json",rows);return rows.length}
function applyCanonicalCorrections(s){const map={YearStart:"FirstYear",YearEnd:"LastYear",LengthFt:"LOA_ft",BeamFt:"Beam_ft",DraftFt:"Draft_ft",DisplacementLb:"Displacement_lb",FuelCapacityGal:"FuelCapacity",WaterCapacityGal:"WaterCapacity",NormalizedHullType:"NormalizedHullType",NormalizedFuel:"NormalizedFuel",NormalizedPropulsion:"NormalizedPropulsion",BoatFamily:"BoatFamily",ModelCharacter:"ModelCharacter"};const corrections=(s.reviewed||[]).filter(r=>r.ModerationStatus==="approved"&&r.ReviewAction==="corrected"&&r.ContributionType==="correction"&&!r.CanonicalPublishedAt);if(!corrections.length)return 0;const file=path.join(ROOT,"boatmodels.json"),rows=readJson(file,[]);let changed=0;for(const r of corrections){const src=r.Payload?.CorrectionField,target=map[src];if(!target||src==="Other")continue;const model=rows.find(x=>String(x.BoatModelID)===String(r.ModelID));if(!model)continue;let value=r.Payload?.ProposedValue;if(["FirstYear","LastYear"].includes(target)){const n=parseInt(value,10);if(!Number.isFinite(n))continue;value=n}else if(["LOA_ft","Beam_ft","Draft_ft","Displacement_lb","FuelCapacity","WaterCapacity"].includes(target)){const n=Number(String(value).replace(/[^0-9.+-]/g,""));if(!Number.isFinite(n))continue;value=n}model[target]=value;model.LastUpdated=new Date().toISOString().slice(0,10);model.Revision=Number(model.Revision||0)+1;model.ReviewedBy="B-Scout Community Moderation";r.CanonicalPublishedAt=new Date().toISOString();r.CanonicalActionRef=`boatmodels.json:${r.ModelID}:${target}`;changed++}if(changed){backup(file);mirrorJson("boatmodels.json",rows);saveState(s)}return changed}
function publishCommunity(s){const ki=path.join(ROOT,"data/community-knowledge-items.json"),ke=path.join(ROOT,"data/community-knowledge-evidence.json");backup(ki);backup(ke);mirrorJson("data/community-knowledge-items.json",s.knowledgeItems||[]);mirrorJson("data/community-knowledge-evidence.json",s.knowledgeEvidence||[]);const reviewedContributions=publishReviewedContributions(s);const canonicalCorrections=applyCanonicalCorrections(s);return {knowledgeItems:(s.knowledgeItems||[]).length,knowledgeEvidence:(s.knowledgeEvidence||[]).length,reviewedContributions,canonicalCorrections}}
function uniqueCode(name,existing){let base=String(name||"").toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,4).padEnd(4,"X"),code=base,n=1;while(existing.has(code)){code=(base.slice(0,3)+String(n%10));n++}return code}
function promoteCanonical(row){if(!row?.CanonicalDraft)throw new Error("No moderator canonical draft supplied");const f=row.CanonicalDraft.Fields||{},extra=Object.fromEntries((row.CanonicalDraft.AdditionalFields||[]).filter(x=>x.Key).map(x=>[x.Key,x.Value]));
 if(row.ContributionType==="new_manufacturer"){
  const file=path.join(ROOT,"data/registry/manufacturers.json"),rows=readJson(file,[]),name=String(f.CanonicalName||"").trim();if(!name)throw new Error("Canonical manufacturer name is required");if(rows.some(x=>String(x.CanonicalName||"").toLowerCase()===name.toLowerCase()))throw new Error("Manufacturer already exists");const codes=new Set(rows.map(x=>x.ManufacturerCode));const code=String(f.ManufacturerCode||"").trim().toUpperCase()||uniqueCode(name,codes);const rec={ManufacturerCode:code,CanonicalName:name,LegacyManufacturerIDs:[],Aliases:String(f.Aliases||"").split(",").map(x=>x.trim()).filter(Boolean),Status:f.Status||"Unknown",CodeStatus:"CommunityReviewed",BoatRecordCount:0,Country:f.Country||null,YearStart:f.YearStart?Number(f.YearStart):null,YearEnd:f.YearEnd?Number(f.YearEnd):null,Website:f.Website||null,ResearchNotes:row.CanonicalDraft.ResearchNotes||null,...extra};backup(file);rows.push(rec);rows.sort((a,b)=>String(a.CanonicalName).localeCompare(String(b.CanonicalName)));mirrorJson("data/registry/manufacturers.json",rows);return {type:"manufacturer",id:code,record:rec};
 }
 if(row.ContributionType==="new_model"){
  const file=path.join(ROOT,"boatmodels.json"),rows=readJson(file,[]),manufacturer=String(f.Manufacturer||"").trim(),model=String(f.Model||"").trim();if(!manufacturer||!model)throw new Error("Manufacturer and model are required");if(rows.some(x=>String(x.Manufacturer||"").toLowerCase()===manufacturer.toLowerCase()&&String(x.Model||"").toLowerCase()===model.toLowerCase()&&String(x.Variant||"").toLowerCase()===String(f.Variant||"").toLowerCase()))throw new Error("Model already exists");const mfr=readJson(path.join(ROOT,"data/registry/manufacturers.json"),[]).find(x=>String(x.CanonicalName||"").toLowerCase()===manufacturer.toLowerCase());const code=String(f.ManufacturerCode||mfr?.ManufacturerCode||uniqueCode(manufacturer,new Set(rows.map(x=>String(x.BoatModelID||"").split("-")[0])))).toUpperCase();let slug=String(model).toUpperCase().replace(/[^A-Z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,18),id=`${code}-${slug}`;let i=2;while(rows.some(x=>x.BoatModelID===id))id=`${code}-${slug}-${i++}`;const existingMfrModel=rows.find(x=>String(x.Manufacturer||"").toLowerCase()===manufacturer.toLowerCase());const rec={ManufacturerID:existingMfrModel?.ManufacturerID||code,Manufacturer:manufacturer,Model:model,Variant:f.Variant||null,Nickname:[manufacturer,model,f.Variant].filter(Boolean).join(" "),ImageURL:"images/boat-placeholder.svg",Active:true,FirstYear:f.YearStart?Number(f.YearStart):null,LastYear:f.YearEnd?Number(f.YearEnd):null,LOA_ft:f.LengthFt?Number(f.LengthFt):null,Beam_ft:f.BeamFt?Number(f.BeamFt):null,Draft_ft:f.DraftFt?Number(f.DraftFt):null,Displacement_lb:f.DisplacementLb?Number(f.DisplacementLb):null,BoatFamily:f.BoatFamily||null,Fuel:f.Fuel||null,NormalizedFuel:f.Fuel||null,Propulsion:f.Propulsion||null,NormalizedPropulsion:f.Propulsion||null,HullBehaviour:f.HullBehaviour||null,EngineConfiguration:f.EngineConfiguration||null,Designer:f.Designer||null,Construction:f.Construction||null,BoatModelID:id,DateCreated:new Date().toISOString().slice(0,10),LastUpdated:new Date().toISOString().slice(0,10),ReviewedBy:"B-Scout Community Moderation",Revision:1,CommunitySourceURL:f.SourceURL||null,ResearchNotes:row.CanonicalDraft.ResearchNotes||null,...extra};backup(file);rows.push(rec);mirrorJson("boatmodels.json",rows);return {type:"model",id,record:rec};
 }
 throw new Error("Contribution is not a promotable manufacturer/model");
}
function serveStatic(req,res,url){let rel=decodeURIComponent(url.pathname==="/"?"/index.html":url.pathname);if(rel.includes("..")||rel.startsWith("/.bscout-data")||rel==="/server.js"){res.writeHead(404);res.end();return}let file=path.join(ROOT,rel);const persistent=path.join(PUBLISHED_DIR,rel);if(persistent.startsWith(PUBLISHED_DIR)&&fs.existsSync(persistent)&&fs.statSync(persistent).isFile())file=persistent;if(!file.startsWith(ROOT)&&!file.startsWith(PUBLISHED_DIR)){res.writeHead(404);res.end();return}if(!fs.existsSync(file)||fs.statSync(file).isDirectory()){res.writeHead(404);res.end("Not found");return}const ext=path.extname(file).toLowerCase(),types={".html":"text/html; charset=utf-8",".js":"application/javascript; charset=utf-8",".css":"text/css; charset=utf-8",".json":"application/json; charset=utf-8",".svg":"image/svg+xml",".jpg":"image/jpeg",".jpeg":"image/jpeg",".png":"image/png",".webp":"image/webp",".pdf":"application/pdf"};res.writeHead(200,{"Content-Type":types[ext]||"application/octet-stream"});fs.createReadStream(file).pipe(res)}
const server=http.createServer(async(req,res)=>{const url=new URL(req.url,"http://localhost");try{
 if(url.pathname==="/api/health")return json(res,200,{shared:true,version:"1.0",adminConfigured:!!ADMIN_TOKEN});
 if(url.pathname==="/api/contributions"&&req.method==="POST"){const ip=req.socket.remoteAddress||"unknown";if(!rateAllowed(ip))return json(res,429,{error:"Too many submissions. Try again later."});const p=await body(req),r=p.record;if(!r?.ContributionID||!r.ContributionType)return json(res,400,{error:"Invalid contribution record"});const s=state();if([...s.pending,...s.reviewed].some(x=>x.ContributionID===r.ContributionID))return json(res,200,{ok:true,id:r.ContributionID,duplicate:true});for(const a of p.attachments||[]){if(!a?.attachmentRef||!a?.dataBase64)continue;const buf=Buffer.from(a.dataBase64,"base64");if(buf.length>26*1024*1024)throw new Error("Attachment too large");const dir=path.join(UPLOAD_DIR,r.ContributionID);fs.mkdirSync(dir,{recursive:true});const file=path.join(dir,`${cleanFilename(a.attachmentRef)}__${cleanFilename(a.filename)}`);fs.writeFileSync(file,buf)}s.pending.push({...r,ModerationStatus:"pending",SharedReceivedAt:new Date().toISOString()});saveState(s);return json(res,201,{ok:true,id:r.ContributionID,pending:s.pending.length})}
 if(url.pathname.startsWith("/api/admin/")){if(!auth(req,url))return json(res,401,{error:"Moderator authentication required"});
  if(url.pathname==="/api/admin/snapshot"&&req.method==="GET")return json(res,200,state());
  if(url.pathname==="/api/admin/snapshot"&&req.method==="PUT"){const p=await body(req),s=state();for(const k of ["pending","reviewed","knowledgeItems","knowledgeEvidence"])if(Array.isArray(p[k]))s[k]=p[k];saveState(s);return json(res,200,{ok:true,updatedAt:s.updatedAt})}
  if(url.pathname==="/api/admin/publish"&&req.method==="POST"){const s=state();const result=publishCommunity(s);return json(res,200,{ok:true,...result})}
  if(url.pathname==="/api/admin/promote"&&req.method==="POST"){const p=await body(req),result=promoteCanonical(p.contribution);return json(res,200,{ok:true,...result})}
  if(url.pathname.startsWith("/api/admin/attachments/")&&req.method==="GET"){const id=decodeURIComponent(url.pathname.split("/").pop()),dirs=fs.existsSync(UPLOAD_DIR)?fs.readdirSync(UPLOAD_DIR):[];for(const d of dirs){const dir=path.join(UPLOAD_DIR,d);for(const f of fs.readdirSync(dir)){if(f.startsWith(cleanFilename(id)+"__")){const file=path.join(dir,f),name=f.split("__").slice(1).join("__");res.writeHead(200,{"Content-Type":"application/octet-stream","Content-Disposition":`inline; filename="${name.replace(/\"/g,"")}"`});return fs.createReadStream(file).pipe(res)}}}return json(res,404,{error:"Attachment not found"})}
 }
 return serveStatic(req,res,url)
 }catch(e){console.error(e);if(!res.headersSent)json(res,500,{error:e.message||"Server error"});else res.end()}});
server.listen(PORT,()=>console.log(`B-Scout shared server: http://127.0.0.1:${PORT} (admin ${ADMIN_TOKEN?"configured":"NOT configured"})`));
