import json, os
from copy import deepcopy
root=os.path.abspath(os.path.join(os.path.dirname(__file__),'..'))
model_file=os.path.join(root,'boatmodels.json')
models=json.load(open(model_file,encoding='utf-8'))
today='2026-08-07'
families=['DeFever','Island Gypsy','Kadey-Krogen','Willard','Monk','North Pacific','Helmsman','Great Harbour','Prairie','SeaPiper']
S={
'DeFever':['https://www.hmy.com/yachting/powerboat-guide/defever','https://www.defevercruisers.com/'],
'Island Gypsy':['https://www.hmy.com/yachting/powerboat-guide/island-gypsy'],
'Kadey-Krogen':['https://www.kadeykrogen.com/our-history/','https://www.kadeykrogen.com/'],
'Willard':['https://willardboats.org/about','https://willardboats.org/boats/vega30','https://willardboats.org/boats/vega36','https://willardboats.org/boats/vega40'],
'Monk':['https://www.hmy.com/yachting/powerboat-guide/monk/36-trawler-1982-2007'],
'North Pacific':['https://northpacificyachts.com/news/'],
'Helmsman':['https://helmsmantrawlers.com/','https://helmsmantrawlers.com/about-helmsman-trawlers/'],
'Great Harbour':['https://www.greatharbourtrawlers.com/gh37.html','https://www.greatharbourtrawlers.com/n37.html'],
'Prairie':['https://www.hmy.com/yachting/powerboat-guide/atlantic/37-double-cabin-1982-92'],
'SeaPiper':['https://www.seapiper.com/wp-content/uploads/2018/03/SeaPiper-35-Specification-09-Mar-2018-1.pdf']
}

def suit(m, exposure='coastal'):
    beam=m.get('Beam_ft') or 99
    inland='Good' if beam<=14 else 'Mixed'
    exposed='Good' if exposure=='passage' else ('Mixed' if exposure=='coastal' else 'Limited')
    return {
      'CoupleCruising':{'Assessment':'Good','Summary':'The documented layout and cruising systems are well suited to a cruising couple, with guest capacity varying by model.'},
      'SoloHandling':{'Assessment':'Mixed','Summary':'Protected helms and deck access can support short-handed operation, but displacement, windage, engine arrangement and docking equipment vary materially by model.'},
      'InlandWaterways':{'Assessment':inland,'Summary':'Route suitability depends on beam, draft and actual air draft; larger models may face marina and lock constraints.'},
      'ExposedWater':{'Assessment':exposed,'Summary':'Hull form and construction support the documented cruising role, but condition, loading, weather and individual configuration remain decisive.'}
    }

def evidence(m,sources,unresolved,status='Reviewed'):
    ap={'Scope':'Model','Models':[m['BoatModelID']],'Years':{'From':m.get('FirstYear'),'To':m.get('LastYear')},'Variations':[]}
    quality='Moderate' if status=='Reviewed' else 'Low'
    coverage='Strong' if status=='Reviewed' else 'Partial'
    m['EvidenceSummary']={'KnowledgeCoverage':coverage,'EvidenceQuality':quality,'Statements':[
      {'Scope':'IdentityAndDimensions','AppliesTo':deepcopy(ap),'EvidenceRefs':sources,'EvidenceTypes':['Factory documented','Technical or survey source'],'Confidence':'High' if status=='Reviewed' else 'Moderate','Notes':'Representative identity and specifications are based on manufacturer, owner-association or model-specific technical references; hull-specific differences remain explicit.'},
      {'Scope':'OverviewAndSuitability','AppliesTo':deepcopy(ap),'EvidenceRefs':sources,'EvidenceTypes':['Factory documented','Technical or survey source'],'Confidence':'Moderate','Notes':'Buyer guidance is derived from documented configuration, dimensions, propulsion and intended use rather than sales language.'},
      {'Scope':'InspectionFocus','AppliesTo':dict(ap,Scope='Model family'),'EvidenceRefs':sources,'EvidenceTypes':['Technical or survey source'],'Confidence':'Moderate','Notes':'Inspection guidance identifies systems and age/configuration risks to inspect; it is not an assertion that every hull has a defect.'}
    ],'UnresolvedInformation':unresolved+['Legacy CommonProblems were not promoted to KnownConcerns without model-specific evidence meeting the approved threshold.']}
    m['ResearchStatus']=status;m['DataConfidence']='Moderate' if status=='Reviewed' else 'Low';m['ReviewedBy']='B-Atlas Phase 8C-10 Traditional Trawler Family Research';m['LastUpdated']=today;m['Revision']=(m.get('Revision') or 1)+1

def q(items): return ['What inspection, repair or service history is available for '+x[0].lower()+x[1:]+'?' for x in items]

def generic(m, desc, strengths, tradeoffs, best, avoid, insp, variations, sources=None, unresolved=None, exposure='coastal',status='Reviewed'):
    m['Overview']=desc;m['Suitability']=suit(m,exposure);m['Strengths']=strengths;m['TradeOffs']=tradeoffs;m['BestFor']=best;m['AvoidIf']=avoid;m['KnownConcerns']=[];m['InspectionFocus']=insp;m['BuyerQuestions']=q(insp);m['OwnerActions']=['Keep deck, window and hardware penetrations sealed and investigate leaks promptly','Service propulsion, cooling, exhaust, steering and fuel systems to documented intervals','Document structural, tank, electrical and machinery repairs for future buyers'];m['ModelVariations']=variations;evidence(m,sources or S[m['Manufacturer']],unresolved or [],status)
    note=f"Phase 8C-10 traditional-trawler family normalization {today}. Unsupported defects remain unknown."
    m['ResearchNotes']='\n\n'.join(x for x in [note,(m.get('ResearchNotes') or '').strip()] if x)

# DeFever corrections and normalization
for m in [x for x in models if x.get('Manufacturer')=='DeFever']:
    i=m['BoatModelID'];src=list(S['DeFever']);status='Reviewed';un=[]
    m['Fuel']='Diesel';m['NormalizedFuel']='Diesel';m['Propulsion']='Shaft';m['NormalizedPropulsion']='Shaft';m['Flybridge']='Yes'
    if i=='DEFE-34-TR':
        m.update(Model='34 Passagemaker',FirstYear=1974,LastYear=1976,LOA_ft=34.33,Beam_ft=12.25,Draft_ft=3.33,Displacement_lb=21000,FuelCapacity=380,WaterCapacity=100,EngineCount=1,EngineConfiguration='Single 120 hp Ford Lehman diesel');src+=['https://www.hmy.com/yachting/powerboat-guide/defever/34-passagemaker-1974-76']; exposure='passage'
    elif i=='DEFE-38-TR':
        m['Model']='38 Trawler'; status='Initial'; exposure='passage';un=['B-Atlas retains a DeFever 38 record, but the current research set does not establish a standardized production-model identity comparable with the cataloged DeFever series. Verify builder, year and hull documentation before treating marketplace listings as the same model.']
    elif i=='DEFE-40-EURO':
        m.update(Model='40 Offshore Cruiser',Variant=None,FirstYear=1984,LastYear=1991); exposure='coastal'
    elif i=='DEFE-41':
        m.update(Model='41 Trawler',FirstYear=1980,LastYear=1995,LOA_ft=40.58,Beam_ft=14.17,Draft_ft=4.0,Displacement_lb=23000,FuelCapacity=400,WaterCapacity=250,HoldingCapacity=40,EngineConfiguration='Single Cummins or twin Ford Lehman diesels',EngineCount=None);src+=['https://www.hmy.com/yachting/powerboat-guide/defever/41-trawler-1980-95'];exposure='coastal'
    elif i=='DEFE-43':
        m.update(Model='43 Trawler',FirstYear=1978,LastYear=1981,LOA_ft=42.17,Beam_ft=14.0,Draft_ft=4.42,Displacement_lb=40836,FuelCapacity=1072,WaterCapacity=500,HoldingCapacity=50,EngineCount=2,EngineConfiguration='Twin 120 hp Ford Lehman diesels');src+=['https://www.hmy.com/yachting/powerboat-guide/defever/43-trawler-1978-81'];exposure='passage'
    elif i=='DEFE-45':
        m.update(Model='45 Pilothouse',FirstYear=2002,LastYear=2008);exposure='passage'
    elif i=='DEFE-47':
        m.update(Model='47 POC Motor Yacht',FirstYear=1986,LastYear=1992,LOA_ft=46.83,Beam_ft=16.0,Draft_ft=4.67,Displacement_lb=43200,FuelCapacity=600,WaterCapacity=275,HoldingCapacity=50,EngineCount=2);src+=['https://www.hmy.com/yachting/powerboat-guide/defever/47-poc-motor-yacht-1986-92'];exposure='coastal'
    else:
        m.update(Model='49 Cockpit Motor Yacht',FirstYear=1994,LastYear=2006,LOA_ft=48.83,Beam_ft=15.0,Draft_ft=4.58,Displacement_lb=54000,FuelCapacity=1100,WaterCapacity=370,HoldingCapacity=90,EngineCount=2);src+=['https://www.hmy.com/yachting/powerboat-guide/defever/49-cockpit-motor-yacht-1994-2006'];exposure='passage'
    desc=f"The DeFever {m['Model']} is an Arthur DeFever cruising design emphasizing substantial displacement, protected running gear and practical accommodations for extended motoring. Its exact hull form and layout vary by model, but the family favors economical passage speeds, robust deck arrangements and machinery intended for long cruising rather than marina-focused performance."
    generic(m,desc,['Protected running gear and conservative cruising hull design','Layouts emphasize extended cruising, storage and workable deck access','Strong recognition among traditional long-range trawler buyers'],['Large displacement, tankage and systems increase haul-out and ownership cost','Older examples can carry extensive exterior teak and aging tanks/systems','Cruising performance favors efficiency and range over speed'],['Couples planning extended coastal or passagemaking use','Owners who value traditional machinery access and protected running gear','Buyers comfortable maintaining older heavy cruising yachts'],['You require high planing speeds','You need trailerability or compact marina dimensions','You want minimal exterior and systems maintenance'],['Verify exact DeFever model identity, builder and production year from hull documentation','Inspect decks, windows, rail bases and exterior teak for moisture intrusion and prior repairs','Inspect fuel and water tanks, plumbing, exhaust and engine-room ventilation','Inspect shafts, cutlass bearings, rudders, keel and running-gear protection','Review electrical upgrades and generator/charging systems on older examples'],[{'Name':'Builder and configuration variation','Description':'DeFever designs were produced by different yards and in multiple propulsion/layout configurations; individual hull documentation controls builder, engine package and arrangement.','AffectedYears':'Varies by model','EvidenceRefs':src,'Confidence':'Moderate'}],src,un,exposure,status)

# Island Gypsy
for m in [x for x in models if x.get('Manufacturer')=='Island Gypsy']:
    i=m['BoatModelID'];src=list(S['Island Gypsy']);status='Reviewed';un=[];m['Fuel']='Diesel';m['NormalizedFuel']='Diesel';m['Propulsion']='Shaft';m['NormalizedPropulsion']='Shaft';m['Flybridge']='Yes';exposure='coastal'
    if i=='ISGY-32-SE' or i=='ISGY-32':
        m.update(Model='32 Sedan',FirstYear=1981,LastYear=2000,LOA_ft=32.0,Beam_ft=12.0,Draft_ft=3.67,Displacement_lb=16400,FuelCapacity=250,WaterCapacity=120,HoldingCapacity=15,EngineCount=1,EngineConfiguration='Single diesel; later higher-output Cummins installations');src+=['https://www.hmy.com/yachting/powerboat-guide/island-gypsy/32-sedan-1981-2000']
        if i=='ISGY-32': un=['This record overlaps the explicit ISGY-32-SE Sedan record. It is retained for compatibility pending a controlled duplicate-ID consolidation.'];status='Initial'
    elif i=='ISGY-32-EU':
        m.update(Model='32 Europa',FirstYear=1989,LastYear=2003,LOA_ft=32.0,Beam_ft=12.0,Draft_ft=3.67,Displacement_lb=16400,FuelCapacity=250,WaterCapacity=120,HoldingCapacity=15,EngineCount=1);src+=['https://www.hmy.com/yachting/powerboat-guide/island-gypsy/32-europa-1989-2003']
    elif i=='ISGY-32-FI':
        m.update(Model='32 Fisherman',FirstYear=1982,LastYear=1997,LOA_ft=32.08,Beam_ft=12.0,Draft_ft=3.67,Displacement_lb=13000,FuelCapacity=250,WaterCapacity=120,EngineCount=None);src+=['https://www.hmy.com/yachting/powerboat-guide/island-gypsy/32-fisherman-1982-97']
    elif i=='ISGY-36EURO': m.update(Model='36 Europa',FirstYear=1980,LastYear=1998)
    elif i=='ISGY-36':
        m.update(Model='36 Classic',FirstYear=1978,LastYear=2001,LOA_ft=36.0,Beam_ft=13.0,Draft_ft=3.5,Displacement_lb=27000,FuelCapacity=400,WaterCapacity=200,HoldingCapacity=50,EngineCount=None);src+=['https://www.hmy.com/yachting/powerboat-guide/island-gypsy/36-classic-1978-2001']
    elif i=='ISGY-40':
        m.update(Model='40 Classic',FirstYear=1995,LastYear=1998,LOA_ft=40.0,Beam_ft=14.25,Draft_ft=3.5,Displacement_lb=34000,FuelCapacity=400,WaterCapacity=200,EngineCount=2);src+=['https://www.hmy.com/yachting/powerboat-guide/island-gypsy/40-classic-1995-98']
    elif i=='ISGY-44':
        m.update(Model='44 Motor Cruiser',FirstYear=1980,LastYear=1996,LOA_ft=44.25,Beam_ft=15.33,Draft_ft=4.25,Displacement_lb=38500,FuelCapacity=720,WaterCapacity=320,HoldingCapacity=60,EngineCount=2);src+=['https://www.hmy.com/yachting/powerboat-guide/island-gypsy/44-motor-cruiser-1980-96']
    elif i=='ISGY-50':
        status='Initial';un=['The current B-Atlas 50-foot Island Gypsy record does not map cleanly to the principal documented historical model catalog, which includes several 49-foot variants. Verify exact model designation and hull documentation before renaming or consolidating.']
    desc=f"The Island Gypsy {m['Model']} is a traditional fiberglass cruising boat from the Halvorsen-associated Island Gypsy line. Depending on model it ranges from compact sedan/Europa layouts to larger motor cruisers, generally combining teak-rich interiors, semi-displacement hulls, protected shafting and flybridge/lower-helm cruising arrangements."
    generic(m,desc,['Traditional teak interior and practical cruising layout','Protected shaft-drive running gear and economical low-to-moderate-speed operation','Good side-deck and helm access on documented sedan/Europa models'],['Exterior teak can create substantial maintenance burden','Older tanks, windows and deck structures require condition-specific inspection','Performance and engine count vary significantly across versions'],['Couples wanting traditional trawler character and warm interiors','Coastal and inland cruisers comfortable with older-boat maintenance','Buyers who value flybridge and lower-helm flexibility'],['You want low-maintenance exterior finishes','You require high-speed planing performance','You need modern systems with minimal refit exposure'],['Confirm exact Island Gypsy model/variant and engine configuration from build records','Moisture-test teak decks, window surrounds, rail bases and cabin-top penetrations','Inspect fuel/water/waste tanks and hoses, particularly original installations','Inspect engine cooling, exhaust, shaft, rudder and keel/running gear','Review electrical, charging and generator upgrades and workmanship'],[{'Name':'Layout and engine variation','Description':'Island Gypsy models were offered in Sedan, Europa, Fisherman, Classic and motor-cruiser configurations with materially different layouts and engine packages.','AffectedYears':'Varies by model','EvidenceRefs':src,'Confidence':'Moderate'}],src,un,exposure,status)

# Kadey-Krogen
for m in [x for x in models if x.get('Manufacturer')=='Kadey-Krogen']:
    i=m['BoatModelID'];src=list(S['Kadey-Krogen']);m['Fuel']='Diesel';m['NormalizedFuel']='Diesel';exposure='passage';un=[]
    if i=='KDKR-38-CT':
        m['Model']='38 Cutter';m['Propulsion']='Sail + Shaft';m['NormalizedPropulsion']='Shaft';m['EngineCount']=1;exposure='passage'
    else:
        m['Propulsion']='Shaft';m['NormalizedPropulsion']='Shaft';m['EngineCount']=1
    if i=='KDKR-36-MA': m.update(Model='36 Manatee',FirstYear=1984,LastYear=1992)
    if i=='KDKR-39': m.update(Model='39',FirstYear=1997,LastYear=2013)
    if i=='KDKR-42': m.update(Model='42',FirstYear=1977,LastYear=1998)
    if i=='KDKR-44': m.update(Model='44',FirstYear=2004,LastYear=2016)
    if i=='KDKR-48-NS': m.update(Model='48 North Sea',FirstYear=1995,LastYear=2007)
    desc=f"The Kadey-Krogen {m['Model']} is a purpose-built cruising design from a builder focused on displacement-speed efficiency and long-range use. The family emphasizes substantial tankage, protected single-screw propulsion and liveaboard-oriented interiors; the 38 Cutter is the major exception, combining shoal-draft sailing capability with auxiliary diesel power."
    generic(m,desc,['Purpose-built long-range cruising design with efficient displacement operation','Protected running gear and substantial tankage on power models','Strong builder/owner knowledge base and liveaboard-oriented layouts'],['Low-speed cruising requires patience and weather planning','Large tankage and systems increase refit and maintenance scope','Beam and displacement of larger models materially affect marina and haul-out options'],['Couples planning extended liveaboard and long-distance cruising','Owners prioritizing range, efficiency and protected machinery','Buyers comfortable with displacement-speed passage planning'],['You require sustained planing speeds','You need trailerable or narrow-beam dimensions','You want very simple weekend-cruiser systems'],['Verify model generation, build year and engine installation from factory documentation','Inspect cored decks, windows, hatches and hardware penetrations for moisture','Inspect tanks, fuel transfer/filtration, exhaust and cooling systems','Inspect shaft, rudder, stern gear and keel protection','Review electrical, charging, generator and navigation-system refits'],[{'Name':'Model-specific layouts and generations','Description':'Kadey-Krogen models evolved through multiple layouts and equipment packages; the 38 Cutter is a distinct sailing/motorsailing design rather than a conventional Krogen trawler.','AffectedYears':'Varies by model','EvidenceRefs':src,'Confidence':'High'}],src,un,exposure,'Reviewed')

# Willard
for m in [x for x in models if x.get('Manufacturer')=='Willard']:
    i=m['BoatModelID'];src=list(S['Willard']);m['Fuel']='Diesel';m['NormalizedFuel']='Diesel';m['EngineCount']=1;m['Propulsion']='Shaft';m['NormalizedPropulsion']='Shaft';un=[]
    if i=='WILL-30-VE': m.update(Model='30 Vega Horizon',Variant='Motorsailer',FirstYear=1972,LastYear=1975)
    elif i=='WILL-30-VO': m.update(Model='30 Vega Voyager',Variant='Raised Pilothouse',FirstYear=1972,LastYear=1975)
    elif i=='WILL-36-TR': m.update(Model='36 Vega',Variant='Family',FirstYear=1961,LastYear=1970,LOA_ft=36);un=['The Vega 36 family included Standard Cruiser, Aft Pilothouse and motorsailer versions; individual hull configuration must be identified rather than inferred from length alone.']
    else: m.update(Model='40 Vega Nomad',Variant='Widebody Flybridge Sedan',FirstYear=1973,LastYear=1977);un=['The Vega 40 family also included Voyager pilothouse and motorsailer versions. This record represents the Nomad/widebody flybridge form.']
    desc=f"The Willard {m['Model']} belongs to Willard Marine’s early production-fiberglass cruising lineage. These heavy, economical boats use displacement hulls and simple diesel propulsion, with the Vega families offered in materially different sedan, pilothouse and motorsailer configurations."
    generic(m,desc,['Heavy displacement fiberglass construction with protected running gear','Simple low-speed diesel propulsion and strong owner-association documentation','Compact models provide unusual cruising utility for their length'],['Very low cruising speeds compared with semi-displacement alternatives','Many examples are now restoration-age boats with decades of owner modifications','Interior and deck configuration varies substantially by Vega version'],['Owners who value simplicity, efficiency and traditional displacement behavior','Restoration-minded buyers seeking historically significant fiberglass trawlers','Slow coastal and inland cruising where speed is secondary'],['You require fast cruise speeds','You want turnkey modern systems without refit exposure','You cannot accommodate model-specific restoration or customization'],['Confirm exact Vega model/version and hull number from documentation','Inspect deck/superstructure cores or fiberglass-over-plywood areas appropriate to production period','Inspect tanks, wiring, exhaust, cooling and original plumbing for age-related deterioration','Inspect shaft, rudder, keel and steering systems','Review structural and systems modifications made over the boat’s long service life'],[{'Name':'Vega configuration families','Description':'Willard used the same hull families for distinct Nomad, Voyager, Horizon, Searcher and other configurations. “Vega” identifies a hull family rather than one universal layout.','AffectedYears':'1961–1977 primary Vega era','EvidenceRefs':src,'Confidence':'High'}],src,un,'coastal','Reviewed')

# Monk 36
for m in [x for x in models if x.get('Manufacturer')=='Monk']:
    src=S['Monk'];m.update(Model='36 Trawler',FirstYear=1982,LastYear=2007,LOA_ft=36.0,Beam_ft=13.0,Draft_ft=4.0,Displacement_lb=18000,FuelCapacity=320,WaterCapacity=120,HoldingCapacity=45,EngineCount=1,Fuel='Diesel',NormalizedFuel='Diesel',Propulsion='Shaft',NormalizedPropulsion='Shaft',Flybridge='Yes')
    generic(m,'The Monk 36 Trawler is an aft-cabin semi-displacement cruiser designed by Ed Monk Jr. and produced first in Taiwan and later in Nova Scotia. Its enduring layout combines a single diesel, protected propeller, two-stateroom accommodation, galley-up salon and flybridge/lower-helm operation in a manageable 36-foot package.',['Long production run and established owner knowledge base','Single-diesel economy with protected running gear','Two-stateroom layout and wide side decks in a moderate-size hull'],['Early boats carry more exterior teak and associated upkeep','Production-location and interior details changed after the early 1990s','Single-screw handling benefits from thruster assistance in difficult conditions'],['Couples seeking a traditional 36-foot aft-cabin trawler','Great Loop and extended coastal cruisers prioritizing economy','Owners comfortable maintaining an older single-diesel boat'],['You require high cruise speeds','You want a single-level sedan layout without aft-cabin steps','You want minimal exterior-teak or refit exposure'],['Confirm Taiwan versus Nova Scotia production and model year','Moisture-test decks, windows, rail bases and exterior teak penetrations','Inspect fuel/water/waste tanks, hoses and sanitation systems','Inspect engine cooling, exhaust, shaft, rudder, skeg and steering','Review electrical and generator upgrades'],[{'Name':'Production-location evolution','Description':'Production moved from Taiwan to Nova Scotia after 1992, with reduced exterior teak and interior changes including aft-head and master-berth revisions.','AffectedYears':'1982–2007','EvidenceRefs':src,'Confidence':'High'}],src,[],'coastal','Reviewed')

# North Pacific
for m in [x for x in models if x.get('Manufacturer')=='North Pacific']:
    src=S['North Pacific'];m['Fuel']='Diesel';m['NormalizedFuel']='Diesel';m['Propulsion']='Shaft';m['NormalizedPropulsion']='Shaft';m['EngineCount']=1;m['Flybridge']='Yes'
    if m['BoatModelID']=='NPAC-28': m.update(Model='28 Pilothouse',FirstYear=2009,LastYear=2012,LOA_ft=31.0,Beam_ft=8.5,EngineConfiguration='Single 130 hp Cummins QSD diesel');un=['Published overall-length conventions vary because the 28-foot design includes swim platform and bow appendages.']
    else: m.update(Model='38 Sedan',FirstYear=2012,LastYear=2015,LOA_ft=41.5,Beam_ft=12.75,Draft_ft=4.0,Displacement_lb=24000,FuelCapacity=350,WaterCapacity=200,EngineConfiguration='Single 250 hp Cummins QSB 6.7 diesel');un=[]
    generic(m,f"The North Pacific {m['Model']} is a China-built cruising trawler developed around practical owner operation, low-maintenance exterior surfaces and warm wood interiors. The 28 is a compact pilothouse design aimed at trailerable-style cruising, while the 38 Sedan is a substantially larger Europa-style long-range coastal cruiser.",['Practical machinery access and owner-oriented systems','Single-diesel economy with enclosed lower-helm protection','Low-maintenance exterior compared with teak-heavy traditional trawlers'],['Limited production makes brokerage availability uneven','Single-engine propulsion provides no second-engine redundancy','The 38 requires conventional yacht-scale marina and haul-out infrastructure'],['Couples wanting practical pilothouse or sedan cruising','Owners prioritizing economy, systems access and low exterior maintenance','Protected-water and coastal cruisers who value single-diesel simplicity'],['You require twin-engine propulsion redundancy','You want high-speed planing performance','You need broad dealer-network support for a high-volume production brand'],['Verify exact hull year and factory equipment list','Inspect windows, deck hardware and cored structures for leakage','Inspect single-diesel cooling, exhaust, shaft, rudder and fuel systems','Review thruster, inverter/charger, heating and electrical installations','Confirm tank capacities and weight from hull-specific documentation'],[{'Name':'28 versus 38 mission difference','Description':'The NP28 is a compact pilothouse pocket trawler; the NP38 Sedan is a larger Europa-style cruiser with substantially greater displacement and tankage.','AffectedYears':'Model-specific','EvidenceRefs':src,'Confidence':'High'}],src,un,'coastal','Reviewed')

# Helmsman
for m in [x for x in models if x.get('Manufacturer')=='Helmsman']:
    src=S['Helmsman'];m['Fuel']='Diesel';m['NormalizedFuel']='Diesel';m['Propulsion']='Shaft';m['NormalizedPropulsion']='Shaft';m['EngineCount']=1;m['Flybridge']='Yes';m['HullType']='Semi-Displacement';m['NormalizedHullForm']='Semi-Displacement';m['LastYear']=None
    if m['BoatModelID']=='HELM-31-CA': m.update(Model='31 Sedan',FirstYear=2011,LOA_ft=31.0,Beam_ft=10.5,Draft_ft=3.0,Displacement_lb=11500,FuelCapacity=150,WaterCapacity=100,HoldingCapacity=30)
    elif m['BoatModelID']=='HELM-38E-TR': m.update(Model='38E Pilothouse',FirstYear=2014)
    elif m['BoatModelID']=='HELM-43-E': m.update(Model='43E Pilothouse',FirstYear=2018)
    else: m.update(Model='46 Pilothouse',FirstYear=2025,LOA_ft=50.08,Beam_ft=16.25,Draft_ft=5.0,Displacement_lb=45000,FuelCapacity=800,WaterCapacity=300,HoldingCapacity=100,EngineConfiguration='Single Cummins QSC 8.3 diesel; higher-output options available')
    generic(m,f"The Helmsman {m['Model']} is a modern single-diesel semi-displacement cruising trawler emphasizing protected running gear, practical machinery access, low exterior maintenance and warm traditional interiors. Helmsman’s range spans the Camano-derived 31 Sedan through larger raised-pilothouse boats intended for extended coastal and long-range cruising.",['Single diesel with full-keel/skeg running-gear protection','Low-maintenance exterior with strong machinery access','Modern layouts combine traditional wood interiors with contemporary systems'],['Wide-beam larger models require substantial marina and haul-out infrastructure','Single-engine propulsion lacks second-engine redundancy','Newer complex electrical, thruster and comfort systems increase systems-management burden'],['Couples planning serious coastal and extended cruising','Owners wanting traditional trawler utility without exterior teak burden','Buyers prioritizing machinery access and single-diesel efficiency'],['You require twin-engine propulsion redundancy','You need compact trailerable dimensions beyond the 31 class','You prefer minimalist systems with little dependence on thrusters/electrical equipment'],['Verify factory build specification and optional-equipment list','Inspect hull/deck penetrations, windows and pilothouse doors for leaks','Inspect engine, cooling, exhaust, shaft, skeg, rudder and hydraulic steering','Test bow/stern thrusters, charging, inverter, generator and navigation systems','Confirm loaded weight, air draft and tankage for intended route'],[{'Name':'Sedan and pilothouse range','Description':'Helmsman uses related design principles across Sedan and Pilothouse models; the 31 derives from the Camano 31 hull while larger boats are separate Helmsman designs.','AffectedYears':'2011 onward','EvidenceRefs':src,'Confidence':'High'}],src,[],'passage' if m['BoatModelID']=='HELM-46-PH' else 'coastal','Reviewed')

# Great Harbour
for m in [x for x in models if x.get('Manufacturer')=='Great Harbour']:
    src=S['Great Harbour'];m.update(LOA_ft=36.83,Beam_ft=15.83,Draft_ft=2.83,Displacement_lb=48000,FuelCapacity=500,WaterCapacity=300,HoldingCapacity=100,EngineCount=2,Fuel='Diesel',NormalizedFuel='Diesel',Propulsion='Shaft',NormalizedPropulsion='Shaft',EngineConfiguration='Twin 54 hp Yanmar diesels');m['Flybridge']='Optional'
    if m['BoatModelID']=='GRTH-GH37':m['Model']='GH37'
    else:m['Model']='N37'
    generic(m,f"The Great Harbour {m['Model']} is a very wide, shallow-draft full-displacement trawler from Mirage Manufacturing. It uses twin small diesels, exceptional interior volume and large tankage to prioritize liveaboard comfort, low-speed economy and shallow-water access over conventional trawler proportions or speed.",['Exceptional interior volume and tankage for nominal length','Twin low-horsepower diesels provide redundancy with modest fuel burn','Very shallow draft and protected low-speed cruising mission'],['15 ft 10 in beam creates major slip, lock and haul-out constraints','48,000 lb displacement is exceptionally high for a 37-foot nominal length','Cruising speed is firmly displacement-speed and the unconventional hull form is mission-specific'],['Liveaboard couples prioritizing space and shallow draft','Great Loop, Bahamas and long-duration low-speed cruising','Owners who value twin-engine redundancy more than speed'],['Your marina or waterways impose narrow-beam limits','You require conventional 37-foot haul-out/transport options','You want fast cruise speeds or sporty handling'],['Confirm GH37 versus N37 layout and optional flybridge configuration','Inspect integral fiberglass tanks and all fuel/water plumbing','Inspect twin-engine cooling, exhaust, shafts, rudders and steering','Inspect cored superstructure/deck penetrations and windows','Verify electrical service, inverter/generator and household-appliance installations'],[{'Name':'GH37 versus N37 layout','Description':'GH37 and N37 share principal dimensions and machinery but use materially different interior/deck arrangements; the N37 emphasizes couple cruising while the GH37 maximizes multi-level liveaboard volume.','AffectedYears':'Production run','EvidenceRefs':src,'Confidence':'High'}],src,[],'passage','Reviewed')

# Prairie
for m in [x for x in models if x.get('Manufacturer')=='Prairie']:
    src=S['Prairie'];m['Fuel']='Diesel';m['NormalizedFuel']='Diesel';m['Propulsion']='Shaft';m['NormalizedPropulsion']='Shaft';m['Flybridge']='Yes'
    if m['BoatModelID']=='PRAI-36-TR': m.update(Model='36 Coastal Cruiser',FirstYear=1979,LastYear=1982);un=['Prairie closed in the early 1980s and the 36 molds/tooling were subsequently used for the Atlantic 37 Double Cabin.'];status='Reviewed'
    else: m.update(Model='29 Trawler',FirstYear=1977,LastYear=1983);un=['Detailed factory documentation for the Prairie 29 is limited; principal specifications remain representative pending stronger primary-source confirmation.'];status='Initial'
    generic(m,f"The Prairie {m['Model']} is a compact American traditional trawler from the short-lived Prairie Boat Works line. The designs emphasize straightforward diesel cruising and practical accommodations; the 36 became particularly significant because its tooling continued as the Atlantic 37 Double Cabin after Prairie ceased operations.",['Traditional cruising layout and straightforward diesel shaft propulsion','Strong interior utility relative to length','Prairie 36 design lineage continued as the Atlantic 37'],['Low production and age make documentation and replacement trim less straightforward','Surviving boats are highly condition-dependent','Traditional low-speed mission limits performance expectations'],['Budget-conscious buyers seeking an uncommon traditional trawler','Owners comfortable researching and maintaining low-volume older boats','Slow inland and coastal cruising'],['You require abundant factory/dealer support','You want high-speed performance','You are unwilling to accept condition and documentation variability'],['Verify model identity, year and build documentation carefully','Inspect decks, windows and superstructure for moisture and prior repairs','Inspect fuel/water tanks, wiring, exhaust and cooling systems','Inspect shafts, rudders, keel and steering','Review owner modifications due to the boats’ age and low-volume history'],[{'Name':'Prairie 36 / Atlantic 37 lineage','Description':'After Prairie closed, Atlantic Yachts acquired the Prairie 36 molds and reintroduced the design as the Atlantic 37 Double Cabin.','AffectedYears':'1979–1982 Prairie production; Atlantic successor from 1982','EvidenceRefs':src,'Confidence':'High'}],src,un,'coastal',status)

# SeaPiper
for m in [x for x in models if x.get('Manufacturer')=='SeaPiper']:
    src=S['SeaPiper'];m.update(Model='35',FirstYear=2018,LastYear=None,LOA_ft=35.92,Beam_ft=8.5,Draft_ft=2.92,Displacement_lb=17000,FuelCapacity=240,WaterCapacity=95,HoldingCapacity=32,EngineCount=1,Fuel='Diesel',NormalizedFuel='Diesel',Propulsion='Shaft',NormalizedPropulsion='Shaft',EngineConfiguration='Single Beta Marine 85 hp diesel',Flybridge='No')
    generic(m,'The SeaPiper 35 is an unusually narrow long-range pilothouse cruiser designed around an 8 ft 6 in beam, shallow draft and single 85 hp diesel. Its light-commercial aesthetic, separated cockpit/pilothouse/forward-accommodation zones and substantial tankage prioritize efficient low-speed travel and easy berth access over conventional yacht styling.',['8 ft 6 in beam is exceptionally narrow for a 35-foot cruising boat','Single-diesel displacement efficiency with substantial 240-gallon fuel capacity','Shallow draft and low bridge-clearance configuration expand route options'],['Narrow beam limits interior width and form stability compared with beamy trawlers','Cruising speed is approximately 7–9 knots','Distinctive utilitarian layout may not suit buyers wanting one open continuous salon'],['Couples prioritizing range, narrow beam and efficient inland/coastal cruising','Owners who value simple workboat-inspired systems and protected pilothouse operation','Routes where slip width or bridge clearance matters'],['You need wide-beam liveaboard volume','You require high-speed performance','You prefer conventional luxury-yacht interior integration'],['Verify hull-specific build specification and any production changes','Inspect aluminum/stainless fittings, windows, sliding doors and deck penetrations','Inspect Beta diesel cooling, exhaust, shaft, rudder and fuel systems','Verify tank installation, fuel transfer and sanitation systems','Test electrical, inverter/charging and optional comfort systems'],[{'Name':'Air-draft configuration','Description':'Published factory material gives approximately 8 ft 6 in bridge clearance with radar mast down and about 13 ft with mast up.','AffectedYears':'Production run','EvidenceRefs':src,'Confidence':'High'}],src,[],'coastal','Reviewed')

# write
json.dump(models,open(model_file,'w',encoding='utf-8'),indent=2,ensure_ascii=False);open(model_file,'a').write('\n')
ids=[m['BoatModelID'] for m in models if m.get('Manufacturer') in families]
report={'phase':'8C-10','date':today,'families':families,'normalizedRecords':len(ids),'modelCount':len(models),'reviewed':sum(1 for m in models if m.get('Manufacturer') in families and m.get('ResearchStatus')=='Reviewed'),'initial':sum(1 for m in models if m.get('Manufacturer') in families and m.get('ResearchStatus')=='Initial'),'knownConcernsPromoted':0,'notableFindings':['DeFever 34 corrected to 34 Passagemaker (1974-76); generic 45/47/49 records aligned to documented 45 Pilothouse, 47 POC Motor Yacht and 49 Cockpit Motor Yacht.','DeFever 38 retained as unresolved identity rather than forced into a cataloged production model.','Island Gypsy generic 32 overlaps the explicit 32 Sedan record and is flagged for later ID consolidation.','Island Gypsy 50 remains unresolved against the better-documented 49-foot historical variants.','Willard Vega designations are treated as hull families with distinct Nomad, Voyager, Horizon and other configurations.','Prairie 36 lineage to Atlantic 37 is documented; Prairie 29 remains Initial pending stronger primary documentation.','Great Harbour GH37 and N37 share principal dimensions and machinery but materially different layouts.','SeaPiper 35 factory specifications confirm 8 ft 6 in beam and approximately 8 ft 6 in mast-down bridge clearance.']}
os.makedirs(os.path.join(root,'developer/reports'),exist_ok=True)
rp=os.path.join(root,'developer/reports/phase8c10-traditional-trawler-family-normalization.json');json.dump(report,open(rp,'w',encoding='utf-8'),indent=2);open(rp,'a').write('\n')
md=os.path.join(root,'developer/reports/PHASE_8C10_TRADITIONAL_TRAWLER_FAMILY_NORMALIZATION.md');open(md,'w',encoding='utf-8').write(f"# Phase 8C-10 — Traditional trawler families\n\nNormalized {len(ids)} records across {len(families)} manufacturers.\n\n- Reviewed: {report['reviewed']}\n- Initial pending stronger identity/source support: {report['initial']}\n- KnownConcerns promoted: 0\n- Total B-Atlas models: {len(models)}\n\nNo generic legacy CommonProblems were promoted to model-specific defects.\n")
print(json.dumps(report,indent=2))
