import json, os, shutil
from copy import deepcopy
root=os.path.abspath(os.path.join(os.path.dirname(__file__),'..'))
model_file=os.path.join(root,'boatmodels.json')
models=json.load(open(model_file,encoding='utf-8'))
today='2026-08-07'
families=['Cheoy Lee','Californian','Gulfstar','Ocean Alexander','Tollycraft','Uniflite','Universal','Transpacific Marine','Mariner','Seahorse','Sealord']
S={
'Cheoy Lee':['https://www.cheoyleeassociation.com/Power/Powertrawler3.htm','https://www.hmy.com/yachting/powerboat-guide/cheoy-lee'],
'Californian':['https://www.hmy.com/yachting/powerboat-guide/californian/34-lrc-1977-85','https://www.hmy.com/yachting/powerboat-guide/californian/38-lrc-sedan-1978-85'],
'Gulfstar':['https://www.hmy.com/yachting/powerboat-guide/gulfstar','https://sailboatdata.com/sailboat/gulfstar-39-sailmaster/'],
'Ocean Alexander':['https://www.hmy.com/yachting/powerboat-guide/ocean-alexander','https://ca.boats.com/power-boats/1986-ocean-alexander-39-sedan-10098720/'],
'Tollycraft':['https://www.hmy.com/yachting/powerboat-guide/tollycraft','https://tollycruisers.ca/tollylife/how-many-tollycrafts/'],
'Uniflite':['https://www.hmy.com/yachting/powerboat-guide/uniflite/36-double-cabin-1972-84'],
'Universal':['https://trinidad.boatshed.com/universal_36_trawler-boat-337526.html'],
'Transpacific Marine':['https://www.hmy.com/yachting/powerboat-guide/eagle/32-pilothouse-1985-98','https://bronteshore.ca/current_listings/1986-eagle-marine-trawler/'],
'Mariner':[],
'Seahorse':['https://passagemaker.com/cruiser-reviews/the-mighty-ducks/'],
'Sealord':['https://www.boatdealers.ca/boats-for-sale/542099/sealord-tricabin-hamilton-ontario']
}

def suit(m,exposed='Mixed'):
 return {
 'CoupleCruising':{'Assessment':'Good','Summary':'The documented cruising layout is practical for a couple; guest capacity and privacy vary by model.'},
 'SoloHandling':{'Assessment':'Mixed','Summary':'Lower-helm access and protected decks can help short-handed operation, but windage, engine count and docking equipment remain hull-specific.'},
 'InlandWaterways':{'Assessment':'Good' if (m.get('Beam_ft') or 99)<=14 else 'Mixed','Summary':'Route fit depends on actual beam, draft and air draft; verify bridge and marina limits for the individual boat.'},
 'ExposedWater':{'Assessment':exposed,'Summary':'Condition, loading and actual hull configuration are decisive; this assessment reflects documented design intent rather than an offshore guarantee.'}}

def evidence(m,sources,unresolved,status='Reviewed'):
 ap={'Scope':'Model','Models':[m['BoatModelID']],'Years':{'From':m.get('FirstYear'),'To':m.get('LastYear')},'Variations':[]}
 m['EvidenceSummary']={'KnowledgeCoverage':'Strong' if status=='Reviewed' else 'Partial','EvidenceQuality':'Moderate' if status=='Reviewed' else 'Low','Statements':[
 {'Scope':'IdentityAndDimensions','AppliesTo':deepcopy(ap),'EvidenceRefs':sources,'EvidenceTypes':['Factory documented','Technical or survey source'] if sources else ['Unverified'],'Confidence':'High' if status=='Reviewed' else 'Moderate','Notes':'Representative identity and specifications use model-specific references where available; unresolved production or hull differences remain explicit.'},
 {'Scope':'OverviewAndSuitability','AppliesTo':deepcopy(ap),'EvidenceRefs':sources,'EvidenceTypes':['Technical or survey source'] if sources else ['Unverified'],'Confidence':'Moderate' if sources else 'Low','Notes':'Guidance is derived from documented configuration and design traits, not marketplace promotion.'},
 {'Scope':'InspectionFocus','AppliesTo':dict(ap,Scope='Model family'),'EvidenceRefs':sources,'EvidenceTypes':['Technical or survey source'] if sources else ['Unverified'],'Confidence':'Moderate' if sources else 'Low','Notes':'Inspection items are age/configuration risks to investigate and are not assertions that every hull has the defect.'}
 ],'UnresolvedInformation':unresolved+['Legacy CommonProblems were not promoted to KnownConcerns without model-specific evidence meeting the approved threshold.']}
 m['ResearchStatus']=status;m['DataConfidence']='Moderate' if status=='Reviewed' else 'Low';m['ReviewedBy']='B-Scout Phase 8C-11 Classic Taiwanese / Older Motoryacht Research';m['LastUpdated']=today;m['Revision']=(m.get('Revision') or 1)+1

def questions(items): return ['What inspection, repair or service history is available for '+x[0].lower()+x[1:]+'?' for x in items]
def norm(m,overview,strengths,tradeoffs,best,avoid,insp,variations,sources,unresolved,status='Reviewed',exposed='Mixed'):
 m['Overview']=overview;m['Suitability']=suit(m,exposed);m['Strengths']=strengths;m['TradeOffs']=tradeoffs;m['BestFor']=best;m['AvoidIf']=avoid;m['KnownConcerns']=[];m['InspectionFocus']=insp;m['BuyerQuestions']=questions(insp);m['OwnerActions']=['Keep deck, window and hardware penetrations sealed and investigate leaks promptly','Maintain propulsion, cooling, exhaust, steering and fuel systems to documented intervals','Document structural, tank, electrical and machinery repairs for future buyers'];m['ModelVariations']=variations;evidence(m,sources,unresolved,status)
 m['ResearchNotes']='\n\n'.join(x for x in [f'Phase 8C-11 classic Taiwanese / older motoryacht normalization {today}. Unsupported defects remain unknown.',(m.get('ResearchNotes') or '').strip()] if x)

byid={m['BoatModelID']:m for m in models}
# identity corrections
id_changes={'CHLY-33':'CHLY-32','CHLY-36-SE':'CHLY-36-TR'}
for old,new in id_changes.items():
 m=byid.pop(old);m['BoatModelID']=new;byid[new]=m
 if old=='CHLY-36-SE':
  oldimg=os.path.join(root,'images/chly-36-se.jpg');newimg=os.path.join(root,'images/chly-36-tr.jpg')
  if os.path.exists(oldimg) and not os.path.exists(newimg): shutil.move(oldimg,newimg)
  m['ImageURL']='images/chly-36-tr.jpg'
 else:m['ImageURL']='images/chly-32.jpg'
# refresh models list references already mutated

# Cheoy Lee
for m in [x for x in models if x.get('Manufacturer')=='Cheoy Lee']:
 src=list(S['Cheoy Lee']);un=[];status='Reviewed';m.update(Fuel='Diesel',NormalizedFuel='Diesel',Propulsion='Shaft',NormalizedPropulsion='Shaft')
 if m['BoatModelID']=='CHLY-28':
  m.update(Model='28 Trawler',Variant='Trawler',LOA_ft=27.92,Beam_ft=10.25,Draft_ft=3.25,Displacement_lb=14500,FuelCapacity=310,EngineCount=1,EngineConfiguration='Single diesel; engine make and horsepower vary by hull',AftCabin='No');un=['Published production-year detail for the 28 Trawler remains less complete than its brochure specifications.']
 elif m['BoatModelID']=='CHLY-32':
  m.update(Model='32 Trawler',Variant='Trawler',FirstYear=1977,LastYear=1986,LOA_ft=31.92,Beam_ft=12.0,Draft_ft=4.42,Displacement_lb=19000,FuelCapacity=360,WaterCapacity=200,EngineCount=1,EngineConfiguration='Single Ford Lehman diesel commonly documented',Flybridge='Yes',AftCabin='No');src+=['https://www.hmy.com/yachting/powerboat-guide/cheoy-lee/32-trawler-1977-86']
 elif m['BoatModelID']=='CHLY-35':
  m.update(Model='35 Trawler',Variant='Trawler',FirstYear=1979,LastYear=1986,LOA_ft=34.92,Beam_ft=12.0,Draft_ft=3.58,Displacement_lb=21000,FuelCapacity=650,WaterCapacity=210,HoldingCapacity=30,EngineCount=1,EngineConfiguration='Single 120 hp Ford Lehman diesel commonly documented',Flybridge='Yes',AftCabin='No',Cabins=1,Heads=1);src+=['https://www.hmy.com/yachting/powerboat-guide/cheoy-lee/35-trawler-1979-86']
 else:
  m.update(Model='36 Trawler Mk II',Variant='Trawler',LOA_ft=36.5,Beam_ft=13.0,Draft_ft=3.5,FuelCapacity=620,Flybridge='Yes',AftCabin='Yes',NormalizedStyle='Trawler');status='Initial';un=['Original brochure material confirms the 36 Trawler Mk II dimensions and tankage, but a precise production-year range and representative machinery package require stronger model-specific documentation.']
 norm(m,f"The Cheoy Lee {m['Model']} is a Hong Kong-built traditional cruising powerboat from Cheoy Lee's classic trawler period. Heavy fiberglass construction, teak joinery, protected running gear and displacement-oriented operation define the family, while layout and machinery differ materially by model.",['Traditional teak interior and substantial fiberglass construction','Protected shaft/rudder arrangement suited to low-speed cruising','Strong classic-yacht character with practical side-deck access'],['Exterior teak and older deck/window systems can demand substantial upkeep','Heavy displacement and low-speed mission limit performance','Age, yard practices and owner modifications create significant hull-to-hull variation'],['Couples seeking a traditional wood-rich cruising boat','Owners comfortable maintaining older teak-intensive yachts','Low-speed inland and coastal cruising'],['You require modern low-maintenance finishes','You need planing-speed performance','You want standardized equipment and documentation across every hull'],['Confirm exact model identity and build year from hull documentation','Inspect teak decks, cabin-top penetrations, windows and trim for moisture intrusion','Inspect fuel/water tanks, wiring, plumbing and owner modifications','Inspect engine cooling, exhaust, mounts, shaft, rudder and keel/skeg','Verify flybridge, mast and air-draft configuration for intended routes'],[{'Name':'Model and equipment variation','Description':'Cheoy Lee produced multiple trawler sizes and machinery/layout arrangements; individual hull documentation controls exact equipment and construction detail.','AffectedYears':'Production run','EvidenceRefs':src,'Confidence':'Moderate'}],src,un,status,'Mixed')

# Californian
for m in [x for x in models if x.get('Manufacturer')=='Californian']:
 src=list(S['Californian']);m.update(Fuel='Diesel',NormalizedFuel='Diesel',Propulsion='Shaft',NormalizedPropulsion='Shaft',EngineCount=2,Flybridge='Yes',AftCabin='No')
 if m['BoatModelID']=='CALF-34-TR':m.update(Model='34 LRC',Variant='Long Range Cruiser',FirstYear=1977,LastYear=1985,LOA_ft=34.5,Beam_ft=12.33,Draft_ft=3.17,Displacement_lb=18000,FuelCapacity=250,WaterCapacity=75,HoldingCapacity=30,NormalizedStyle='Cruiser')
 else:m.update(Model='38 LRC Sedan',Variant='Long Range Cruiser Sedan',FirstYear=1978,LastYear=1985,LOA_ft=37.67,Beam_ft=13.0,Draft_ft=3.5,Displacement_lb=28000,FuelCapacity=400,WaterCapacity=100,HoldingCapacity=25,NormalizedStyle='Cruiser')
 norm(m,f"The Californian {m['Model']} is a U.S.-built flybridge sedan cruiser with trawler-like styling but a modified-V hull capable of substantially more than displacement speed with higher-power diesel packages. Wide side decks and practical lower-helm layouts favor family coastal cruising rather than traditional full-displacement operation.",['Solid-fiberglass U.S.-built hull and practical deck access','Can cruise economically at low speed yet accept higher-power diesel packages','Useful sedan layout with lower helm and cockpit'],['Wide side decks reduce interior width','Performance and fuel economy vary greatly with engine package','Older machinery, tanks and deck hardware remain condition-sensitive'],['Buyers wanting classic trawler appearance without being limited to trawler speed','Coastal cruising couples or families using a cockpit-oriented layout','Owners who value simpler exterior trim than many Taiwan trawlers'],['You require a true full-displacement passagemaker','You need an aft-cabin layout','You want predictable economy without verifying the installed engines'],['Verify original versus repowered engine package and realistic cruise fuel burn','Inspect decks, windows, cockpit and flybridge penetrations for moisture','Inspect fuel tanks, exhaust, cooling and engine beds','Inspect shafts, struts, rudders and steering','Confirm lower-helm visibility and side-deck access for the intended crew'],[{'Name':'Engine and layout options','Description':'Both models were offered with differing layouts and engine packages; performance ranges from displacement-speed economy to planing-capable cruising.','AffectedYears':'Production run','EvidenceRefs':src,'Confidence':'High'}],src,[],'Reviewed','Mixed')

# Gulfstar
for m in [x for x in models if x.get('Manufacturer')=='Gulfstar']:
 src=list(S['Gulfstar']);un=[];status='Reviewed';m.update(Fuel='Diesel',NormalizedFuel='Diesel',Propulsion='Shaft',NormalizedPropulsion='Shaft')
 i=m['BoatModelID']
 if i=='GULF-36-TR':m.update(Model='36 Trawler',Variant='Trawler',FirstYear=1972,LastYear=1976,LOA_ft=36.25,Beam_ft=12,Draft_ft=3,Displacement_lb=16000,FuelCapacity=250,WaterCapacity=100,EngineCount=2,EngineConfiguration='Twin 80 hp Perkins diesels commonly documented',Flybridge='Yes',AftCabin='Yes');src+=['https://www.hmy.com/yachting/powerboat-guide/gulfstar/36-trawler-1972-76']
 elif i=='GULF-39-SM':m.update(Model='39 Sailmaster',Variant='Sailmaster Motorsailer',FirstYear=1981,LastYear=1984,LOA_ft=39.58,Beam_ft=12.06,Draft_ft=4.75,Displacement_lb=19000,FuelCapacity=80,WaterCapacity=150,EngineCount=1,EngineConfiguration='Single Perkins 4-108 50 hp auxiliary diesel',Flybridge='No',AftCabin='No',NormalizedStyle='Motorsailer');un=['This is a sailing motorsailer rather than a conventional power trawler; B-Scout should preserve that classification in search and comparison.']
 elif i=='GULF-43-TR':m.update(Model='43 Trawler',Variant='Trawler',FirstYear=1972,LastYear=1977,LOA_ft=43.33,Beam_ft=13.92,Draft_ft=3.5,Displacement_lb=21000,FuelCapacity=300,WaterCapacity=130,EngineCount=2,EngineConfiguration='Twin Perkins diesels commonly documented',Flybridge='Yes',AftCabin='Yes');src+=['https://www.hmy.com/yachting/powerboat-guide/gulfstar/43-trawler-1972-77']
 elif i=='GULF-44-MC':m.update(Model='44 Motor Cruiser',Variant='Motor Cruiser',FirstYear=1978,LastYear=1980,LOA_ft=44.42,Beam_ft=14.5,Draft_ft=4,Displacement_lb=28400,FuelCapacity=500,WaterCapacity=250,HoldingCapacity=40,EngineCount=2,EngineConfiguration='Twin Perkins diesels',Flybridge='Yes',AftCabin='Yes',NormalizedStyle='Trawler');src+=['https://www.hmy.com/yachting/powerboat-guide/gulfstar/44-motor-cruiser-1978-80']
 else:m.update(Model='49 Motor Yacht',Variant='Motor Yacht',FirstYear=1984,LastYear=1987,LOA_ft=49,Beam_ft=15.08,Draft_ft=3.83,Displacement_lb=42000,FuelCapacity=675,WaterCapacity=370,EngineCount=2,EngineConfiguration='Twin Perkins 350 hp or GM 6-71 diesel packages',Flybridge='Yes',AftCabin='Yes',Cabins=3,Heads=3,NormalizedStyle='Motor Yacht');src+=['https://www.hmy.com/yachting/powerboat-guide/gulfstar/49-motor-yacht-1984-87']
 norm(m,f"The Gulfstar {m['Model']} reflects Gulfstar's broad 1970s–1980s range from sail-derived trawlers and motorsailers to larger motor yachts. The specific model's hull form, speed and accommodation must be judged independently rather than treating all Gulfstars as conventional trawlers.",['Substantial cruising accommodations and tankage for length','Generally practical machinery and lower-helm arrangements on power models','Distinctive designs ranging from efficient trawlers to capable motor yachts'],['Model families differ substantially in hull construction and performance','Age makes tanks, deck penetrations, wiring and machinery condition critical','Larger models carry significant systems, air-draft and operating-cost burdens'],['Cruising buyers who understand the specific Gulfstar generation','Owners comfortable maintaining older systems-rich fiberglass yachts','Inland and coastal cruising where the documented model mission fits'],['You assume every Gulfstar is a slow displacement trawler','You need low systems complexity or easy road transport','You are unwilling to verify model generation, hull construction and engine package'],['Verify exact model and generation against hull documentation','Inspect deck/core areas, windows and structural penetrations','Inspect fuel/water tanks, wiring, plumbing, generator and HVAC systems','Inspect engines, exhaust, cooling, shafts, rudders and keel','Confirm air draft and actual displacement for intended route and haul-out'],[{'Name':'Generation-specific design changes','Description':'Gulfstar reused and evolved hull concepts across trawlers, motorsailers and motor yachts; Mk II and later motor-yacht generations can differ materially in layout, structure and speed.','AffectedYears':'Varies by model','EvidenceRefs':src,'Confidence':'High'}],src,un,status,'Mixed')

# Ocean Alexander
for m in [x for x in models if x.get('Manufacturer')=='Ocean Alexander']:
 src=list(S['Ocean Alexander']);status='Initial';un=['Early small-model Ocean Alexander documentation is incomplete in the current source set; production years and representative specifications should be verified against builder records or multiple model-specific technical sources before promotion to Reviewed.'];m.update(Fuel='Diesel',NormalizedFuel='Diesel',Propulsion='Shaft',NormalizedPropulsion='Shaft',EngineCount=2,Flybridge='Yes',AftCabin='No')
 if m['BoatModelID']=='OCAL-39-SE':
  m.update(Model='39 Sedan',Variant='Sedan');src+=['https://www.yachtworld.com/yacht/1986-ocean-alexander-39-sedan-10098720/'];un=['1986 examples clearly establish the 39 Sedan identity and two-stateroom flybridge layout, but a definitive production range and standard factory specification remain unresolved.']
 else:m.update(Model='36 Sedan',Variant='Sedan');un=['The 36 Sedan identity remains weakly documented in the current research set and should be treated as provisional pending stronger model-specific evidence.']
 norm(m,f"The Ocean Alexander {m['Model']} is an early Taiwan-built flybridge sedan cruiser associated with Alexander Marine's better-finished motoryacht tradition. The recorded layout emphasizes teak interior joinery, twin-diesel shaft propulsion and coastal cruising, but early small-model documentation is less complete than for later Ocean Alexander ranges.",['Traditional teak interior and practical flybridge-sedan layout','Twin-diesel shaft propulsion provides maneuvering redundancy','Ocean Alexander developed a strong reputation for fit and finish among Taiwan builders'],['Early-model documentation and standard specifications are incomplete','Twin machinery and aging systems increase maintenance burden','Individual boats can differ materially after decades of refits'],['Buyers seeking a traditional Northwest-style twin-diesel sedan','Coastal cruising couples wanting lower and upper helm positions','Owners willing to verify an uncommon early model carefully'],['You require fully documented factory specifications before purchase','You prefer single-engine economy and simplicity','You want low-maintenance modern construction details'],['Confirm exact model, year and builder plate before relying on marketplace naming','Inspect decks, windows, flybridge and rail penetrations for moisture','Inspect tanks, wiring, plumbing, generator and HVAC installations','Inspect twin diesels, exhaust, cooling, shafts and steering','Verify hull-specific air draft, displacement and tankage'],[],src,un,status,'Mixed')

# Tollycraft
for m in [x for x in models if x.get('Manufacturer')=='Tollycraft']:
 src=list(S['Tollycraft']);un=[];status='Reviewed';m.update(Propulsion='Shaft',NormalizedPropulsion='Shaft',EngineCount=2,Flybridge='Yes',AftCabin='No')
 if m['BoatModelID']=='TOLL-34-SE':m.update(Model='34 Sport Sedan',Variant='Sport Sedan',FirstYear=1987,LastYear=1993,LOA_ft=34,Beam_ft=12.5,Draft_ft=2.83,Displacement_lb=17000,FuelCapacity=200,WaterCapacity=116,AirDraft_ft=13.92,Fuel='Gasoline or Diesel',NormalizedFuel='Mixed Diesel/Gasoline');src+=['https://www.hmy.com/yachting/powerboat-guide/tollycraft/34-sport-sedan-1987-93']
 else:m.update(Model='37 Sedan',Variant='Sedan',FirstYear=1974,LastYear=1980,Fuel='Gasoline or Diesel',NormalizedFuel='Mixed Diesel/Gasoline');status='Initial';un=['Owner-club and marketplace evidence clearly supports the 37 Sedan identity and 1970s production, but the current source set does not establish one authoritative model-wide specification and engine package.']
 norm(m,f"The Tollycraft {m['Model']} is a Pacific Northwest-built fiberglass flybridge sedan emphasizing practical cockpit use, broad visibility and solid cruising construction. Unlike traditional displacement trawlers, these boats use modified-V powerboat hulls and were offered with gasoline and, on some configurations, diesel power.",['Well-regarded Northwest fiberglass construction','Practical cockpit, lower helm and flybridge arrangement','Good interior utility without heavy trawler-style exterior teak'],['Fuel burn and performance depend strongly on engine package','Older gasoline installations may not suit buyers prioritizing diesel economy','Age-related deck, window, tank and wiring condition still requires careful survey'],['Pacific Northwest and Great Lakes coastal cruising','Buyers wanting classic sedan practicality with moderate-speed capability','Owners who value cockpit utility and dual helm stations'],['You require a full-displacement trawler','You insist on single-diesel simplicity','You are unwilling to verify original versus repowered machinery'],['Verify exact Tollycraft model/year and engine package','Inspect deck, flybridge, window and cockpit penetrations for moisture','Inspect fuel tanks, exhaust systems, wiring and engine-room ventilation','Inspect shafts, struts, rudders and steering','Confirm bridge configuration and air draft'],[{'Name':'Engine and bridge arrangements','Description':'Tollycraft models commonly appeared with different gasoline/diesel packages and bridge layouts; individual equipment must be verified.','AffectedYears':'Production run','EvidenceRefs':src,'Confidence':'Moderate'}],src,un,status,'Mixed')

# Uniflite
for m in [x for x in models if x.get('Manufacturer')=='Uniflite']:
 src=list(S['Uniflite']);m.update(Model='36 Double Cabin',Variant='Double Cabin',FirstYear=1972,LastYear=1984,LOA_ft=36,Beam_ft=12.33,Draft_ft=2.67,AirDraft_ft=12.25,Displacement_lb=21000,FuelCapacity=200,WaterCapacity=100,Fuel='Gasoline',NormalizedFuel='Gasoline',Propulsion='Shaft',NormalizedPropulsion='Shaft',EngineCount=2,EngineConfiguration='Twin gasoline inboards standard; repowers vary',Flybridge='Yes',AftCabin='Yes',NormalizedStyle='Motor Yacht')
 norm(m,'The Uniflite 36 Double Cabin is a U.S.-built aft-cabin motor yacht with a solid-fiberglass hull, full-width aft master stateroom and dual helm stations. It is a conventional planing powerboat rather than a trawler, and most examples were delivered with twin gasoline inboards.',['Solid-fiberglass construction and practical aft-cabin layout','Full-width aft master provides unusual privacy for 36 feet','Dual helm stations and moderate beam support family cruising'],['Twin gasoline power increases fuel consumption relative to diesel trawlers','Older examples require careful blister and laminate inspection','Aft-cabin windage and systems age increase docking and ownership demands'],['Great Lakes and coastal buyers wanting an older aft-cabin motor yacht','Families prioritizing two private sleeping areas','Owners comfortable with twin gasoline machinery or documented repowers'],['You require diesel economy or trawler-speed efficiency','You want low windage and compact bridge clearance','You will not undertake a thorough hull-laminate inspection'],['Inspect hull and topsides carefully for blistering and laminate repairs','Confirm 1984 36 II versus earlier solid-hull configuration','Inspect fuel system, gasoline ventilation, exhaust and ignition-protection equipment','Inspect decks, windows and flybridge penetrations','Inspect shafts, rudders and steering'],[{'Name':'1984 36 II','Description':'A 36 II version appeared in 1984 with a fully cored hull, revised flybridge and interior, materially different from earlier solid-hull examples.','AffectedYears':'1984','EvidenceRefs':src,'Confidence':'High'}],src,[],'Reviewed','Mixed')

# Universal
for m in [x for x in models if x.get('Manufacturer')=='Universal']:
 src=list(S['Universal']);status='Initial';un=['Universal Marine Taiwan-built trawler naming is inconsistently documented; model-wide production years and specifications remain provisional pending stronger factory or technical references.'];m.update(Fuel='Diesel',NormalizedFuel='Diesel',Propulsion='Shaft',NormalizedPropulsion='Shaft',Flybridge='Yes')
 if m['BoatModelID']=='UNIV-36-TR':m.update(Model='36 Trawler',Variant='Trawler',LOA_ft=36,EngineCount=1,EngineConfiguration='Single Ford Lehman diesel commonly documented',AftCabin='Yes',Cabins=2,Berths=6,FuelCapacity=200,WaterCapacity=150);src+=['https://trinidad.boatshed.com/universal_36_trawler-boat-337526.html']
 else:m.update(Model='40 Trawler',Variant='Trawler',EngineCount=None)
 norm(m,f"The Universal {m['Model']} is a Taiwan-built traditional trawler associated with Universal Marine. Surviving examples emphasize teak interiors, displacement-speed diesel operation and conventional cruising layouts, but model naming and standard specifications are not consistently documented.",['Traditional teak trawler character and low-speed diesel mission','Shaft drive and protected cruising layout suit inland/coastal use','Practical liveaboard-oriented accommodation in surviving examples'],['Low-volume documentation makes model verification important','Exterior wood, tanks and systems may require substantial restoration','Performance is displacement-speed and individual machinery varies'],['Buyers comfortable researching a low-volume Taiwan trawler','Couples seeking classic wood-rich cruising accommodations','Slow inland and coastal cruising'],['You require broad factory documentation and parts support','You need planing speed','You are unwilling to verify hull-specific builder and equipment'],['Confirm builder plate, HIN, exact model and year','Inspect decks, windows and exterior teak for moisture and prior repairs','Inspect tanks, wiring, plumbing and sanitation systems','Inspect engine, cooling, exhaust, shaft, rudder and keel','Verify actual tankage, displacement and air draft'],[],src,un,status,'Mixed')

# Transpacific Eagle
for m in [x for x in models if x.get('Manufacturer')=='Transpacific Marine']:
 src=list(S['Transpacific Marine']);m.update(Model='Eagle 32 Pilothouse',Variant='Pilothouse Trawler',FirstYear=1985,LastYear=1998,LOA_ft=32,Beam_ft=11.5,Draft_ft=3.5,Displacement_lb=13000,Fuel='Diesel',NormalizedFuel='Diesel',Propulsion='Shaft',NormalizedPropulsion='Shaft',EngineCount=1,EngineConfiguration='Single Ford Lehman diesel; horsepower varies by year/hull',Flybridge='Optional',AftCabin='No',NormalizedStyle='Trawler')
 norm(m,'The Transpacific Marine Eagle 32 Pilothouse is a Taiwan-built tug/trawler-style displacement cruiser with a raised pilothouse, teak interior, single diesel and protected running gear. Its compact size and economical 7–8 knot operation make it particularly relevant to couples seeking traditional character without moving into a 36–40 foot trawler.',['Raised pilothouse provides strong visibility and weather protection','Single-diesel displacement economy with protected running gear','Warm teak interior and generous salon for a 32-foot boat'],['Forward stateroom is compact','Published tankage and displacement vary between individual examples','Low-volume model support requires careful hull-specific documentation'],['Couples cruising the Great Loop, Great Lakes or protected coast at displacement speed','Buyers seeking classic trawler character in a compact hull','Owners comfortable maintaining an older low-volume Taiwan-built boat'],['You require high cruising speed','You need broad factory/dealer support','You want modern low-maintenance exterior and systems'],['Confirm Transpacific/Eagle builder identity and exact year','Inspect decks, windows and pilothouse penetrations for moisture','Verify tank material and actual fuel/water capacities','Inspect Ford Lehman cooling, exhaust, mounts and service history','Inspect shaft, rudder, steering and optional upper-helm installation'],[{'Name':'Machinery and tankage variation','Description':'Surviving Eagle 32s document Ford Lehman engines from roughly 90 to 135 hp and materially different published tank capacities; hull-specific values must be verified.','AffectedYears':'1985–1998','EvidenceRefs':src,'Confidence':'High'}],src,['Published fuel, water, holding and displacement figures vary materially among surviving examples; B-Scout retains representative values only where corroborated.'],'Reviewed','Mixed')

# Low-evidence Mariner / Seahorse / Sealord
for make in ['Mariner','Seahorse','Sealord']:
 for m in [x for x in models if x.get('Manufacturer')==make]:
  src=list(S[make]);un=[];status='Initial';m['Propulsion']='Shaft';m['NormalizedPropulsion']='Shaft'
  if make=='Sealord':
   m.update(Model='34 Tri-Cabin',Variant='Tri-Cabin',FirstYear=1987,LastYear=1987,LOA_ft=34,Beam_ft=12,Draft_ft=3.5,Displacement_lb=18000,Fuel='Diesel',NormalizedFuel='Diesel',EngineCount=2,EngineConfiguration='Twin Volvo Penta MD31A diesels documented on a surviving example',Flybridge='Yes',AftCabin='Yes');un=['Current evidence establishes at least one 1987 Sealord (Chien Hwa) 34 Tri-Cabin and its principal dimensions, but not a complete model-wide production history.']
  elif make=='Seahorse':
   m['Fuel']='Diesel';m['NormalizedFuel']='Diesel';un=['The current research set confirms Seahorse as a yacht-building/importing operation but does not establish these 35/40 Pilothouse records as standardized production models with reliable model-wide specifications. Retain as provisional until stronger evidence is found.']
  else:un=['The Mariner 28 Seafarer powerboat identity remains weakly documented and is easily confused with unrelated Mariner sailboats and Carver Mariner models. Retain provisionally pending builder-specific evidence.']
  norm(m,f"The {make} {m['Model']} {m.get('Variant') or ''}".strip()+" is retained as a provisional B-Scout model because surviving-market evidence suggests the identity exists, but the current source set does not establish a complete factory specification or production history. Its recorded configuration should therefore be treated as a research lead rather than a fully verified model standard.",['Potentially useful classic cruising configuration if the individual hull matches the recorded identity'],['Documentation is sparse and marketplace naming may be inconsistent','Hull-specific condition and equipment dominate the buying decision','Factory-standard dimensions and systems are not yet sufficiently verified'],['Experienced buyers willing to verify an uncommon model from primary hull documentation'],['You require a fully documented model history before considering a candidate','You are unwilling to commission careful survey and identity verification'],['Confirm builder plate, HIN, model designation and year before relying on B-Scout specifications','Obtain prior surveys, manuals and original documentation where available','Inspect decks, windows, structure, tanks, wiring and plumbing','Inspect engines, exhaust, cooling, shafts, rudders and steering','Verify actual dimensions, tankage and air draft'],[],src,un,status,'Mixed')

# archive redirects for changed IDs
arch=os.path.join(root,'developer/archive/identity-migration-archive.json')
if os.path.exists(arch):
 d=json.load(open(arch,encoding='utf-8')); lm=d.setdefault('legacyIdMap',[])
 for old,new in id_changes.items():
  if not any(x.get('LegacyBoatModelID')==old and x.get('CurrentBoatModelID')==new for x in lm):lm.append({'LegacyBoatModelID':old,'ProposedV7BoatModelID':new,'MigrationStatus':'Migrated','SourceRecordCount':1,'CurrentBoatModelID':new,'RedirectType':'Permanent'})
 json.dump(d,open(arch,'w',encoding='utf-8'),indent=2);open(arch,'a').write('\n')

json.dump(models,open(model_file,'w',encoding='utf-8'),indent=2,ensure_ascii=False);open(model_file,'a').write('\n')
ids=[m['BoatModelID'] for m in models if m.get('Manufacturer') in families]
report={'phase':'8C-11','date':today,'families':families,'normalizedRecords':len(ids),'modelCount':len(models),'reviewed':sum(1 for m in models if m.get('Manufacturer') in families and m.get('ResearchStatus')=='Reviewed'),'initial':sum(1 for m in models if m.get('Manufacturer') in families and m.get('ResearchStatus')=='Initial'),'identityChanges':id_changes,'knownConcernsPromoted':0,'notableFindings':['Cheoy Lee 33 corrected to documented 32 Trawler; 36 Sedan corrected to 36 Trawler Mk II, with production years left unresolved.','Californian 34/38 corrected to 34 LRC and 38 LRC Sedan, which are modified-V cruisers rather than full-displacement trawlers.','Gulfstar 39 corrected to 1981–84 Sailmaster motorsailer; Gulfstar 49 corrected to 1984–87 Motor Yacht.','Ocean Alexander 36/39 remain Initial because early small-model documentation is incomplete; 39 Sedan identity is supported by surviving 1986 examples.','Tollycraft 34 corrected to 34 Sport Sedan (1987–93); 37 Sedan retained Initial pending a stronger model-wide specification source.','Uniflite 36 Double Cabin normalized and 1984 36 II variation documented.','Universal, Mariner, Seahorse and Sealord records remain conservative where model-wide documentation is weak.','Transpacific Marine Eagle 32 normalized to documented 1985–98 Pilothouse identity with hull-specific machinery/tankage variation.']}
os.makedirs(os.path.join(root,'developer/reports'),exist_ok=True)
json.dump(report,open(os.path.join(root,'developer/reports/phase8c11-classic-taiwanese-normalization.json'),'w',encoding='utf-8'),indent=2);open(os.path.join(root,'developer/reports/phase8c11-classic-taiwanese-normalization.json'),'a').write('\n')
open(os.path.join(root,'developer/reports/PHASE_8C11_CLASSIC_TAIWANESE_OLDER_MOTORYACHT_NORMALIZATION.md'),'w',encoding='utf-8').write(f"# Phase 8C-11 — Classic Taiwanese / older motoryachts\n\nNormalized {len(ids)} records across {len(families)} manufacturers.\n\n- Reviewed: {report['reviewed']}\n- Initial pending stronger model-specific evidence: {report['initial']}\n- Identity corrections: CHLY-33 → CHLY-32; CHLY-36-SE → CHLY-36-TR\n- KnownConcerns promoted: 0\n- Total B-Scout models: {len(models)}\n\nNo generic legacy CommonProblems were promoted to model-specific defects.\n")
print(json.dumps(report,indent=2))
