import json, os
from copy import deepcopy
root=os.path.abspath(os.path.join(os.path.dirname(__file__),'..'))
p=os.path.join(root,'boatmodels.json')
models=json.load(open(p,encoding='utf-8'))
today='2026-08-07'

SRC={
 'BENE_ST':['https://www.beneteau.com/en-us/heritage-powerboats/heritage-swift-trawler'],
 'BENE_ST30':['https://www.beneteau.com/en-us/heritage-swift-trawler/swift-trawler-30'],
 'BENE_ST34':['https://www.beneteau.com/en-us/swift-trawler/swift-trawler-34'],
 'BENE_ST35':['https://www.beneteau.com/en-us/former-swift-trawler/swift-trawler-35'],
 'BENE_ST47':['https://www.beneteau.com/en-us/heritage-swift-trawler/swift-trawler-47'],
 'BENE_ST48':['https://www.beneteau.com/en-us/swift-trawler/swift-trawler-48'],
 'BENE_ST52':['https://www.beneteau.com/en-us/swift-trawler/swift-trawler-52'],
 'BENE_ANT':['https://www.beneteau.com/en-us/heritage-powerboats/antares-2012-2022'],
 'BENE_ANT11':['https://www.beneteau.com/en-us/antares-outboard/antares-11'],
 'BENE_BAR':['https://www.beneteau.com/en-us/heritage-powerboats/barracuda'],
 'BENE_BAR8':['https://www.beneteau.com/en-us/barracuda/barracuda-8-23'],
 'BENE_BAR9':['https://www.beneteau.com/barracuda/barracuda-9'],
 'J_MF605':['https://www.jeanneau.com/boats/powerboat/9-merry-fisher/25-merry-fisher-605'],
 'J_MF635':['https://www.jeanneau.com/en-us/boats/powerboat/9-merry-fisher/312-merry-fisher-635'],
 'J_RANGE':['https://www.jeanneau.com/fr/comparateur/moteur'],
 'J_MF855':['https://www.jeanneau.com/fr/bateaux/moteur/9-merry-fisher/29-merry-fisher-855'],
 'J_MF895':['https://www.jeanneau.com/fr/articles/744-new-jeanneau-merry-fisher-895-launched'],
 'J_MF1095':['https://www.jeanneau.com/articles/1049-new-merry-fisher-1095','https://www.jeanneau.com/fr/bateaux/moteur/9-merry-fisher/618-merry-fisher-1095-coupe'],
 'J_MF1095F':['https://www.jeanneau.com/fr/articles/1610-nouveau-jeanneau-merry-fisher-1095-version-flybridge','https://www.jeanneau.com/boats/powerboat/9-merry-fisher/710-merry-fisher-1095-fly'],
 'J_NC895':['https://www.jeanneau.com/en-us/boats/powerboat/41-nc-weekender/103-nc-895'],
}

def gallon_l(l): return round(l/3.78541,1)

def ev(m,src,status='Reviewed',unresolved=None, notes='Factory and model-specific documentation support identity and representative specifications.'):
    unresolved=list(unresolved or [])
    ap={'Scope':'Model','Models':[m['BoatModelID']],'Years':{'From':m.get('FirstYear'),'To':m.get('LastYear')},'Variations':[]}
    m['EvidenceSummary']={
      'KnowledgeCoverage':'Strong' if status=='Reviewed' else 'Partial',
      'EvidenceQuality':'Moderate' if src else 'Low',
      'Statements':[
        {'Scope':'IdentityAndDimensions','AppliesTo':deepcopy(ap),'EvidenceRefs':src,'EvidenceTypes':['Factory documented'],'Confidence':'High' if status=='Reviewed' else 'Moderate','Notes':notes},
        {'Scope':'OverviewAndSuitability','AppliesTo':deepcopy(ap),'EvidenceRefs':src,'EvidenceTypes':['Factory documented'],'Confidence':'Moderate','Notes':'Guidance is derived from documented layout, hull form, propulsion and dimensions.'},
        {'Scope':'InspectionFocus','AppliesTo':dict(ap,Scope='Model family'),'EvidenceRefs':src,'EvidenceTypes':['Factory documented','Technical or survey source'],'Confidence':'Moderate','Notes':'Inspection guidance reflects configuration and age exposure; it is not a claim that every hull has a defect.'}
      ],
      'UnresolvedInformation':unresolved+['Legacy CommonProblems were not promoted to KnownConcerns without model-specific evidence meeting the approved threshold.']
    }
    m.update(ResearchStatus=status,DataConfidence='Moderate' if status=='Reviewed' else 'Low',ReviewedBy='B-Atlas Phase 8C-14 French Production Research',LastUpdated=today,Revision=(m.get('Revision') or 1)+1)

def common_suit(m, longrange=False):
    beam=m.get('Beam_ft') or 99
    return {
      'CoupleCruising':{'Assessment':'Good','Summary':'The enclosed helm and documented accommodation support weekend or extended couple cruising.'},
      'SoloHandling':{'Assessment':'Good' if (m.get('LOA_ft') or 99)<35 else 'Mixed','Summary':'Side-door access and good visibility help; docking burden rises with size, windage and twin-engine/flybridge configuration.'},
      'InlandWaterways':{'Assessment':'Good' if beam<=12 else 'Mixed','Summary':'The enclosed cruising layout works well on inland routes; beam and air draft must be checked against route restrictions.'},
      'ExposedWater':{'Assessment':'Good' if longrange else 'Mixed','Summary':'Factory CE ratings and hull form support coastal use; loading, weather and individual boat condition remain decisive.'}
    }

def norm(m,overview,strengths,trade,best,avoid,insp,vars,src,status='Reviewed',unresolved=None,longrange=False,owner=None):
    m['Overview']=overview;m['Suitability']=common_suit(m,longrange);m['Strengths']=strengths;m['TradeOffs']=trade;m['BestFor']=best;m['AvoidIf']=avoid;m['KnownConcerns']=[];m['InspectionFocus']=insp
    m['BuyerQuestions']=[f'What service, repair or inspection history is available for {x[0].lower()+x[1:]}?' for x in insp]
    m['OwnerActions']=owner or ['Keep windows, hatches, deck hardware and exterior penetrations sealed','Maintain propulsion, cooling, exhaust, steering and electrical systems to documented intervals','Document machinery and system upgrades for future survey and resale']
    m['ModelVariations']=vars
    ev(m,src,status,unresolved)
    m['ResearchNotes']='\n\n'.join(x for x in [f'Phase 8C-14 French production normalization {today}.',(m.get('ResearchNotes') or '').strip()] if x)

# redirects/consolidations
redirects_path=os.path.join(root,'data','model-id-redirects.json')
try: redirects=json.load(open(redirects_path,encoding='utf-8'))
except: redirects={}
def add_redirect(a,b):
    global redirects
    if isinstance(redirects,list): redirects.append({'From':a,'To':b,'Reason':'Phase 8C-14 identity consolidation'})
    else: redirects[a]=b

# remove duplicate Beneteau Swift Trawler 34 and duplicate Jeanneau market-name records
for old,new in [('BENE-34-ST','BENE-34-SW'),('JEAU-NC895','JEAU-895'),('JEAU-NC1095','JEAU-1095')]:
    rec=next((x for x in models if x.get('BoatModelID')==old),None)
    if rec: models.remove(rec); add_redirect(old,new)

for m in models:
    bid=m['BoatModelID']; maker=m.get('Manufacturer')
    if maker=='Beneteau':
      m['ManufacturerID']='BENE'
      m['KnownConcerns']=[]
      if bid=='BENE-30-SW':
        m.update(Model='Swift Trawler 30',Variant='Flybridge',Nickname='Beneteau Swift Trawler 30',FirstYear=2016,LastYear=2020,LOA_ft=32.78,Beam_ft=11.58,Draft_ft=3.42,Displacement_lb=13224,Fuel='Diesel',NormalizedFuel='Diesel',EngineConfiguration='Single Cummins diesel inboard',EngineCount=1,Propulsion='Shaft',NormalizedPropulsion='Shaft',Flybridge='Yes',AftCabin='No',FuelCapacity=190,WaterCapacity=80,HoldingCapacity=23,Cabins=1,Berths=6,Heads=1,Shower=True,NormalizedHullForm='Semi-Displacement',NormalizedStyle='Trawler',Configuration='Flybridge Trawler')
        norm(m,'The Beneteau Swift Trawler 30 is a compact flybridge passagemaker-style cruiser built around a semi-planing hull, single diesel shaft drive and a bright deck-saloon layout. It combines displacement-speed economy with the ability to cruise substantially faster when required.',['Single diesel shaft drive simplifies machinery compared with larger twin-engine Swift Trawlers','Flybridge plus lower helm provide flexible all-weather operation','Compact dimensions retain useful long-cruise accommodation'],['Flybridge adds windage and air draft','Fast-cruise capability comes with higher fuel burn than displacement operation','One-cabin layout is less private for extended guest cruising'],['Couples wanting a compact long-range cruising layout','Great Loop and inland/coastal cruising','Buyers wanting single-diesel simplicity with flybridge visibility'],['You require two private sleeping cabins','You need low bridge clearance without flybridge windage','You want true full-displacement behavior only'],['Inspect flybridge structure, helm controls and weather exposure','Inspect single-diesel cooling, exhaust, shaft and stern gear','Inspect saloon windows, side door and deck penetrations for leaks','Inspect fuel, water, sanitation and electrical systems'],[],SRC['BENE_ST30'],unresolved=['Exact end of production varies by market/model year documentation.'],longrange=True)
      elif bid=='BENE-34-SW':
        m.update(Model='Swift Trawler 34',Variant='Flybridge or Sedan',Nickname='Beneteau Swift Trawler 34',FirstYear=2009,LastYear=2016,LOA_ft=36.02,Beam_ft=13.12,Draft_ft=3.25,Displacement_lb=16350,Fuel='Diesel',NormalizedFuel='Diesel',EngineConfiguration='Single diesel inboard',EngineCount=1,Propulsion='Shaft',NormalizedPropulsion='Shaft',Flybridge='Optional',AftCabin='No',FuelCapacity=211,WaterCapacity=84,HoldingCapacity=24,Cabins=2,Berths=6,Heads=1,Shower=True,NormalizedHullForm='Semi-Displacement',NormalizedStyle='Trawler',Configuration='Flybridge or Sedan Trawler')
        norm(m,'The Beneteau Swift Trawler 34 is a semi-displacement cruising boat offered with or without a flybridge. Its asymmetrical deck layout, single diesel shaft drive and broad speed range made it one of the defining early Swift Trawler models.',['Single diesel shaft propulsion','Available in flybridge and non-flybridge configurations','Useful two-cabin cruising accommodation','Broad operating-speed range'],['Asymmetrical side-deck arrangement favors one side for circulation','Flybridge examples carry substantially more air draft','Semi-displacement performance is less economical at speed than slow displacement cruising'],['Couples seeking a practical Great Loop or coastal cruiser','Buyers wanting a single diesel with two cabins','Owners choosing between low-air-draft sedan and flybridge visibility'],['You require symmetrical wide side decks','You need very low air draft in flybridge form','You expect full-displacement fuel economy at all speeds'],['Confirm flybridge versus non-flybridge factory configuration','Inspect single diesel, shaft, exhaust and cooling systems','Inspect asymmetric side deck, railings, deck hardware and windows','Review flybridge or roof structure for water intrusion','Verify air draft for the actual configuration'],[{'Name':'Flybridge or non-flybridge versions','Description':'Beneteau offered the Swift Trawler 34 with or without an upper helm/flybridge.','AffectedYears':'Production run','EvidenceRefs':SRC['BENE_ST34'],'Confidence':'High'}],SRC['BENE_ST34'],longrange=True)
      elif bid=='BENE-35-SW':
        m.update(Model='Swift Trawler 35',Variant='Flybridge',Nickname='Beneteau Swift Trawler 35',FirstYear=2017,LastYear=2024,LOA_ft=37.04,Beam_ft=13.22,Draft_ft=3.83,Displacement_lb=18187,Fuel='Diesel',NormalizedFuel='Diesel',EngineConfiguration='Single Cummins 425 hp diesel inboard',EngineCount=1,Propulsion='Shaft',NormalizedPropulsion='Shaft',Flybridge='Yes',AftCabin='No',FuelCapacity=211,WaterCapacity=80,HoldingCapacity=23,Cabins=2,Berths=6,Heads=1,Shower=True,NormalizedHullForm='Semi-Displacement',NormalizedStyle='Trawler',Configuration='Flybridge Trawler')
        norm(m,'The Beneteau Swift Trawler 35 succeeded the 34 with a more contemporary two-cabin interior while retaining single-diesel shaft propulsion, semi-planing hull form and a substantial flybridge. It is aimed at extended family or couple cruising rather than low-speed trawler operation alone.',['Single-diesel shaft propulsion','Two private cabins in a relatively compact hull','Large flybridge and enclosed lower helm','Semi-planing hull permits both economical slow cruise and faster passages'],['13-foot-plus beam increases slip and haul-out requirements','Flybridge creates significant air draft and exterior exposure','Systems complexity is higher than on simpler traditional trawlers'],['Couples or small families undertaking extended cruising','Great Loop and coastal cruising where beam is acceptable','Buyers wanting a modern single-engine flybridge cruiser'],['Your marina or storage limit is near 12 feet of beam','You need low bridge clearance','You prefer minimal systems and exterior equipment'],['Inspect flybridge deck, seating bases and helm penetrations','Inspect Cummins cooling, exhaust, shaft and stern gear','Inspect deckhouse glazing and side door seals','Review sanitation, electrical, heating and charging systems'],[],SRC['BENE_ST35'],unresolved=['Production end year varies by market as the model transitioned out of the range.'],longrange=True)
      elif bid=='BENE-47':
        m.update(Model='Swift Trawler 47',Variant='Flybridge',Nickname='Beneteau Swift Trawler 47',FirstYear=2019,LastYear=2022,LOA_ft=48.36,Beam_ft=14.76,Draft_ft=3.83,Displacement_lb=27780,Fuel='Diesel',NormalizedFuel='Diesel',EngineConfiguration='Twin Cummins diesel inboards',EngineCount=2,Propulsion='Shaft',NormalizedPropulsion='Shaft',Flybridge='Yes',AftCabin='No',FuelCapacity=580,WaterCapacity=169,HoldingCapacity=None,Cabins=3,Berths=6,Heads=2,Shower=True,NormalizedHullForm='Semi-Displacement',NormalizedStyle='Trawler',Configuration='Flybridge Trawler')
        norm(m,'The Beneteau Swift Trawler 47 is a three-cabin flybridge cruiser designed for faster long-distance family cruising. Twin diesels, broad side decks and a large flybridge make it substantially more capable and more complex than the smaller single-engine Swift Trawlers.',['Three-cabin family cruising layout','Twin-diesel redundancy and maneuverability','Large flybridge and practical side decks','Large fuel capacity supports extended passages'],['Twin machinery and larger systems increase ownership cost','Nearly 15-foot beam requires larger slips and haul-out facilities','Flybridge air draft limits some inland routes'],['Families or couples wanting substantial long-range accommodation','Coastal and Great Lakes cruising with larger marina infrastructure','Owners comfortable maintaining twin diesels and yacht-scale systems'],['You need compact slips or economical haul-out','You require low air draft','You want single-engine mechanical simplicity'],['Inspect both engines, shafts, exhausts and cooling systems','Inspect flybridge structure, electronics and helm controls','Inspect side doors, glazing and deck penetrations','Review generator, charging, sanitation and domestic systems'],[],SRC['BENE_ST47'],unresolved=['Holding-tank capacity should be verified by model year and market.'],longrange=True)
      elif bid=='BENE-48':
        m.update(Model='Swift Trawler 48',Variant='Flybridge',Nickname='Beneteau Swift Trawler 48',FirstYear=2022,LastYear=None,LOA_ft=48.36,Beam_ft=14.76,Draft_ft=3.77,AirDraft_ft=19.0,Displacement_lb=27896,Fuel='Diesel',NormalizedFuel='Diesel',EngineConfiguration='Twin Cummins QSB 6.7 diesels',EngineCount=2,Propulsion='Shaft',NormalizedPropulsion='Shaft',Flybridge='Yes',AftCabin='No',FuelCapacity=510,WaterCapacity=169,HoldingCapacity=None,Cabins=3,Berths=6,Heads=2,Shower=True,NormalizedHullForm='Semi-Displacement',NormalizedStyle='Trawler',Configuration='Flybridge Trawler')
        norm(m,'The Beneteau Swift Trawler 48 is a modern three-cabin flybridge passagemaker-style cruiser with twin shaft-drive Cummins diesels and a semi-planing hull. Factory data emphasizes long-range operation at displacement speeds while retaining cruising speeds around the high teens.',['Three-cabin accommodation with two heads','Large 510-gallon fuel capacity','Twin shaft-drive diesels','Factory-documented efficient displacement and fast-cruise operating modes'],['19-foot bridge clearance is a major inland-route constraint','Twin diesel and yacht-scale systems raise maintenance cost','14-foot-9-inch beam requires substantial marina infrastructure'],['Extended family coastal and Great Lakes cruising','Owners wanting modern passagemaker comfort with speed reserve','Buyers with marina access for a 48-foot yacht'],['Your route has restrictive bridge clearance','You need compact slips or economical storage','You prefer single-engine simplicity'],['Inspect twin Cummins engines, shafts, cooling and exhaust','Inspect flybridge structure, T-top options and exposed systems','Inspect side door, glazing and roof penetrations','Review generator, battery, charging, sanitation and domestic systems'],[],SRC['BENE_ST48'],longrange=True)
      elif bid=='BENE-52':
        m.update(Model='Swift Trawler 52',Variant='Flybridge',Nickname='Beneteau Swift Trawler 52',FirstYear=2008,LastYear=2012,LOA_ft=55.77,Beam_ft=16.14,Draft_ft=3.94,AirDraft_ft=21.0,Displacement_lb=45173,Fuel='Diesel',NormalizedFuel='Diesel',EngineConfiguration='Twin diesel inboards up to 600 hp each',EngineCount=2,Propulsion='Shaft',NormalizedPropulsion='Shaft',Flybridge='Yes',AftCabin='No',FuelCapacity=1057,WaterCapacity=211,HoldingCapacity=None,Cabins=3,Berths=6,Heads=2,Shower=True,NormalizedHullForm='Semi-Displacement',NormalizedStyle='Trawler',Configuration='Large Flybridge Trawler')
        norm(m,'The Beneteau Swift Trawler 52 is an early large flagship of the Swift Trawler family, combining a 55-foot overall envelope, twin diesels, large tankage and a substantial flybridge. It is a yacht-scale cruising platform rather than a compact trawler.',['Very large fuel and water capacities','Three-cabin long-range accommodation','Twin-diesel propulsion and substantial flybridge','High cruising capability for a trawler-style yacht'],['16-foot-plus beam and 21-foot air draft impose major infrastructure limits','Large twin-diesel systems carry high operating and maintenance costs','Older examples now require age-sensitive inspection of complex domestic systems'],['Experienced owners seeking large-volume long-distance cruising','Families needing three cabins and substantial tankage','Buyers with yacht-scale dockage and service access'],['You need inland-route bridge flexibility','You have compact marina or haul-out limits','You want low-cost simple ownership'],['Inspect twin engines, shafts, fuel and exhaust systems','Inspect flybridge and deckhouse for weather exposure and leaks','Review generator, chargers, batteries and AC/DC distribution','Inspect tanks, sanitation and domestic water systems','Verify bridge clearance with antennas and electronics'],[],SRC['BENE_ST52'],unresolved=['Exact production years should be cross-checked against hull documentation; 2008–2012 is retained as representative production-era guidance.'],longrange=True)
      elif bid.startswith('BENE-ANT'):
        if bid=='BENE-ANT-7': m.update(Model='Antares 7',Variant='Pilothouse Outboard',Nickname='Beneteau Antares 7',LOA_ft=24.54,Beam_ft=8.30,Fuel='Gasoline',NormalizedFuel='Gasoline',Propulsion='Outboard',NormalizedPropulsion='Outboard',EngineConfiguration='Single outboard',EngineCount=1,Flybridge='No',AftCabin='No',NormalizedHullForm='Planing',NormalizedStyle='Cruiser',Configuration='Pilothouse Outboard Cruiser')
        elif bid=='BENE-ANT-8': m.update(Model='Antares 8',Variant='Pilothouse Outboard',Nickname='Beneteau Antares 8',LOA_ft=27.0,Beam_ft=9.15,Fuel='Gasoline',NormalizedFuel='Gasoline',Propulsion='Outboard',NormalizedPropulsion='Outboard',EngineConfiguration='Single outboard',EngineCount=1,Flybridge='No',AftCabin='No',NormalizedHullForm='Planing',NormalizedStyle='Cruiser',Configuration='Pilothouse Outboard Cruiser')
        elif bid=='BENE-ANT-9': m.update(Model='Antares 9',Variant='Pilothouse Outboard',Nickname='Beneteau Antares 9',LOA_ft=29.92,Beam_ft=9.81,Fuel='Gasoline',NormalizedFuel='Gasoline',Propulsion='Outboard',NormalizedPropulsion='Outboard',EngineConfiguration='Twin outboards',EngineCount=2,Flybridge='No',AftCabin='No',NormalizedHullForm='Planing',NormalizedStyle='Cruiser',Configuration='Pilothouse Outboard Cruiser')
        elif bid=='BENE-ANT-11': m.update(Model='Antares 11',Variant='Coupe',Nickname='Beneteau Antares 11 Coupe',FirstYear=2020,LastYear=None,LOA_ft=36.58,Beam_ft=11.52,Draft_ft=2.59,AirDraft_ft=10.75,Displacement_lb=13451,Fuel='Gasoline',NormalizedFuel='Gasoline',Propulsion='Outboard',NormalizedPropulsion='Outboard',EngineConfiguration='Twin outboards up to 300 hp each',EngineCount=2,Flybridge='No',AftCabin='No',FuelCapacity=212,WaterCapacity=53,Cabins=2,Berths=5,Heads=1,Shower=True,NormalizedHullForm='Planing',NormalizedStyle='Cruiser',Configuration='Coupe Outboard Cruiser')
        src=SRC['BENE_ANT11'] if bid=='BENE-ANT-11' else SRC['BENE_ANT']
        norm(m,f"The {m['Nickname']} is a French enclosed-pilothouse outboard cruiser designed for short coastal trips, fishing and weekend use. The Antares range prioritizes visibility, sheltered helm operation and practical cockpit access rather than traditional trawler-speed efficiency.",['Protected pilothouse helm','Outboard propulsion simplifies engine access and winterization','Practical cockpit and side-deck access for coastal use'],['Planing-speed operation uses substantially more fuel than displacement cruising','Outboard installations occupy transom space','Accommodation and tankage are modest relative to trawler-style cruisers of similar overall length'],['Weekend coastal cruising','Owners wanting enclosed outboard operation','Fishing and family day use with occasional overnighting'],['You primarily cruise at 6–8 knots for maximum economy','You require large long-range tankage','You want shaft-drive diesel propulsion'],['Inspect outboard service history, mounting and steering','Inspect pilothouse windows, doors and roof penetrations','Inspect cockpit drainage and transom structure','Verify tankage, sleeping layout and fitted sanitation equipment'],[],src,unresolved=['Production years and exact tankage vary by Antares generation; verify the individual model year.'],longrange=False)
      elif bid.startswith('BENE-BAR'):
        if bid=='BENE-BAR-8': m.update(Model='Barracuda 8',Variant='Sport Fishing Pilothouse',Nickname='Beneteau Barracuda 8',LOA_ft=26.21,Beam_ft=9.19,Displacement_lb=5830,Fuel='Gasoline',NormalizedFuel='Gasoline',FuelCapacity=74,WaterCapacity=26,Propulsion='Outboard',NormalizedPropulsion='Outboard',EngineConfiguration='Single or twin outboards; 300 hp maximum total',EngineCount=None,Flybridge='Optional',AftCabin='No',NormalizedHullForm='Planing',NormalizedStyle='Sport Fisher',Configuration='Walkaround Pilothouse Sport Fisher')
        else: m.update(Model='Barracuda 9',Variant='Sport Fishing Pilothouse',Nickname='Beneteau Barracuda 9',LOA_ft=29.86,Beam_ft=9.78,Displacement_lb=9784,Fuel='Gasoline',NormalizedFuel='Gasoline',FuelCapacity=106,WaterCapacity=26,Propulsion='Outboard',NormalizedPropulsion='Outboard',EngineConfiguration='Twin outboards up to 250 hp each',EngineCount=2,Flybridge='Optional',AftCabin='No',NormalizedHullForm='Planing',NormalizedStyle='Sport Fisher',Configuration='Walkaround Pilothouse Sport Fisher')
        src=SRC['BENE_BAR8'] if bid.endswith('-8') else SRC['BENE_BAR9']
        norm(m,f"The {m['Nickname']} is an enclosed walkaround sport-fishing cruiser from Beneteau's Barracuda line. Its planing hull, outboard propulsion, broad cockpit and optional upper helm on some versions emphasize fishing versatility and all-weather day use rather than displacement-speed passagemaking.",['Protected pilothouse with strong exterior access','Fishing-oriented cockpit and deck layout','Outboard propulsion and planing performance'],['Accommodation is secondary to fishing and deck space','Optional flybridge adds air draft and exposure','Fuel use at planing speeds exceeds slow-cruiser expectations'],['Fishing-focused coastal owners','All-weather day boating','Buyers wanting a practical outboard pilothouse'],['You need large private cabins for extended cruising','You primarily want economical displacement-speed operation','You require diesel shaft propulsion'],['Inspect outboard installation, steering and service history','Inspect cockpit drainage, fishboxes and deck hardware','Inspect pilothouse doors/windows and optional flybridge penetrations','Verify actual engine count and options on the individual boat'],[{'Name':'Configuration options','Description':'Barracuda models were offered in multiple deck/door layouts; flybridge and engine count can vary by version.','AffectedYears':'Production run','EvidenceRefs':src,'Confidence':'High'}],src,longrange=False)

    elif maker=='Jeanneau':
      m['ManufacturerID']='JEAU'; m['KnownConcerns']=[]
      if bid=='JEAU-605':
        m.update(Model='Merry Fisher 605',Variant='Pilothouse Outboard',Nickname='Jeanneau Merry Fisher 605',LOA_ft=19.0,Beam_ft=8.07,Draft_ft=1.41,Displacement_lb=2381,FuelCapacity=26.4,WaterCapacity=5.3,Fuel='Gasoline',NormalizedFuel='Gasoline',Propulsion='Outboard',NormalizedPropulsion='Outboard',EngineConfiguration='Single outboard',EngineCount=1,Flybridge='No',AftCabin='No',Cabins=1,Berths=3,Heads=0,NormalizedHullForm='Planing',NormalizedStyle='Cruiser',Configuration='Compact Pilothouse Outboard Cruiser')
        src=SRC['J_MF605']
      elif bid=='JEAU-635':
        m.update(Model='Merry Fisher 635',Variant='Pilothouse',Nickname='Jeanneau Merry Fisher 635',LOA_ft=21.0,Beam_ft=None,Draft_ft=1.31,Displacement_lb=2601,FuelCapacity=35.9,Fuel='Gasoline',NormalizedFuel='Gasoline',Propulsion='Outboard',NormalizedPropulsion='Outboard',EngineConfiguration='Single outboard typical',EngineCount=1,Flybridge='No',AftCabin='No',Cabins=1,Berths=2,Heads=0,NormalizedHullForm='Planing',NormalizedStyle='Cruiser',Configuration='Compact Pilothouse Cruiser'); src=SRC['J_MF635']
      elif bid=='JEAU-695':
        m.update(Model='Merry Fisher 695',Variant='Pilothouse Outboard',Nickname='Jeanneau Merry Fisher 695',Flybridge='No',AftCabin='No',Fuel='Gasoline',NormalizedFuel='Gasoline',Propulsion='Outboard',NormalizedPropulsion='Outboard',EngineCount=1,EngineConfiguration='Single outboard',NormalizedHullForm='Planing',NormalizedStyle='Cruiser',Configuration='Pilothouse Outboard Cruiser'); src=SRC['J_RANGE']
      elif bid=='JEAU-795':
        m.update(Model='Merry Fisher 795',Variant='Pilothouse Outboard',Nickname='Jeanneau Merry Fisher 795',Flybridge='No',AftCabin='No',Fuel='Gasoline',NormalizedFuel='Gasoline',Propulsion='Outboard',NormalizedPropulsion='Outboard',EngineCount=1,EngineConfiguration='Single outboard typical',NormalizedHullForm='Planing',NormalizedStyle='Cruiser',Configuration='Pilothouse Outboard Cruiser'); src=SRC['J_RANGE']
      elif bid=='JEAU-855':
        m.update(Model='Merry Fisher 855',Variant='Pilothouse Outboard',Nickname='Jeanneau Merry Fisher 855',LOA_ft=28.61,Beam_ft=9.81,Draft_ft=1.84,Displacement_lb=6393,FuelCapacity=105.7,WaterCapacity=26.4,Fuel='Gasoline',NormalizedFuel='Gasoline',Propulsion='Outboard',NormalizedPropulsion='Outboard',EngineCount=2,EngineConfiguration='Twin outboards',Flybridge='No',AftCabin='No',Cabins=2,Berths=4,Heads=1,Shower=True,NormalizedHullForm='Planing',NormalizedStyle='Cruiser',Configuration='Two-Cabin Pilothouse Outboard Cruiser'); src=SRC['J_MF855']
      elif bid=='JEAU-895':
        m.update(Model='Merry Fisher 895',Variant='Pilothouse Outboard',Nickname='Jeanneau Merry Fisher 895 / NC 895',FirstYear=2017,LastYear=None,LOA_ft=29.75,Beam_ft=9.75,Draft_ft=2.07,Displacement_lb=8695,FuelCapacity=158.5,WaterCapacity=42.3,Fuel='Gasoline',NormalizedFuel='Gasoline',Propulsion='Outboard',NormalizedPropulsion='Outboard',EngineCount=2,EngineConfiguration='Twin outboards up to 200 hp each',Flybridge='No',AftCabin='No',Cabins=2,Berths=6,Heads=1,Shower=True,NormalizedHullForm='Planing',NormalizedStyle='Cruiser',Configuration='Two-Cabin Pilothouse Outboard Cruiser'); src=[*SRC['J_MF895'],*SRC['J_NC895']]
      elif bid=='JEAU-895-SP':
        m.update(Model='Merry Fisher 895 Sport',Variant='Sport Pilothouse',Nickname='Jeanneau Merry Fisher 895 Sport',Flybridge='No',AftCabin='No',Fuel='Gasoline',NormalizedFuel='Gasoline',Propulsion='Outboard',NormalizedPropulsion='Outboard',EngineCount=2,EngineConfiguration='Twin outboards',NormalizedHullForm='Planing',NormalizedStyle='Sport Fisher',Configuration='Walkaround Sport Pilothouse'); src=SRC['J_RANGE']
      elif bid=='JEAU-1095':
        m.update(Model='Merry Fisher 1095 Coupé',Variant='Coupé',Nickname='Jeanneau Merry Fisher 1095 Coupé / NC 1095',FirstYear=2018,LastYear=None,LOA_ft=34.45,Beam_ft=11.06,Draft_ft=2.26,Displacement_lb=10225,FuelCapacity=211.3,WaterCapacity=42.3,Fuel='Gasoline',NormalizedFuel='Gasoline',Propulsion='Outboard',NormalizedPropulsion='Outboard',EngineCount=2,EngineConfiguration='Twin outboards',Flybridge='No',AftCabin='No',Cabins=3,Berths=6,Heads=1,Shower=True,NormalizedHullForm='Planing',NormalizedStyle='Cruiser',Configuration='Three-Cabin Pilothouse Outboard Cruiser'); src=SRC['J_MF1095']
      elif bid=='JEAU-1095-FLY':
        m.update(Model='Merry Fisher 1095 Fly',Variant='Flybridge',Nickname='Jeanneau Merry Fisher 1095 Fly / NC 1095 Fly',FirstYear=2020,LastYear=None,LOA_ft=34.28,Beam_ft=11.06,Draft_ft=2.26,Displacement_lb=11685,FuelCapacity=211.3,WaterCapacity=68.7,Fuel='Gasoline',NormalizedFuel='Gasoline',Propulsion='Outboard',NormalizedPropulsion='Outboard',EngineCount=2,EngineConfiguration='Twin outboards',Flybridge='Yes',AftCabin='No',Cabins=3,Berths=6,Heads=1,Shower=True,NormalizedHullForm='Planing',NormalizedStyle='Cruiser',Configuration='Three-Cabin Flybridge Outboard Cruiser'); src=SRC['J_MF1095F']
      else: continue
      # generic Jeanneau editorial fields
      is_sport='Sport' in m.get('Model','')
      overview=f"The {m['Nickname']} is a French enclosed {'walkaround sport' if is_sport else 'family'} cruiser from Jeanneau's Merry Fisher/NC family. It uses outboard propulsion and a planing hull, with emphasis on protected helm visibility, flexible cockpit space and compact weekend accommodation."
      strengths=['Protected pilothouse helm and strong visibility','Outboard propulsion simplifies engine access and replacement','Practical cockpit-to-saloon connection']
      if (m.get('Cabins') or 0)>=2: strengths.append('Multiple cabins provide unusually useful accommodation for the length')
      trade=['Planing-speed fuel use is higher than displacement trawlers','Outboards occupy transom space and place machinery outside the hull','Tankage and storage are more weekend-oriented than long-range trawler layouts']
      best=['Weekend and short coastal cruising','Owners wanting enclosed outboard operation','Family day use with occasional overnighting']
      if is_sport: best[2]='Fishing and watersports with protected pilothouse shelter'
      avoid=['You primarily cruise at displacement speed for maximum economy','You require diesel shaft propulsion','You need traditional trawler-scale tankage']
      insp=['Inspect outboard service history, transom mounting and steering','Inspect pilothouse windows, side doors, roof hatches and deck penetrations','Inspect cockpit drains, sliding seating and exterior hardware','Verify actual tankage, sleeping layout and optional equipment']
      vars=[]
      unresolved=['Exact production end and generation-specific specifications should be verified by model year.']
      if bid=='JEAU-895': vars.append({'Name':'Merry Fisher / NC market naming','Description':'The same core 895 design is marketed as Merry Fisher 895 in many markets and NC 895 in North America; market equipment can differ.','AffectedYears':'Production run','EvidenceRefs':src,'Confidence':'High'})
      if bid=='JEAU-1095': vars.append({'Name':'Merry Fisher / NC market naming','Description':'The same core 1095 coupe design is marketed under Merry Fisher and NC naming by market; the Fly is a distinct upper-helm variant.','AffectedYears':'Production run','EvidenceRefs':src,'Confidence':'High'})
      if bid=='JEAU-1095-FLY': vars.append({'Name':'Original and Series 2','Description':'Jeanneau introduced the 1095 Fly for the 2020 season and later released a Series 2 evolution with revised hull and deck features.','AffectedYears':'2020 onward','EvidenceRefs':src,'Confidence':'High'})
      norm(m,overview,strengths,trade,best,avoid,insp,vars,src,'Reviewed',unresolved,longrange=False)

# write redirects
json.dump(redirects,open(redirects_path,'w',encoding='utf-8'),indent=2,ensure_ascii=False);open(redirects_path,'a').write('\n')
# update schema release
sp=os.path.join(root,'data','model-schema.json')
s=json.load(open(sp,encoding='utf-8')); s['schemaVersion']=max(int(s.get('schemaVersion',0)),14); s['release']='v6.11-phase8c14-french-production-normalized'; s['status']='Phase 8C-14 French production cruiser normalization completed';json.dump(s,open(sp,'w',encoding='utf-8'),indent=2,ensure_ascii=False);open(sp,'a').write('\n')
# write models
json.dump(models,open(p,'w',encoding='utf-8'),indent=2,ensure_ascii=False);open(p,'a').write('\n')
# report
xs=[m for m in models if m.get('Manufacturer') in ['Beneteau','Jeanneau']]
report={'phase':'8C-14','date':today,'families':['Beneteau','Jeanneau'],'canonicalRecords':len(xs),'totalModelCount':len(models),'reviewed':sum(m.get('ResearchStatus')=='Reviewed' for m in xs),'initial':sum(m.get('ResearchStatus')=='Initial' for m in xs),'consolidated':[{'From':'BENE-34-ST','To':'BENE-34-SW','Reason':'Duplicate Swift Trawler 34 identity'},{'From':'JEAU-NC895','To':'JEAU-895','Reason':'NC 895 is North American market naming for Merry Fisher 895 platform'},{'From':'JEAU-NC1095','To':'JEAU-1095','Reason':'NC 1095 is North American market naming for Merry Fisher 1095 platform'}],'knownConcernsPromoted':0}
os.makedirs(os.path.join(root,'developer/reports'),exist_ok=True)
rp=os.path.join(root,'developer/reports/phase8c14-french-production-normalization.json');json.dump(report,open(rp,'w',encoding='utf-8'),indent=2);open(rp,'a').write('\n')
open(os.path.join(root,'developer/reports/PHASE_8C14_FRENCH_PRODUCTION_NORMALIZATION.md'),'w',encoding='utf-8').write(f"# Phase 8C-14 — French production cruisers\n\nNormalized Beneteau and Jeanneau.\n\n- Canonical records: {len(xs)}\n- Reviewed: {report['reviewed']}\n- Initial: {report['initial']}\n- Duplicate/market-name identities consolidated: 3\n- KnownConcerns promoted: 0\n- Total B-Atlas models: {len(models)}\n")
print(json.dumps(report,indent=2))
