import json, os
from copy import deepcopy
root=os.path.abspath(os.path.join(os.path.dirname(__file__),'..'))
p=os.path.join(root,'boatmodels.json')
models=json.load(open(p,encoding='utf-8'))
today='2026-08-07'
fams=['Nimbus','Fjord','Saga','Nord Star','Greenline']
S={
'Nimbus3003':['https://www.devalk.nl/en/yachtbrokerage/52892/NIMBUS-3003.html','https://www.devalk.nl/en/yachtbrokerage/81320/NIMBUS-3003.html'],
'Nimbus365':['https://nimbus.se/boats/365-coupe/'],
'Fjord36Open':['https://fjordboats.com/us/historical-models/fjord-36-open/','https://lengersyachts.de/yachts/fjord-36-open-07/'],
'Fjord36Cruiser':['https://www.svb24.nl/ownersclub/fjord-36-cruiser.html'],
'Fjord40Open':['https://fjordboats.com/us/historical-models/fjord-40-open/','https://fjordboatsna.com/wp-content/uploads/2021/10/F40o.22_SPEC_20210702.pdf'],
'Fjord40Cruiser':['https://www.hanseyachtsag.com/mis/website/document/download/fjord-40-cruiser-brochure-2019-fjord-40-cruiser_-8772518759680315536.pdf','https://www.devalk.nl/en/yachtbrokerage/500843/FJORD-40-CRUISER.html'],
'Greenline33':['https://greenlinehybridnw.com/wp-content/uploads/GreenlineYachtsBrochure_GL-33_2022.pdf','https://www.greenlinesweden.se/17/9/greenline-33/'],
'Greenline39':['https://greenlinehybrid.ca/models/greenline39','https://www.boatingnz.co.nz/boat-reviews/greenline-39-hybrid/'],
'NordStar31':['https://nordstar.fi/nord-star-fleet/pilothouse-31-plus/'],
'Saga26':['https://www.boat.no/asp/boats/show.asp?id=16263&mid=90566','https://www.skippo.se/batar/batmarken/saga/26-ht']}

def evidence(m,src,status,unresolved):
 ap={'Scope':'Model','Models':[m['BoatModelID']],'Years':{'From':m.get('FirstYear'),'To':m.get('LastYear')},'Variations':[]}
 m['EvidenceSummary']={'KnowledgeCoverage':'Strong' if status=='Reviewed' else 'Partial','EvidenceQuality':'Moderate' if src else 'Low','Statements':[
 {'Scope':'IdentityAndDimensions','AppliesTo':deepcopy(ap),'EvidenceRefs':src,'EvidenceTypes':['Factory documented','Technical or survey source'],'Confidence':'High' if status=='Reviewed' else 'Moderate','Notes':'Identity and representative specifications are based on model-specific documentation.'},
 {'Scope':'OverviewAndSuitability','AppliesTo':deepcopy(ap),'EvidenceRefs':src,'EvidenceTypes':['Factory documented','Technical or survey source'],'Confidence':'Moderate','Notes':'Guidance is derived from documented layout, hull and propulsion characteristics.'},
 {'Scope':'InspectionFocus','AppliesTo':dict(ap,Scope='Model family'),'EvidenceRefs':src,'EvidenceTypes':['Technical or survey source'],'Confidence':'Moderate','Notes':'Inspection guidance addresses configuration and age risks and is not a claim of universal model defects.'}],
 'UnresolvedInformation':unresolved+['Legacy CommonProblems were not promoted to KnownConcerns without model-specific evidence meeting the approved threshold.']}
 m.update(ResearchStatus=status,DataConfidence='Moderate' if status=='Reviewed' else 'Low',ReviewedBy='B-Scout Phase 8C-13 Scandinavian Research',LastUpdated=today,Revision=(m.get('Revision') or 1)+1)

def suit(m,character='coastal'):
 return {'CoupleCruising':{'Assessment':'Good','Summary':'The documented accommodation and protected helm arrangement suit a cruising couple.'},'SoloHandling':{'Assessment':'Good' if (m.get('EngineCount')==1 and (m.get('LOA_ft') or 99)<=40) else 'Mixed','Summary':'Visibility is generally strong; docking burden depends on size, propulsion and fitted thrusters.'},'InlandWaterways':{'Assessment':'Good' if (m.get('Beam_ft') or 99)<=12 else 'Mixed','Summary':'Dimensions suit many inland routes, but air draft and speed-oriented propulsion remain route-specific.'},'ExposedWater':{'Assessment':'Good' if character in ['coastal','all-weather'] else 'Mixed','Summary':'Scandinavian designs emphasize protected operation, but model-specific CE category, loading and condition govern exposed-water suitability.'}}

def norm(m,overview,strengths,trade,best,avoid,insp,vars,src,status='Reviewed',unresolved=[]):
 m['Overview']=overview;m['Suitability']=suit(m,'all-weather' if m['Manufacturer'] in ['Nord Star','Nimbus'] else 'coastal');m['Strengths']=strengths;m['TradeOffs']=trade;m['BestFor']=best;m['AvoidIf']=avoid;m['KnownConcerns']=[];m['InspectionFocus']=insp;m['BuyerQuestions']=[f'What inspection, service or repair history is available for {x[0].lower()+x[1:]}?' for x in insp];m['OwnerActions']=['Keep windows, deck hardware, hatches and exterior penetrations sealed','Maintain propulsion, cooling, exhaust, steering and electrical systems to documented intervals','Document propulsion, battery and system upgrades for future survey and resale'];m['ModelVariations']=vars;evidence(m,src,status,unresolved)
 m['ResearchNotes']='\n\n'.join(x for x in [f'Phase 8C-13 Scandinavian normalization {today}.',(m.get('ResearchNotes') or '').strip()] if x)

# consolidate Greenline hybrid duplicate into canonical 33
hy=next((x for x in models if x.get('BoatModelID')=='GRNL-33-HY'),None)
if hy:
 models.remove(hy)
 redirects_path=os.path.join(root,'data','model-id-redirects.json')
 try: redirects=json.load(open(redirects_path,encoding='utf-8'))
 except: redirects={}
 if isinstance(redirects,list): redirects.append({'From':'GRNL-33-HY','To':'GRNL-33','Reason':'Greenline 33 Hybrid is a propulsion option/variant of Greenline 33, not a separate boat model.'})
 else: redirects['GRNL-33-HY']='GRNL-33'
 json.dump(redirects,open(redirects_path,'w',encoding='utf-8'),indent=2,ensure_ascii=False);open(redirects_path,'a').write('\n')

for m in models:
 if m.get('Manufacturer')=='Nimbus' and m['BoatModelID']=='NMBS-3003':
  m.update(Model='3003',Variant='Aft Cabin Coupe',Nickname='Nimbus 3003',FirstYear=1985,LastYear=1992,LOA_ft=30.18,Beam_ft=10.5,Draft_ft=2.79,AirDraft_ft=8.04,Displacement_lb=7937,Fuel='Diesel',NormalizedFuel='Diesel',EngineConfiguration='Single Volvo Penta diesel inboard typical',EngineCount=1,Propulsion='Shaft',NormalizedPropulsion='Shaft',Flybridge='No',AftCabin='Yes',FuelCapacity=74,WaterCapacity=45,HoldingCapacity=13,Berths=5,Cabins=2,Heads=1,Shower=True,HullType='Planing',NormalizedHullForm='Planing',NormalizedHullConfiguration='Monohull',NormalizedStyle='Cruiser',Configuration='Aft Cabin Coupe')
  norm(m,'The Nimbus 3003 is a Swedish aft-cabin coupe cruiser from the late 1980s and early 1990s. It combines a compact deep-V/planing hull, protected cockpit helm, single diesel shaft drive and unusually useful two-cabin accommodation for its length.',['Compact two-cabin layout with separate aft cabin','Single diesel shaft drive keeps propulsion relatively straightforward','Protected Scandinavian cockpit and helm suit shoulder-season cruising'],['Aft-cabin layout separates sleeping areas but constrains open-plan interior volume','Older examples require careful inspection of original systems and window/deck sealing','Planing-speed operation uses more fuel than displacement trawlers'],['Couples wanting a compact traditional Scandinavian cruiser','Inland and coastal cruising where protected helm comfort matters','Buyers valuing an aft cabin in roughly 30 feet'],['You require wide modern walkaround side decks','You want full-displacement economy at 6–8 knots','You need contemporary systems without age-related refit exposure'],['Inspect window frames, deck fittings and cockpit enclosure for leaks','Inspect diesel cooling, exhaust, shaft, stern gear and engine mounts','Inspect fuel, water and holding tanks and hoses','Review electrical and heating-system upgrades','Confirm actual draft and bridge clearance on the individual boat'],[{'Name':'Representative draft variation','Description':'Published examples report draft around 0.85–1.05 m; individual propeller/shaft and loading differences should be verified.','AffectedYears':'All','EvidenceRefs':S['Nimbus3003'],'Confidence':'Moderate'}],S['Nimbus3003'])
 if m.get('Manufacturer')=='Nimbus' and m['BoatModelID']=='NMBS-365-CO':
  m.update(Model='365 Coupé',Variant='Coupé',Nickname='Nimbus 365 Coupé',LOA_ft=37.92,Beam_ft=11.48,Draft_ft=3.74,AirDraft_ft=12.86,Displacement_lb=14090,FuelCapacity=185,WaterCapacity=71,HoldingCapacity=32,Berths=6,Cabins=2,Heads=1,Shower=True,Fuel='Diesel',NormalizedFuel='Diesel',EngineCount=1,EngineConfiguration='Single diesel shaft standard; twin diesel shaft options documented',Propulsion='Shaft',NormalizedPropulsion='Shaft',Flybridge='No',AftCabin='No',NormalizedHullForm='Planing',NormalizedHullConfiguration='Monohull',NormalizedStyle='Cruiser',Configuration='Coupé Cruiser')
  norm(m,'The Nimbus 365 Coupé is a Swedish all-weather family cruiser built around an enclosed deck saloon, two cabins and shaft-drive diesel propulsion. Factory documentation shows both single- and twin-engine options, making exact machinery configuration important when comparing individual boats.',['Excellent enclosed visibility and weather protection','Two-cabin layout supports extended couple or family cruising','Factory shaft-drive diesel choices avoid sterndrive dependence'],['Systems and accommodation are more complex than a compact single-cabin cruiser','Twin-engine examples increase maintenance burden and machinery-space crowding','Higher cruising speeds carry greater fuel use than displacement trawlers'],['Couples or families wanting an all-weather Scandinavian cruiser','Extended inland and coastal cruising','Owners prioritizing enclosed helm comfort and practical side access'],['You require a narrow trailerable boat','You want minimal systems and single-purpose simplicity','You primarily want 6–7-knot displacement economy'],['Confirm single- or twin-engine factory configuration','Inspect shaft seals, stern gear, cooling and exhaust systems','Inspect deck saloon windows, doors and roof openings for leakage','Review electrical, heating, hot-water and sanitation systems','Verify air draft with mast and antenna configuration'],[{'Name':'Engine alternatives','Description':'Factory specifications document both single D6 and twin D4 shaft-drive configurations with materially different weight and performance.','AffectedYears':'Production run','EvidenceRefs':S['Nimbus365'],'Confidence':'High'}],S['Nimbus365'])

# Fjord
for m in [x for x in models if x.get('Manufacturer')=='Fjord']:
 m.update(Fuel='Diesel',NormalizedFuel='Diesel',Flybridge='No',AftCabin='No',NormalizedHullForm='Planing',NormalizedHullConfiguration='Monohull',NormalizedStyle='Express Cruiser')
 if m['BoatModelID']=='FJRD-36-OPEN':
  m.update(Model='36 Open',Variant='Open',Nickname='Fjord 36 Open',FirstYear=2011,LastYear=2020,LOA_ft=35.43,Beam_ft=11.98,Draft_ft=2.95,AirDraft_ft=10.17,Displacement_lb=13228,FuelCapacity=158,WaterCapacity=42,HoldingCapacity=10,EngineCount=2,EngineConfiguration='Twin Volvo Penta D4 diesels',Propulsion='Sterndrive',NormalizedPropulsion='Sterndrive',Berths=2,Cabins=1,Heads=1,Shower=False,Configuration='Open Walkaround Day Cruiser')
  norm(m,'The Fjord 36 Open is a German-built Scandinavian-style walkaround day cruiser with a deep-V planing hull, large open deck and a compact overnight cabin. Its design prioritizes social deck space and high-speed coastal operation rather than traditional cruising volume.',['Exceptional open-deck circulation and social space','Deep-V planing performance with twin diesel sterndrives','Compact cabin, head and galley permit occasional overnight use'],['Limited enclosed living space for extended cruising','Twin diesels and sterndrives add maintenance complexity','Open layout provides less weather protection than a coupé cruiser'],['Day boating and fast coastal cruising','Owners prioritizing outdoor entertaining and walkaround access','Occasional overnight use rather than extended liveaboard cruising'],['You require an enclosed all-weather salon','You cruise primarily at displacement speeds','You want low-complexity single-engine propulsion'],['Inspect sterndrive service history, bellows and corrosion protection','Inspect teak/deck surfaces and hardware bedding','Inspect engine cooling, exhaust and fuel systems','Inspect cabin/head ventilation and plumbing','Confirm T-top, bimini and air-draft configuration'],[],S['Fjord36Open'])
 elif m['BoatModelID']=='FJRD-36':
  m.update(Model='36 Cruiser',Variant='Cruiser',Nickname='Fjord 36 Cruiser',FirstYear=2005,LastYear=2012,LOA_ft=35.43,Beam_ft=11.94,EngineCount=None,EngineConfiguration='Diesel inboard configuration requires hull-specific verification',Propulsion='Unknown',NormalizedPropulsion='Unknown',Configuration='Enclosed Cruiser')
  norm(m,'The Fjord 36 Cruiser is a less-common enclosed cruising variant associated with Fjord’s pre/Open-era 36-foot range. Surviving documentation confirms the model identity and principal dimensions, but machinery, accommodation and production details require individual-hull verification.',['Enclosed cruising layout provides more weather protection than an open dayboat','Approximately 36-foot size remains manageable for couple cruising','Scandinavian/German production heritage supports practical coastal use'],['Documentation is much thinner than for the 36 Open','Individual machinery and interior specifications require verification','Resale/search recognition is weaker than the better-known Open model'],['Buyers specifically seeking an enclosed Fjord in this size range','Coastal cruising where weather protection matters','Owners comfortable researching a less-common model'],['You need fully standardized factory specifications','You specifically want the open walkaround Fjord layout','You are unwilling to verify machinery and layout hull by hull'],['Confirm HIN/model designation and production year','Verify engine count, drive type and tank capacities','Inspect hull/deck structure and window sealing','Inspect propulsion, cooling, exhaust and steering systems','Verify accommodation and air draft'],[],S['Fjord36Cruiser'],'Initial',['Model identity is supported, but reliable factory-wide machinery and accommodation specifications remain incomplete.'])
 elif m['BoatModelID']=='FJRD-40-OPEN':
  m.update(Model='40 Open',Variant='Open',Nickname='Fjord 40 Open',FirstYear=2007,LastYear=2021,LOA_ft=39.34,Beam_ft=13.09,Draft_ft=3.44,Displacement_lb=22002,FuelCapacity=256,WaterCapacity=83,EngineCount=2,EngineConfiguration='Twin Volvo Penta IPS diesels',Propulsion='Pod',NormalizedPropulsion='Pod',Berths=2,Cabins=1,Heads=1,Shower=False,Configuration='Open Walkaround Day Cruiser')
  norm(m,'The Fjord 40 Open is the model that established Fjord’s modern walkaround dayboat identity. It combines a broad open deck, deep-V planing hull and twin Volvo Penta IPS diesels with a compact cabin for occasional overnight use.',['Large single-level walkaround deck and social cockpit','Twin IPS propulsion provides high-speed performance and joystick maneuvering','CE Category B documentation supports substantial coastal capability for the design type'],['Open layout sacrifices enclosed living volume and weather protection','Twin IPS systems increase service complexity and cost','Nearly 13-foot beam creates marina and storage implications'],['Fast coastal day boating and entertaining','Owners valuing distinctive walkaround access','Occasional overnighting with emphasis on deck space'],['You need an enclosed all-weather cruising salon','You want low-speed displacement economy','You want simple shaft-drive machinery'],['Inspect IPS service history, seals, corrosion protection and steering','Inspect deck structure, teak and hardware bedding','Inspect engine-room ventilation, cooling and exhaust systems','Inspect cabin/head plumbing and electrical systems','Verify T-top and air-draft configuration'],[],S['Fjord40Open'])
 elif m['BoatModelID']=='FJRD-40':
  m.update(Model='40 Cruiser',Variant='Cruiser',Nickname='Fjord 40 Cruiser',FirstYear=2007,LastYear=2018,LOA_ft=39.34,Beam_ft=13.09,Draft_ft=2.95,AirDraft_ft=11.48,Displacement_lb=20944,FuelCapacity=264,WaterCapacity=90,EngineCount=2,EngineConfiguration='Twin Volvo Penta IPS diesels',Propulsion='Pod',NormalizedPropulsion='Pod',Berths=4,Cabins=2,Heads=1,Shower=True,Configuration='Enclosed Express Cruiser')
  norm(m,'The Fjord 40 Cruiser is the enclosed companion to the early modern Fjord 40 Open. It retains the planing hull and twin IPS propulsion but adds a glass-enclosed salon and two-cabin accommodation for more weather-protected cruising.',['Enclosed one-level salon improves all-weather usability','Two cabins provide substantially more overnight capability than the Open','Twin IPS propulsion offers joystick maneuvering and strong performance'],['Twin IPS machinery is maintenance-intensive compared with a single shaft drive','Broad beam and high-speed systems increase ownership cost','Less open deck area than the 40 Open'],['Couples wanting Fjord styling with genuine enclosed cruising accommodation','Fast coastal cruising in mixed weather','Owners comfortable maintaining twin IPS systems'],['You want maximum open-deck dayboat space','You primarily cruise slowly for fuel economy','You want minimal propulsion complexity'],['Inspect IPS pods, steering, seals and corrosion protection','Inspect salon glazing, doors and roof penetrations','Inspect both diesels, cooling and exhaust systems','Inspect electrical, HVAC and sanitation systems','Confirm displacement and tankage for model year'],[],S['Fjord40Cruiser'])

# Greenline canonical 33 and 39
for m in [x for x in models if x.get('Manufacturer')=='Greenline']:
 m.update(Flybridge='No',AftCabin='No',EngineCount=1,NormalizedHullConfiguration='Monohull',NormalizedStyle='Cruiser',Configuration='Solar-Assisted Sedan Cruiser')
 if m['BoatModelID']=='GRNL-33':
  m.update(Model='33',Variant=None,Nickname='Greenline 33',FirstYear=2010,LastYear=2024,LOA_ft=32.78,Beam_ft=11.45,Draft_ft=2.3,AirDraft_ft=9.68,Displacement_lb=10582,FuelCapacity=132,WaterCapacity=79,HoldingCapacity=17,Berths=7,Cabins=1,Heads=1,Shower=True,Fuel='Diesel / Electric',NormalizedFuel='Diesel',EngineConfiguration='Single shaft drive; diesel, hybrid and electric propulsion options',Propulsion='Shaft',NormalizedPropulsion='Shaft',HullType='Superdisplacement / hybrid hull',NormalizedHullForm='Semi-Displacement')
  vars=[{'Name':'Propulsion options','Description':'Greenline 33 was offered with diesel-only, diesel-electric hybrid and later full-electric propulsion; these are propulsion variants of the same boat model rather than separate model identities.','AffectedYears':'Production run','EvidenceRefs':S['Greenline33'],'Confidence':'High'},{'Name':'Early versus later boats','Description':'Systems, solar capacity, battery technology and propulsion packages evolved materially during the long production run; exact equipment must be verified by year.','AffectedYears':'2010–2024','EvidenceRefs':S['Greenline33'],'Confidence':'Moderate'}]
  norm(m,'The Greenline 33 is a Slovenian solar-assisted sedan cruiser built around an efficient J&J-designed hull and single shaft line. It was offered in diesel, diesel-electric hybrid and later electric configurations; B-Scout treats those propulsion packages as variations of one model, not separate boat models.',['Very efficient hull at low-to-moderate cruising speeds','Large solar roof and household-style electrical concept support quiet anchoring','Single-level salon/cockpit arrangement creates unusually useful space for a 33-footer'],['Hybrid/electric versions add battery, inverter and control-system complexity','Propulsion and electrical specifications changed substantially over the production run','Wide cabin house produces asymmetric/limited side-deck compromises on some layouts'],['Couples seeking efficient inland and coastal cruising','Owners who value solar-supported house systems and quiet anchoring','Buyers comfortable understanding modern electrical systems'],['You want a mechanically simple traditional trawler','You need high-speed planing performance','You are unwilling to maintain lithium/hybrid/electrical systems where fitted'],['Verify diesel, hybrid or electric propulsion package and battery age','Inspect shaft, rudder, propeller-protection fins and stern gear','Inspect solar panels, inverters, chargers and battery-management systems','Inspect windows, doors and roof penetrations for leakage','Verify tankage and electrical configuration by production year'],vars,S['Greenline33'])
 elif m['BoatModelID']=='GRNL-39':
  m.update(Model='39',FirstYear=2017,LastYear=None,LOA_ft=39.34,Beam_ft=12.3,Draft_ft=2.95,AirDraft_ft=10.37,Displacement_lb=15432,FuelCapacity=185,WaterCapacity=106,HoldingCapacity=21,Berths=6,Cabins=2,Heads=1,Shower=True,Fuel='Diesel / Electric',NormalizedFuel='Diesel',EngineConfiguration='Single shaft drive; diesel, hybrid and electric options documented',Propulsion='Shaft',NormalizedPropulsion='Shaft',HullType='Hybrid semi-displacement',NormalizedHullForm='Semi-Displacement')
  vars=[{'Name':'Propulsion options','Description':'Diesel, diesel-electric hybrid and full-electric configurations have been offered; performance, battery capacity and range depend strongly on the installed system.','AffectedYears':'Production run','EvidenceRefs':S['Greenline39'],'Confidence':'High'}]
  norm(m,'The Greenline 39 is a two-cabin Slovenian sedan cruiser using Greenline’s efficiency-focused hull, roof-integrated solar power and a single shaft line. It is offered with diesel, hybrid and electric propulsion configurations and emphasizes low-speed efficiency and generator-reduced cruising comfort.',['Two-cabin layout with large single-level salon and cockpit','Large solar array and house battery system support quiet off-grid use','Efficient single-shaft hull can cruise economically at displacement speeds'],['Advanced electrical systems require knowledgeable maintenance','Hybrid/electric range and charging capability depend heavily on configuration','Single-engine propulsion lacks the redundancy of twins'],['Couples seeking efficient extended coastal or inland cruising','Owners who value solar-supported electrical autonomy','Buyers comfortable with modern energy-management systems'],['You require twin-engine redundancy','You want a traditional low-tech trawler','You need sustained high-speed performance without efficiency trade-offs'],['Verify diesel, hybrid or electric propulsion and battery specification','Inspect battery-management, inverter, charger and solar systems','Inspect shaft, rudder, propeller and stern gear','Inspect glazing, doors and roof openings for leakage','Confirm propulsion service history and software/control updates'],vars,S['Greenline39'])

# Nord Star
for m in [x for x in models if x.get('Manufacturer')=='Nord Star']:
 m.update(Model='31+',Variant=None,Nickname='Nord Star 31+',LOA_ft=32.97,Beam_ft=10.33,Displacement_lb=11023,FuelCapacity=137,WaterCapacity=31,HoldingCapacity=23,Berths=5,EngineCount=2,EngineConfiguration='Twin diesel sterndrives typical; maximum rated engine power 550 kW',Fuel='Diesel',NormalizedFuel='Diesel',Propulsion='Sterndrive',NormalizedPropulsion='Sterndrive',Flybridge='No',AftCabin='No',HullType='Deep-V planing',NormalizedHullForm='Planing',NormalizedHullConfiguration='Monohull',NormalizedStyle='Pilothouse Cruiser',Configuration='Walkaround Pilothouse Cruiser')
 norm(m,'The Nord Star 31+ is a Finnish all-weather walkaround pilothouse cruiser designed around protected helm operation, three-door deck access and a deep-V planing hull. Factory specifications support high-speed coastal use with substantial twin-diesel power.',['Excellent all-weather helm protection and three-door deck access','Full walkaround circulation supports docking and working the boat','Deep-V planing hull and robust hand-laminated construction target demanding coastal use'],['Twin sterndrives add maintenance and corrosion exposure','High-speed capability carries substantially higher fuel burn than displacement cruisers','Interior volume is constrained by full walkaround side decks'],['Owners cruising in cold, wet or exposed coastal conditions','Couples who prioritize deck access and helm protection','Buyers who value speed as well as all-weather capability'],['You want displacement-speed economy','You want a low-maintenance single shaft drive','You prioritize maximum interior beam over side-deck access'],['Inspect both sterndrives, bellows, transoms and corrosion protection','Inspect engine cooling, exhaust and fuel systems','Inspect pilothouse doors, windows and roof penetrations for water entry','Inspect deck and rail attachments','Verify actual engine package and maximum-rated power compliance'],[],S['NordStar31'])

# Saga
for m in [x for x in models if x.get('Manufacturer')=='Saga']:
 m.update(Model='26 HT',Variant='Hardtop',Nickname='Saga 26 HT',LOA_ft=26.35,Beam_ft=9.02,Draft_ft=3.44,Displacement_lb=5512,Fuel='Diesel',NormalizedFuel='Diesel',EngineCount=1,EngineConfiguration='Single diesel inboard; semi-planing and planing versions documented',Propulsion='Unknown',NormalizedPropulsion='Unknown',Flybridge='No',AftCabin='No',HullType='Semi-planing / planing depending version',NormalizedHullForm='Semi-Displacement',NormalizedHullConfiguration='Monohull',NormalizedStyle='Hardtop Cruiser',Configuration='Hardtop Cruiser')
 norm(m,'The Saga 26 HT is a Norwegian hardtop motor cruiser, not a double-ender aft-cabin boat. Period references describe both semi-planing and planing versions with single inboard diesel power, emphasizing compact all-weather family cruising.',['Compact hardtop provides useful weather protection','Single diesel keeps basic machinery relatively simple','Norwegian design suits practical coastal and inland use'],['Different propulsion/hull versions require individual verification','Interior and tankage data are less consistently documented than newer Saga models','Older examples may have significant owner modifications'],['Couples seeking a compact Scandinavian hardtop cruiser','Inland and sheltered/coastal cruising','Owners wanting simple single-diesel operation'],['You require a true aft-cabin layout','You need standardized modern production specifications','You expect full-displacement trawler behavior from every version'],['Confirm whether the boat is semi-planing or full-planing version','Verify shaft or sterndrive arrangement and engine installation','Inspect hardtop windows, deck fittings and cockpit enclosure','Inspect cooling, exhaust, fuel and steering systems','Verify tankage, berths and sanitation equipment on the individual boat'],[{'Name':'Hull/drive versions','Description':'Period references describe semi-planing and full-planing versions; drive arrangement and performance should be verified on each hull.','AffectedYears':'Production run','EvidenceRefs':S['Saga26'],'Confidence':'Moderate'}],S['Saga26'],'Reviewed',['Production start/end years remain less firmly documented than principal identity and dimensions.'])

json.dump(models,open(p,'w',encoding='utf-8'),indent=2,ensure_ascii=False);open(p,'a').write('\n')
xs=[m for m in models if m.get('Manufacturer') in fams]
report={'phase':'8C-13','date':today,'families':fams,'normalizedRecords':len(xs),'modelCount':len(models),'reviewed':sum(m.get('ResearchStatus')=='Reviewed' for m in xs),'initial':sum(m.get('ResearchStatus')=='Initial' for m in xs),'consolidated':[{'From':'GRNL-33-HY','To':'GRNL-33'}],'knownConcernsPromoted':0,'notableFindings':['Greenline 33 Hybrid consolidated into Greenline 33 as a propulsion variation, reducing duplicate model identities.','Fjord 36 Cruiser and 36 Open retained as distinct documented variants; the 36 Cruiser remains Initial because model-wide machinery data are incomplete.','Fjord 40 Open and 40 Cruiser retained as distinct documented variants with twin diesel propulsion; Open and Cruiser serve materially different use cases.','Saga 26 corrected from double-ender/aft-cabin displacement classification to Saga 26 HT hardtop cruiser with version-dependent semi-planing/planing characteristics.','Nord Star 31+ aligned to current factory dimensions, tankage and all-weather walkaround identity.']}
os.makedirs(os.path.join(root,'developer/reports'),exist_ok=True)
rp=os.path.join(root,'developer/reports/phase8c13-scandinavian-normalization.json');json.dump(report,open(rp,'w',encoding='utf-8'),indent=2);open(rp,'a').write('\n')
open(os.path.join(root,'developer/reports/PHASE_8C13_SCANDINAVIAN_NORMALIZATION.md'),'w',encoding='utf-8').write(f"# Phase 8C-13 — Scandinavian families\n\nNormalized {len(xs)} canonical records across Nimbus, Fjord, Saga, Nord Star and Greenline.\n\n- Reviewed: {report['reviewed']}\n- Initial: {report['initial']}\n- Consolidated duplicate model identities: 1\n- KnownConcerns promoted: 0\n- Total B-Scout models: {len(models)}\n")
print(json.dumps(report,indent=2))
