import json, os
from copy import deepcopy
root=os.path.abspath(os.path.join(os.path.dirname(__file__),'..'))
p=os.path.join(root,'boatmodels.json')
models=json.load(open(p,encoding='utf-8'))
today='2026-08-07'
families=['Back Cove','Duffy','Fortier','Hunt Yachts','Sabre','BHM','Atlantic Boat','Atlantic','Sisu','True North']
S={
'Back Cove':['https://www.backcoveyachts.com/owners/heritage-models','https://www.backcoveyachts.com/motor-yachts/back-cove-39o'],
'Duffy':['https://kraftpower.com/wp-content/uploads/2025/06/Duffy-31-Application-Page-v1-1.pdf'],
'Fortier':['https://fortierboats.com/','https://fortierboats.com/fortier-26/','https://fortierboats.com/fortier-33/'],
'Hunt Yachts':['https://huntyachts.com/wp-content/uploads/2015/11/2016-Surfhunter-29-standard-equipment-11-3-15.pdf','https://www.yachtingmagazine.com/new-coupe-hunt/'],
'Sabre':['https://www.sabreyachts.com/owners/heritage-models/sabre-38-hard-top-express','https://www.sabreyachts.com/yachts/38-salon-express','https://sabreyachts.s3.us-east-2.amazonaws.com/sabre/wp-content/uploads/2012/09/12103435/34x-specs.pdf'],
'BHM':['https://www.boatdesign.net/threads/over-weight-boat.23483/'],
'Atlantic Boat':['https://www.atlanticboat.com/'],
'Atlantic':['https://www.hmy.com/yachting/powerboat-guide/atlantic/37-double-cabin-1982-92'],
'Sisu':['https://www.reddit.com/r/boating/comments/1lav2tc'],
'True North':['https://truenorth.yachts/about/','https://powerandmotoryacht.com/boats/boat-tests/true-north-34/']}

def suit(m):
 return {
  'CoupleCruising':{'Assessment':'Good','Summary':'The documented layout and protected helm arrangement are practical for a cruising couple, with accommodation depth varying by model.'},
  'SoloHandling':{'Assessment':'Good' if (m.get('EngineCount')==1 and m.get('LOA_ft',99)<=35) else 'Mixed','Summary':'Visibility and cockpit access are generally strong; docking burden depends on size, engine arrangement and fitted thrusters.'},
  'InlandWaterways':{'Assessment':'Good' if (m.get('Beam_ft') or 99)<=13.5 else 'Mixed','Summary':'Shallow-to-moderate draft and protected helm layouts suit many inland routes, but beam and air draft remain route-specific.'},
  'ExposedWater':{'Assessment':'Good','Summary':'Downeast/lobster-derived hull forms are intended for coastal conditions, but individual hull condition, loading and configuration remain decisive.'}}

def q(items): return [f'What service, inspection or repair history is available for {x[0].lower()+x[1:]}?' for x in items]
def evidence(m,sources,status,unresolved):
 ap={'Scope':'Model','Models':[m['BoatModelID']],'Years':{'From':m.get('FirstYear'),'To':m.get('LastYear')},'Variations':[]}
 m['EvidenceSummary']={'KnowledgeCoverage':'Strong' if status=='Reviewed' else 'Partial','EvidenceQuality':'Moderate' if sources else 'Low','Statements':[
 {'Scope':'IdentityAndDimensions','AppliesTo':deepcopy(ap),'EvidenceRefs':sources,'EvidenceTypes':['Factory documented','Technical or survey source'] if sources else ['Unverified'],'Confidence':'High' if status=='Reviewed' else 'Moderate','Notes':'Representative model identity and principal specifications are based on model-specific sources where available.'},
 {'Scope':'OverviewAndSuitability','AppliesTo':deepcopy(ap),'EvidenceRefs':sources,'EvidenceTypes':['Factory documented','Technical or survey source'] if sources else ['Unverified'],'Confidence':'Moderate','Notes':'Decision guidance is derived from documented hull, propulsion, layout and intended use rather than advertising claims.'},
 {'Scope':'InspectionFocus','AppliesTo':dict(ap,Scope='Model family'),'EvidenceRefs':sources,'EvidenceTypes':['Technical or survey source'] if sources else ['Unverified'],'Confidence':'Moderate' if sources else 'Low','Notes':'Inspection items are configuration and age risks, not assertions that every hull suffers a defect.'}],
 'UnresolvedInformation':unresolved+['Legacy CommonProblems were not promoted to KnownConcerns without model-specific evidence meeting the approved threshold.']}
 m.update(ResearchStatus=status,DataConfidence='Moderate' if status=='Reviewed' else 'Low',ReviewedBy='B-Atlas Phase 8C-12 Downeast / Lobster-Style Research',LastUpdated=today,Revision=(m.get('Revision') or 1)+1)

def norm(m,overview,strengths,trade,best,avoid,insp,vars,sources,status='Reviewed',unresolved=[]):
 m['Overview']=overview;m['Suitability']=suit(m);m['Strengths']=strengths;m['TradeOffs']=trade;m['BestFor']=best;m['AvoidIf']=avoid;m['KnownConcerns']=[];m['InspectionFocus']=insp;m['BuyerQuestions']=q(insp);m['OwnerActions']=['Keep deck, window, hatch and hardware penetrations sealed','Maintain engine cooling, exhaust, fuel, steering and drive systems to documented intervals','Document structural, machinery and system modifications for future survey and resale'];m['ModelVariations']=vars;evidence(m,sources,status,unresolved)
 m['ResearchNotes']='\n\n'.join(x for x in [f'Phase 8C-12 Downeast/lobster-style normalization {today}.', (m.get('ResearchNotes') or '').strip()] if x)

# Back Cove specifics
for m in [x for x in models if x.get('Manufacturer')=='Back Cove']:
 src=list(S['Back Cove']);m.update(Flybridge='No',AftCabin='No',NormalizedStyle='Downeast Cruiser')
 unresolved=[];vars=[]
 if m['BoatModelID']=='BKCV-26':m.update(FirstYear=2004,LastYear=2010,LOA_ft=26.5,Beam_ft=9.33,Draft_ft=2.5,FuelCapacity=100,WaterCapacity=30,HoldingCapacity=30,AirDraft_ft=8.5,Displacement_lb=6000,EngineCount=1,EngineConfiguration='Single diesel inboard',Fuel='Diesel',NormalizedFuel='Diesel',Propulsion='Shaft',NormalizedPropulsion='Shaft');src+=['https://www.backcoveyachts.com/owners/heritage-models/back-cove-26']
 elif m['BoatModelID']=='BKCV-29':m.update(LOA_ft=29.5,Beam_ft=9.42,Draft_ft=2.5,Displacement_lb=10000,FuelCapacity=150,WaterCapacity=30,HoldingCapacity=30,AirDraft_ft=8.33,EngineCount=1,EngineConfiguration='Single diesel inboard');src+=['https://www.backcoveyachts.com/owners/heritage-models/back-cove-29']
 elif m['BoatModelID']=='BKCV-30':m.update(FirstYear=2011,LastYear=2019,LOA_ft=34.17,Beam_ft=11.25,Draft_ft=2.67,FuelCapacity=164,WaterCapacity=58,HoldingCapacity=29,AirDraft_ft=8.67,EngineCount=1,EngineConfiguration='Single diesel inboard');src+=['https://www.backcoveyachts.com/owners/heritage-models/back-cove-30']
 elif m['BoatModelID']=='BKCV-32':m.update(FirstYear=2016,LastYear=2020,EngineCount=1,EngineConfiguration='Single diesel inboard');src+=['https://www.backcoveyachts.com/owners/heritage-models/back-cove-32']
 elif m['BoatModelID']=='BKCV-33':m.update(FirstYear=2006,LastYear=2011,LOA_ft=34.67,Beam_ft=12,Draft_ft=3.08,FuelCapacity=185,WaterCapacity=60,HoldingCapacity=60,AirDraft_ft=12.17,EngineCount=1,EngineConfiguration='Single diesel inboard');vars=[{'Name':'33 to 34 designation change','Description':'The Back Cove 33 was relaunched/renamed as the Back Cove 34 for 2012; the two records represent a documented model evolution rather than unrelated hulls.','AffectedYears':'2006–2018','EvidenceRefs':['https://www.backcoveyachts.com/owners/heritage-models/back-cove-33','https://www.backcoveyachts.com/owners/heritage-models/back-cove-34'],'Confidence':'High'}];src+=['https://www.backcoveyachts.com/owners/heritage-models/back-cove-33']
 elif m['BoatModelID']=='BKCV-34':m.update(FirstYear=2012,LastYear=2018,LOA_ft=38.42,Beam_ft=12,Draft_ft=3.08,FuelCapacity=185,WaterCapacity=80,HoldingCapacity=40,AirDraft_ft=12.17,EngineCount=1,EngineConfiguration='Single diesel inboard');src+=['https://www.backcoveyachts.com/owners/heritage-models/back-cove-34']
 elif m['BoatModelID']=='BKCV-37':m.update(FirstYear=2009,LastYear=2020,LOA_ft=42,Beam_ft=13.25,Draft_ft=3.58,FuelCapacity=300,WaterCapacity=120,HoldingCapacity=50,AirDraft_ft=12.5,EngineCount=1,EngineConfiguration='Single diesel inboard');src+=['https://www.backcoveyachts.com/owners/heritage-models/back-cove-37']
 elif m['BoatModelID']=='BKCV-39O':m.update(Model='39O',Variant='Outboard',FirstYear=2020,LastYear=None,LOA_ft=43.5,Beam_ft=13.5,Draft_ft=2.33,FuelCapacity=520,WaterCapacity=97,HoldingCapacity=42,AirDraft_ft=12.42,Displacement_lb=22000,EngineCount=3,EngineConfiguration='Triple gasoline outboards standard; twin 600 hp outboards also offered',Fuel='Gasoline',NormalizedFuel='Gasoline',Propulsion='Outboard',NormalizedPropulsion='Outboard',NormalizedHullForm='Planing');src+=['https://www.backcoveyachts.com/motor-yachts/back-cove-39o']
 elif m['BoatModelID']=='BKCV-41':m.update(FirstYear=2014,LastYear=2024,LOA_ft=46.08,Beam_ft=14,Draft_ft=3.75,FuelCapacity=400,WaterCapacity=160,HoldingCapacity=55,AirDraft_ft=13.17,EngineCount=2,EngineConfiguration='Twin diesel inboards',Fuel='Diesel',NormalizedFuel='Diesel',Propulsion='Shaft',NormalizedPropulsion='Shaft');src+=['https://www.backcoveyachts.com/owners/heritage-models/back-cove-41']
 norm(m,f"The Back Cove {m['Model']} is a Maine-built Downeast cruiser emphasizing clean sightlines, practical cockpit-to-helm flow and efficient propulsion. The model combines lobster-boat-influenced styling with contemporary recreational construction and accommodations.",['Maine-built Downeast design with practical helm and cockpit circulation','Good visibility and side-deck access for couple cruising','Propulsion package emphasizes efficient coastal cruising for its size'],['Performance-oriented Downeast cruisers use more fuel than displacement trawlers','Accommodation volume is concentrated forward rather than in multiple private cabins on smaller models','Mechanical access and system complexity increase materially with size'],['Couples wanting traditional Downeast styling with modern systems','Coastal and inland cruising at moderate-to-fast cruising speeds','Owners who value protected helm visibility and straightforward deck circulation'],['You require full-displacement economy at 6–8 knots','You need extensive multi-cabin liveaboard volume in a short hull','You prefer a flybridge or aft-cabin layout'],['Inspect hull/deck coring around hardware and penetrations','Verify engine, cooling, exhaust and drive-system service history','Inspect hydraulic/electric helm-deck mechanisms where fitted','Confirm air draft, mast and antenna configuration','Verify tank capacities and propulsion package for the exact model year'],vars,src,'Reviewed',unresolved)

# Duffy commercial hull family - custom finish variability
for m in [x for x in models if x.get('Manufacturer')=='Duffy']:
 src=list(S['Duffy']);m.update(Fuel='Diesel',NormalizedFuel='Diesel',Propulsion='Shaft',NormalizedPropulsion='Shaft',EngineCount=1,EngineConfiguration='Single diesel inboard typical; horsepower and installation vary by finish',Flybridge='Optional',AftCabin='No',NormalizedStyle='Downeast Cruiser')
 if m['BoatModelID']=='DUFF-31':m.update(LOA_ft=31,Beam_ft=11,Draft_ft=3,Displacement_lb=11000)
 norm(m,f"The Duffy {m['Model']} is a Spencer Lincoln-influenced Maine lobster-boat hull used for commercial and recreational Downeast builds. Unlike a tightly standardized production cruiser, individual Duffy hulls may be finished by different yards or owners, so layout, machinery, tankage and accommodations can vary substantially.",['Proven lobster-boat hull form with strong coastal working-boat heritage','Single-diesel shaft installations are common and mechanically straightforward','Large cockpit and customizable interior suit fishing or cruising conversions'],['Hull-specific finish quality and equipment vary substantially','Published tankage, displacement and accommodation figures may describe one custom build rather than the hull standard','Cruising amenities depend heavily on who completed the boat'],['Experienced buyers wanting a genuine Maine lobster-boat hull','Owners prioritizing sea-kindly coastal operation and cockpit utility','Buyers comfortable evaluating a custom or semi-custom finish'],['You require standardized production-boat specifications and layouts','You want turnkey model-wide parts/documentation support','You are unwilling to verify the individual builder/finisher and equipment'],['Identify the hull builder and finishing yard for the individual boat','Inspect bulkhead, deck and house attachment quality and any later modifications','Inspect engine beds, shaft alignment, exhaust and cooling installation','Verify tank materials, capacities and installation access','Verify actual displacement, bridge clearance and accommodations rather than relying on model averages'],[{'Name':'Custom and semi-custom finish variation','Description':'Duffy hulls have been finished in different commercial and recreational configurations; machinery, house, flybridge, tankage and interior layout are hull-specific.','AffectedYears':'All production years','EvidenceRefs':src,'Confidence':'High'}],src,'Initial',['Model-wide production years and standard accommodation specifications are not sufficiently standardized to treat current legacy values as factory standards.'])

# Fortier
for m in [x for x in models if x.get('Manufacturer')=='Fortier']:
 src=list(S['Fortier']);m.update(Fuel='Diesel',NormalizedFuel='Diesel',Propulsion='Shaft',NormalizedPropulsion='Shaft',Flybridge='No',AftCabin='No',NormalizedStyle='Downeast Cruiser')
 status='Reviewed';un=[];vars=[]
 if m['BoatModelID']=='FORT-26':m.update(Model='26',FirstYear=1977,LastYear=None,LOA_ft=26.9,Beam_ft=10,Draft_ft=2.5,Displacement_lb=6500,FuelCapacity=100,EngineCount=1,EngineConfiguration='Single diesel inboard');src+=['https://fortierboats.com/fortier-26/']
 elif m['BoatModelID']=='FORT-33':m.update(Model='33',FirstYear=1988,LastYear=None,LOA_ft=33.5,Beam_ft=11.67,Draft_ft=2.67,Displacement_lb=12000,FuelCapacity=220,EngineCount=2,EngineConfiguration='Twin diesel inboards standard; IPS offered on later builds');src+=['https://fortierboats.com/fortier-33/']
 else:
  status='Initial';un=['This record duplicates the Fortier 33 identity and is retained temporarily pending controlled ID consolidation. It should not be interpreted as a separate Fortier model.'];m.update(Flybridge='No',EngineCount=2,EngineConfiguration='Twin diesel inboards')
 norm(m,f"The Fortier {m['Model']} is a New England Downeast/bass-boat cruiser based on Eldridge-McInnis design principles, with a molded keel, low profile and diesel inboard propulsion. Fortier emphasizes robust construction, fishing utility and efficient coastal performance rather than maximum interior volume.",['Strong cockpit utility and low-profile Downeast proportions','Molded keel and diesel inboard arrangement provide protected, conventional running gear','Builder support and long-running production improve documentation compared with many custom lobster hulls'],['Lower cabin volume than taller production cruisers of similar length','Traditional low-profile layout prioritizes cockpit and seakeeping over multiple private cabins','Customization means equipment still varies between individual boats'],['Coastal cruisers who value cockpit space and classic New England design','Fishing/cruising owners wanting conventional inboard machinery','Buyers prioritizing build quality over maximum interior volume'],['You need large multi-cabin accommodations','You want a flybridge or aft-cabin motoryacht','You prefer outboard-powered shallow-draft operation'],['Inspect foam-cored hull/deck around penetrations and hardware','Inspect engine room, exhaust, cooling, shaft and rudder systems','Verify custom options and later modifications','Inspect cockpit sole, scuppers and deck drainage','Confirm actual tankage and machinery package'],vars,src,status,un)

# Hunt
for m in [x for x in models if x.get('Manufacturer')=='Hunt Yachts']:
 src=list(S['Hunt Yachts']);m.update(AftCabin='No',Flybridge='No',NormalizedStyle='Downeast Cruiser')
 if m['BoatModelID']=='HUNT-29':m.update(Model='Surfhunter 29',Variant='Surfhunter',LOA_ft=29.5,Beam_ft=10.5,Draft_ft=3,Displacement_lb=9000,FuelCapacity=150,WaterCapacity=28,EngineCount=1,EngineConfiguration='Single diesel or gasoline package depending configuration',Propulsion='Shaft',NormalizedPropulsion='Shaft');
 else:m.update(Model='Surfhunter 36 Coupe',Variant='Surfhunter Coupe',FirstYear=2012,LOA_ft=36.5,Beam_ft=11.33,Draft_ft=3.25,Displacement_lb=14000,FuelCapacity=150,WaterCapacity=50,EngineCount=1,EngineConfiguration='Single diesel; pod or conventional inboard options documented',Fuel='Diesel',NormalizedFuel='Diesel',Propulsion='Pod Drive',NormalizedPropulsion='Pod')
 norm(m,f"The Hunt {m['Model']} is a performance-oriented Downeast cruiser based on C. Raymond Hunt deep-V design heritage. It combines a protected helm/coupe concept with higher-speed coastal capability and refined recreational accommodations.",['Deep-V Hunt hull heritage supports confident higher-speed coastal operation','Low-profile Downeast styling with strong helm visibility','Quality construction and well-developed recreational layouts'],['Higher cruising speed brings materially greater fuel use than displacement trawlers','Deep-V hull and performance machinery add complexity and draft compared with simple lobster-hull cruisers','Interior volume is moderate for overall length'],['Buyers prioritizing rough-water ride and speed','Couples wanting a refined Downeast day/weekend cruiser','Owners comfortable with performance-boat operating costs'],['You want 6–8 knot displacement economy','You need extensive liveaboard volume','You prioritize very shallow draft over rough-water performance'],['Inspect hull/deck laminate and hardware penetrations','Review engine, pod/shaft, exhaust and cooling service records','Inspect trim tabs, steering, thrusters and electronic controls','Verify machinery package and performance configuration','Inspect glazing, hatches and deck drainage'],[],src,'Reviewed',[])

# Sabre
for m in [x for x in models if x.get('Manufacturer')=='Sabre']:
 src=list(S['Sabre']);m.update(Fuel='Diesel',NormalizedFuel='Diesel',EngineCount=2,EngineConfiguration='Twin diesel inboards',Flybridge='No',AftCabin='No',NormalizedStyle='Downeast Cruiser')
 if m['BoatModelID']=='SABR-34-EX':m.update(Model='34 Express',Variant='Express',FirstYear=2004,LastYear=2009,LOA_ft=34,Beam_ft=13.25,Draft_ft=3,Displacement_lb=20000,FuelCapacity=250,WaterCapacity=60,HoldingCapacity=30,Propulsion='Shaft',NormalizedPropulsion='Shaft')
 else:m.update(Model='38 Salon Express',Variant='Salon Express',FirstYear=2012,LastYear=None,LOA_ft=41.75,Beam_ft=13.33,Draft_ft=3.33,Displacement_lb=21500,FuelCapacity=300,WaterCapacity=100,HoldingCapacity=40,AirDraft_ft=13.25,Propulsion='Pod Drive',NormalizedPropulsion='Pod');src+=['https://www.sabreyachts.com/yachts/38-salon-express']
 norm(m,f"The Sabre {m['Model']} is a Maine-built Downeast express cruiser combining traditional exterior proportions with higher-speed twin-diesel propulsion and yacht-finish accommodations. Sabre places more emphasis on refinement, systems integration and cruising speed than working-lobster-boat derivatives.",['High-quality Maine construction and interior finish','Protected salon/helm with good all-weather visibility','Twin-diesel performance supports fast coastal passages'],['Twin engines and integrated systems increase maintenance cost','Purchase and operating costs are high relative to simpler single-diesel cruisers','Express layout provides less exterior working space than commercial-derived lobster boats'],['Couples seeking premium Downeast cruising at planing speeds','Owners valuing finish quality and all-weather salon comfort','Coastal cruising where speed and refinement matter'],['You want minimal mechanical complexity','You primarily cruise at displacement speed for maximum economy','You need a commercial-style open cockpit and simple finish'],['Inspect propulsion service history, including pods where fitted','Inspect hull/deck coring and hardware bedding','Review electrical, HVAC, generator and integrated electronics maintenance','Inspect windows, doors and salon seals','Confirm machinery and drive configuration for model year'],[],src,'Reviewed',[])

# Low-volume hull builders
for make in ['BHM','Atlantic Boat','Sisu']:
 for m in [x for x in models if x.get('Manufacturer')==make]:
  src=list(S[make]);m.update(Flybridge='No',AftCabin='No',NormalizedStyle='Downeast Cruiser',EngineCount=1)
  if make=='BHM':m.update(Model='32',EngineConfiguration='Single diesel inboard typical',Fuel='Diesel',NormalizedFuel='Diesel',Propulsion='Shaft',NormalizedPropulsion='Shaft')
  elif make=='Atlantic Boat':m.update(Model='26 / Duffy 26',Variant='Duffy Hull',EngineConfiguration='Single diesel inboard typical',Fuel='Diesel',NormalizedFuel='Diesel',Propulsion='Shaft',NormalizedPropulsion='Shaft')
  else:m.update(EngineConfiguration='Single inboard or outboard depending hull and conversion',Fuel='Diesel',NormalizedFuel='Diesel',Propulsion='Shaft',NormalizedPropulsion='Shaft')
  norm(m,f"The {make} {m['Model']} is a Downeast/lobster-boat-derived hull whose individual finish and propulsion can vary significantly. B-Atlas treats the hull identity as useful, but not every legacy accommodation, tankage or equipment value as a factory-wide standard.",['Authentic New England working-boat hull heritage','Simple, practical coastal layout with strong cockpit utility','Individual examples can be configured effectively for fishing or compact cruising'],['Semi-custom and custom finishes create large hull-to-hull differences','Model-wide accommodation and tankage data are not consistently standardized','Older examples may have extensive owner modifications'],['Experienced buyers seeking a genuine lobster-boat-style hull','Coastal cruisers who prioritize seakeeping and cockpit utility','Owners comfortable verifying hull-specific equipment'],['You require standardized production-boat layouts and specifications','You want extensive factory model documentation','You are unwilling to investigate custom finish history'],['Confirm hull builder, finisher, year and HIN','Inspect structural additions, deckhouse and bulkhead workmanship','Inspect engine installation, exhaust, cooling and shaft/outboard conversion','Verify tankage, wiring and plumbing installations','Verify actual dimensions, displacement and accommodations'],[{'Name':'Hull-specific finishing','Description':'Commercial-derived Downeast hulls may be finished by different yards or owners, so house, machinery, tankage and interior arrangement require individual verification.','AffectedYears':'All','EvidenceRefs':src,'Confidence':'Moderate'}],src,'Initial',['Model-wide factory specifications remain incomplete; hull-specific documentation controls configuration.'])

# Atlantic 37 lineage
for m in [x for x in models if x.get('Manufacturer')=='Atlantic']:
 src=list(S['Atlantic']);m.update(Model='37 Double Cabin',Variant='Double Cabin',FirstYear=1982,LastYear=1992,LOA_ft=37.83,Beam_ft=12.83,Draft_ft=3.5,Displacement_lb=21000,Fuel='Diesel',NormalizedFuel='Diesel',EngineCount=2,EngineConfiguration='Twin diesel inboards',Propulsion='Shaft',NormalizedPropulsion='Shaft',Flybridge='Yes',AftCabin='Yes',NormalizedStyle='Trawler')
 norm(m,'The Atlantic 37 Double Cabin is a Taiwan-built trawler-style motoryacht derived from the Prairie 36 lineage rather than a Maine lobster-boat hull. It combines twin-diesel shaft propulsion, flybridge and aft-cabin accommodations for traditional low-to-moderate-speed cruising.',['Two-cabin/two-head layout supports extended cruising','Twin diesels and flybridge provide conventional motoryacht handling','Prairie-derived design has established owner history'],['Aft-cabin/flybridge configuration carries more windage and systems than a simple Downeast cruiser','Age-related deck, tank and system work can be substantial','Not a true working-lobster-hull design despite inclusion in this batch'],['Couples wanting traditional aft-cabin trawler accommodations','Extended inland and coastal cruising','Buyers comfortable with older Taiwan-built systems'],['You want a low-profile lobster-boat-style cruiser','You need minimal maintenance complexity','You require single-engine economy'],['Inspect decks, windows and flybridge penetrations for moisture','Inspect tanks, wiring and plumbing','Inspect both engines, cooling, exhaust, shafts and steering','Verify aft-cabin and interior structure condition','Confirm air draft and bridge-clearance configuration'],[],src,'Reviewed',[])

# True North original diesel record; flag later outboard as distinct missing variation/model
for m in [x for x in models if x.get('Manufacturer')=='True North']:
 src=list(S['True North']);m.update(Model='34',Variant='Original Diesel',FirstYear=2002,LastYear=2011,Fuel='Diesel',NormalizedFuel='Diesel',EngineCount=1,EngineConfiguration='Single diesel inboard on original True North 34',Propulsion='Shaft',NormalizedPropulsion='Shaft',Flybridge='No',AftCabin='No',NormalizedStyle='Downeast Cruiser')
 vars=[{'Name':'Later 34 Outboard Express','Description':'A later/revived True North 34 Outboard Express uses twin gasoline outboards and materially different performance; it should be treated as a distinct generation/model record rather than overwriting the original diesel 34.','AffectedYears':'Later production','EvidenceRefs':['https://truenorth.yachts/about/','https://powerandmotoryacht.com/boats/boat-tests/true-north-34/'],'Confidence':'High'}]
 norm(m,'The original True North 34 is a Downeast power cruiser developed before the later outboard-generation True North 34. The original B-Atlas record represents the earlier diesel/inboard cruising concept; later Catalina-era Outboard Express boats are materially different and should be tracked separately.',['Downeast styling with large cockpit and practical couple-cruising layout','Original single-diesel configuration offers simpler machinery than later twin-outboard versions','Good cockpit-to-helm flow for coastal cruising'],['The True North 34 name spans materially different generations','Original and later outboard specifications must not be mixed','Interior volume remains moderate relative to taller cruisers'],['Couples seeking an original diesel Downeast cruiser','Coastal cruising with emphasis on cockpit utility','Buyers comfortable distinguishing model generations'],['You want the later twin-outboard performance version','You need a flybridge or aft cabin','You require model data that ignores generation differences'],['Confirm whether the boat is original diesel or later Outboard Express generation','Inspect engine, exhaust, cooling, shaft and fuel systems on diesel boats','Inspect hull/deck structure and cockpit openings','Verify actual fuel/water tankage and displacement by generation','Confirm transom/propulsion configuration has not been converted'],vars,src,'Reviewed',['A separate True North 34 Outboard Express record should be added during future model acquisition rather than merging its specs into this original diesel record.'])

json.dump(models,open(p,'w',encoding='utf-8'),indent=2,ensure_ascii=False);open(p,'a').write('\n')
xs=[m for m in models if m.get('Manufacturer') in families]
report={'phase':'8C-12','date':today,'families':families,'normalizedRecords':len(xs),'modelCount':len(models),'reviewed':sum(m.get('ResearchStatus')=='Reviewed' for m in xs),'initial':sum(m.get('ResearchStatus')=='Initial' for m in xs),'knownConcernsPromoted':0,'notableFindings':['Back Cove 33 and 34 documented as a designation/evolution sequence; both retained as marketed identities.','Back Cove 39 corrected to 39O, with triple outboards standard and twin 600 hp outboard option.','Back Cove 33/39O/41 flybridge and aft-cabin legacy flags corrected to No.','Duffy models retained as hull-family records with custom/semi-custom finish variation; not overstated as standardized production cruisers.','Fortier duplicate FORT-33-DE retained Initial and flagged for later ID consolidation; it was not guessed to be a Fortier 30.','Hunt records normalized as Surfhunter 29 and Surfhunter 36 Coupe.','Sabre records normalized as 34 Express and 38 Salon Express.','BHM, Atlantic Boat and Sisu retained Initial where model-wide standard specifications remain weak.','Atlantic 37 normalized as 37 Double Cabin/Prairie-derived trawler rather than lobster-hull cruiser.','True North 34 preserved as original diesel generation; later 34 Outboard Express flagged as a distinct future model record.']}
os.makedirs(os.path.join(root,'developer/reports'),exist_ok=True)
rp=os.path.join(root,'developer/reports/phase8c12-downeast-normalization.json');json.dump(report,open(rp,'w',encoding='utf-8'),indent=2);open(rp,'a').write('\n')
md=os.path.join(root,'developer/reports/PHASE_8C12_DOWNEAST_LOBSTER_STYLE_NORMALIZATION.md')
open(md,'w',encoding='utf-8').write(f"# Phase 8C-12 — Downeast / lobster-style cruisers\n\nNormalized {len(xs)} records across {len(families)} manufacturers.\n\n- Reviewed: {report['reviewed']}\n- Initial: {report['initial']}\n- KnownConcerns promoted: 0\n- Total B-Atlas models: {len(models)}\n\nKey boundary: custom/semi-custom lobster hulls remain conservative where model-wide specifications are not standardized.\n")
print(json.dumps(report,indent=2))
