(function(root){
"use strict";
const STORAGE_KEY="bscoutResourceReviewV1";
const QUEUE_PATH="../data/resource-review-queue-v6.67.json";
let rows=[];
let selectedId=null;
const $=id=>document.getElementById(id);
const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const categoryLabels={manufacturer_source:"Manufacturer / factory",manual_technical:"Manual / technical",brochure_spec:"Brochure / specification",independent_review:"Independent review",video:"Video",owner_community:"Owner community",parts_technical_support:"Parts / technical support",historical_archive:"Historical / archive",buying_inspection:"Buying / inspection",listing_derived:"Listing-derived",unclassified:"Unclassified"};
function readLocal(){try{const v=JSON.parse(localStorage.getItem(STORAGE_KEY)||"[]");return Array.isArray(v)?v:[]}catch{return[]}}
function saveLocal(){localStorage.setItem(STORAGE_KEY,JSON.stringify(rows));renderCounts();}
function mergeRows(base,overlay){const map=new Map(base.map(r=>[r.ResourceReviewID,r]));for(const r of overlay||[])if(r?.ResourceReviewID)map.set(r.ResourceReviewID,{...(map.get(r.ResourceReviewID)||{}),...r});return [...map.values()]}
async function loadSeed(){const res=await fetch(QUEUE_PATH,{cache:"no-store"});if(!res.ok)throw new Error("Resource review seed could not be loaded");const data=await res.json();return Array.isArray(data.items)?data.items:[]}
function mode(mode){const isResource=mode==="resources";$("contributionReviewLayout").hidden=isResource;$("resourceReviewLayout").hidden=!isResource;document.querySelectorAll(".review-mode-tab").forEach(b=>b.classList.toggle("is-active",b.dataset.reviewMode===mode));if(isResource){renderQueue();if(root.BScoutCommunityAPI?.hasAdminToken?.())syncShared(false)}}
function renderCounts(){const c={pending:0,published:0,evidence_only:0,rejected:0,needs_replacement:0};for(const r of rows)c[r.Status]=(c[r.Status]||0)+1;$("resourcePendingCount").textContent=c.pending||0;$("resourcePublishedCount").textContent=c.published||0;$("resourceEvidenceCount").textContent=c.evidence_only||0;$("resourceRejectedCount").textContent=c.rejected||0;$("resourcePendingBadge").textContent=c.pending||0;}
function filtered(){const status=$("resourceStatusFilter").value,cat=$("resourceCategoryFilter").value,q=$("resourceQueueSearch").value.trim().toLowerCase();return rows.filter(r=>(status==="all"||r.Status===status)&&(cat==="all"||r.Category===cat||r.SuggestedCategory===cat)&&(!q||[r.Manufacturer,r.Model,r.Variant,r.URL,r.Title,r.SourceLabel].some(v=>String(v||"").toLowerCase().includes(q))))}
function renderQueue(){renderCounts();const target=$("resourceQueueList"),list=filtered();if(!list.length){target.innerHTML='<div class="empty-list">No resource candidates match these filters.</div>';return}target.innerHTML=list.map(r=>`<button type="button" class="queue-item${selectedId===r.ResourceReviewID?" selected":""}" data-resource-id="${esc(r.ResourceReviewID)}"><div class="queue-item-top"><strong>${esc([r.Manufacturer,r.Model].filter(Boolean).join(" "))}</strong><span class="resource-category-pill">${esc(categoryLabels[r.Category]||r.Category||"Unclassified")}</span></div><small>${esc(r.Status||"pending")} · ${esc(r.URL)}</small></button>`).join("")}
function suggestedTitle(r){try{const u=new URL(r.URL);const path=decodeURIComponent(u.pathname).split('/').filter(Boolean).pop()||u.hostname;return `${r.Manufacturer} ${r.Model} — ${path.replace(/[-_]+/g,' ').replace(/\.pdf$/i,'')}`.slice(0,180)}catch{return `${r.Manufacturer} ${r.Model} resource`}}
function openRow(id){selectedId=id;const r=rows.find(x=>x.ResourceReviewID===id);if(!r)return;$("resourceEmptyReview").hidden=true;$("resourceReviewCard").hidden=false;$("resourceReviewTitle").textContent=[r.Manufacturer,r.Model,r.Variant].filter(Boolean).join(" ");$("resourceReviewMeta").textContent=`${r.ResourceReviewID} · discovered during ${r.DiscoveredIn||"B-Atlas research"}`;$("resourceReviewStatus").textContent=(r.Status||"pending").replace(/_/g," ");$("resourceReviewContext").innerHTML=`<div class="context-grid"><div class="field-block"><span>Model ID</span><strong>${esc(r.BoatModelID)}</strong></div><div class="field-block"><span>Suggested category</span><strong>${esc(categoryLabels[r.SuggestedCategory]||r.SuggestedCategory||"Unclassified")}</strong></div><div class="field-block"><span>Current decision</span><strong>${esc((r.Decision||"Not reviewed").replace(/_/g," "))}</strong></div><div class="field-block"><span>Research facts supported</span><strong>${esc((r.SupportedFacts||[]).join(", ")||"Source relationship recorded; no field labels recovered")}</strong></div></div>${(r.EvidenceNotes||[]).length?`<div class="resource-evidence-notes"><strong>How B-Atlas used this source</strong><ul>${r.EvidenceNotes.map(n=>`<li>${esc(n)}</li>`).join("")}</ul></div>`:""}`;const a=$("resourceReviewUrl");a.href=r.URL;a.textContent=r.URL;$("resourceTitle").value=r.Title||suggestedTitle(r);$("resourceCategory").value=r.Category||r.SuggestedCategory||"unclassified";$("resourceSourceLabel").value=r.SourceLabel||"";$("resourceType").value=r.ResourceType||"";$("resourceScope").value=r.Scope||"Model-specific";$("resourceVerification").value=r.VerificationStatus||"Needs review";$("resourceNotes").value=r.Notes||"";renderQueue()}
function collect(r){return {...r,Title:$("resourceTitle").value.trim(),Category:$("resourceCategory").value,SourceLabel:$("resourceSourceLabel").value.trim(),ResourceType:$("resourceType").value.trim(),Scope:$("resourceScope").value,VerificationStatus:$("resourceVerification").value,Notes:$("resourceNotes").value.trim()}}
function message(text){const el=$("resourceQueueMessage");el.hidden=!text;el.textContent=text||""}
async function saveDecision(decision){const i=rows.findIndex(x=>x.ResourceReviewID===selectedId);if(i<0)return;let r=collect(rows[i]);if(decision==="published"&&!r.Title){alert("Enter a public resource title before publishing.");return}r.Status=decision;r.Decision=decision;r.ReviewedAt=decision==="pending"?null:new Date().toISOString();if(decision!=="published")r.PublishedAt=null;rows[i]=r;saveLocal();try{if(root.BScoutCommunityAPI?.hasAdminToken?.()){await root.BScoutCommunityAPI.saveAdminSnapshot({resourceReview:rows});message("Resource decision saved to the shared moderator queue.")}else message("Resource decision saved in this browser. Connect moderator access to share it centrally.")}catch(e){message(`Saved locally; shared sync failed: ${e.message}`)}openRow(selectedId)}
async function syncShared(showMessage=true){try{const seed=await loadSeed();let merged=mergeRows(seed,readLocal());if(root.BScoutCommunityAPI?.hasAdminToken?.()){const snap=await root.BScoutCommunityAPI.adminSnapshot();merged=mergeRows(merged,snap.resourceReview||[]);rows=merged;saveLocal();await root.BScoutCommunityAPI.saveAdminSnapshot({resourceReview:rows});if(showMessage)message(`Resource queue synchronized: ${rows.length} candidates.`)}else{rows=merged;saveLocal();if(showMessage)message("Moderator is not connected. Using the browser-local resource queue.")}renderQueue();if(selectedId&&rows.some(r=>r.ResourceReviewID===selectedId))openRow(selectedId)}catch(e){message(`Resource queue sync failed: ${e.message}`)}}
async function publishApproved(){try{if(!root.BScoutCommunityAPI?.hasAdminToken?.())throw new Error("Connect as moderator first.");await root.BScoutCommunityAPI.saveAdminSnapshot({resourceReview:rows});const result=await root.BScoutCommunityAPI.publish();message(`Published resource library updates. ${result.resourceAdditions||0} reviewed resource candidate${result.resourceAdditions===1?"":"s"} are now in the public resource overlay/library.`);await syncShared(false)}catch(e){message(`Publish failed: ${e.message}`)}}
function exportRows(){const blob=new Blob([JSON.stringify({schema:"batlas-resource-review-export-v1",exportedAt:new Date().toISOString(),resourceReview:rows},null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`batlas-resource-review-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url)}

document.addEventListener("click",e=>{const modeBtn=e.target.closest("[data-review-mode]");if(modeBtn)return mode(modeBtn.dataset.reviewMode);const row=e.target.closest("[data-resource-id]");if(row)return openRow(row.dataset.resourceId);const decision=e.target.closest("[data-resource-decision]");if(decision)return saveDecision(decision.dataset.resourceDecision)});
["resourceStatusFilter","resourceCategoryFilter"].forEach(id=>$(id)?.addEventListener("change",renderQueue));$("resourceQueueSearch")?.addEventListener("input",renderQueue);$("resourceSyncBtn")?.addEventListener("click",()=>syncShared(true));$("resourcePublishBtn")?.addEventListener("click",publishApproved);$("resourceExportBtn")?.addEventListener("click",exportRows);
(async()=>{try{rows=mergeRows(await loadSeed(),readLocal());saveLocal();renderQueue()}catch(e){message(e.message)}})();
})(window);
